### ISSUE TITLE
[Suggestion] [idea hub] [future/far future] [maybe for addon] more compat with mods/less hardcore & more hardcore recipe config options

### ISSUE THREAD

**Issue by meelock** [BeetoGuy/BetterWithMods#100]
I have a few suggestions for the future of bwm, they are as follows:
- energy compat with immersive engineering: basically modify the motor/generator block from ie to accept or produce mechanical energy (with a config option), or add a config option to add new generator blocks with compat with all mods (sorry if you already said you don't want this, but my view is that these generators would be for early game and wouldn't produce really any energy, ie: for packs centered around bwm) (derp, this might already be in the mod :P)
- hardcore recipes: basically overhaul vanilla recipes (ie, armor with straps now, better piston crafting recipe, and proper ore smelting, yeah I know that might be diverging too much from btw but that would be awesome :P), and generally change recipes to fit the bwm/btw theme.
- far future: compat with buildcraft's energy system and recipe changes to most of bc
- even farther future: compat with mods such as mek and others, but I have no idea how this would be possible, (so this mod could eventually be the early game staple)

please feel free to critique with dev standpoint, still thinking about that. (like that it would be hard to modify how immersive engineering works, etc...)

ps. I was just derping around in a test world thinking about the mod, and playing with it. thus this happened. (sorry for the long post)

pps. straying even more from original btw, some sort of better redstone. (module or other, eg, new light magnifying blocks to create almost instantaneous redstone using sunlight, or something similar) 

ppps. just had another idea, (just an idea, thought it was cool) some sort of super late game conveyer, or tube system using mechanical power. also, some sort of reinforced gearbox that doesn't break from rain, and some sort of way of transmitting mechanical energy using high-pressure fluids or similar.

**Comment by meelock** [comment]
must be perfect!

**Comment by meelock** [comment]
XD

**Comment by DaedalusGame** [comment]
Immersive Engineering compat is already a thing.
Does Buildcraft exist for 1.10? Kinda interested in porting Better than Buildcraft if i can find documentation on it.
As for better redstone, I'm currently working on a bwm addon that provides pcb blocks that allow you to control redstone connectivity more sensibly. Also you can construct a lens block and aim it at a detector block to create faraway redstone using the stuff in bwm already.

**Comment by meelock** [comment]
heya Daedalus, I guess I was more suggesting that it get more config options.

**Comment by meelock** [comment]
after thinking about it for a bit, i think native primal core compat would be really nice if that is possible.

**Comment by meelock** [comment]
Also thinking about it a lens refractor of some kind would be cool, if that fits with the idea of the mod.

**Comment by meelock** [comment]
also hey Daedalus i found [this](https://www.youtube.com/watch?v=tLKhgt14W2g) series that might help.

**Comment by meelock** [comment]
heya also there is a non-private link on the mcf post apparently :P [here](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1283298-better-then-buildcraft-outdated) on the 11 post

**Comment by meelock** [comment]
over here for my minetweeker (outdated) script for primal + bwm

**Comment by DaedalusGame** [comment]
I'll look into it whenever Buildcraft 8.0 releases. Also would you mind editing your previous comment if you have something to add and nobody replied yet? Consider that people watching the repo get an email for every comment in an issue.
