### ISSUE TITLE
BTM + Mekanism

### ISSUE THREAD

**Issue by ConvincedGaming** [BeetoGuy/BetterWithMods#101]
I recently decided to create a custom mod pack based around Better With Mods because of my love for BTW and was going to loosely base it around Better Than Buildcraft.  Also with seeing RenEvo make his appearance again got me thinking about adding Mekanism to the pack instead of BC since it's not out yet.

The crash that I'm getting happens with an almost completed pack and with just BWM and Mekanism installed and I have used quite a few different builds of Mekanism and they all create the same error.  I even had a new laptop sitting, waiting for me to set it up.  Everything is freshly installed in it, same crash.

Forgot to mention that I was able to create this crash when I would try and place a digital miner, but it might also trigger by just right clicking air with the digital miner in your hand.  Tested in the Overworld and the Nether.

http://pastebin.com/Z8k49HjL

Crash log here

**Comment by BeetoGuy** [comment]
Yeah, looks like my guess was right, reviewing Mekanism's ItemBlock for that block. I'll push the fix and then upload a hotfix.
