### ISSUE TITLE
(close please) [suggestion] [minetweaker] multiple input recipes.

### ISSUE THREAD

**Issue by meelock** [BeetoGuy/BetterWithMods#104]
It would be nice if the ability to add couldron/crucible recipes using minetweaker, that need more than one item to craft.

As always conversation is apprecated.
- meelock

**Comment by meelock** [comment]
Turns out this has partially been implemented, but I'm still having issues.

**Comment by DaedalusGame** [comment]
I would understand this if it said multiple output, because multiple output recipes are crap right now, but what's wrong with the multi-input ones?

**Comment by meelock** [comment]
Ok then, I don't even know why that wasn't working for me. Please close this issue!

thanks for you patience.
