### ISSUE TITLE
[Bug] Windmill doesn't have a spinning animation in the nether

### ISSUE THREAD

**Issue by MechWarrior99** [BeetoGuy/BetterWithMods#107]
When you put the windmill in the nether it does not spin. But it will still make power. 

It just looks sort of funny, but not real important.

**Comment by BeetoGuy** [comment]
The standard windmill isn't supposed to function in the Nether regardless, I need to look into fixing that.

**Comment by MechWarrior99** [comment]
I figured as much. Though I do sort of like it working in the nether. Would you be open to having it work in the nether? Or is there reason I don't know about that would break if it could work.

**Comment by BeetoGuy** [comment]
The original reasoning for the horizontal windmill not working in the Nether is due to there not being a true source of wind there, so vertical windmills would be needed in order utilize more space to harness the convection currents instead.

**Comment by MechWarrior99** [comment]
Oh, okay. I didn't realize that the vertical windmill would work in the nether(found new bug and making a new issue for it). That makes sense.
