### ISSUE TITLE
[Bug] AIOT from Actually Additions are not handled as axes.

### ISSUE THREAD

**Issue by garantiertnicht** [BeetoGuy/BetterWithMods#110]
The Actually Additions AIOT should replace every tool (like the Paxel), but It does not give logs whith Better With Mods installed, instead barks, planks and the dust. Issue at Actually Additions: https://github.com/Ellpeck/ActuallyAdditions/issues/326

**Comment by Ellpeck** [comment]
@BeetoGuy: I woudln't know how to fix this on my part.
However, I override the getToolClasses() method and in there, I specify that it's a pickaxe, an axe and a shovel at the same time. Can you somehow query that, or is there something I have to do?

**Comment by BeetoGuy** [comment]
I can probably do that, let me take a look.
