### ISSUE TITLE
Hibachi Issue

### ISSUE THREAD

**Issue by luke-eloquate** [BeetoGuy/BetterWithMods#116]
Hi Beeto! I've been trying out the mod today ( and been having a lot of fun! ) and ran into an issue with my first Hibachi. The fire would not stay lit ( using the old Better than Wolves wiki for guidance I don't believe this should happen? ). After re-lighting the flame for the 3rd of 4th time the Hibachi just disappeared from the world altogether! Haven't put the resources together to test again with a second yet but thought I would let you know regardless. Cheers.

**Comment by BeetoGuy** [comment]
I'm running on the assumption that you're trying flint and steel instead of a redstone signal, and managed to replicate it. Oh my god, that is an amazing bug.

**Comment by luke-eloquate** [comment]
hahaha as long as it's not just me :D
