### ISSUE TITLE
Add ability to smelt ores in kiln

### ISSUE THREAD

**Issue by primetoxinz** [BeetoGuy/BetterWithMods#122]
This should likely use ore dict to find "ore*" -> "ingot*"

**Comment by DaedalusGame** [comment]
More like ore* and smelting recipe (maybe x2 like it is in btw) or you'll end up with redstone ingots if you put redstone ore into a kiln yo

**Comment by primetoxinz** [comment]
is it x2 in btw? it shouldn't be. in btw ores always give a single nugget not matter how smelted

**Comment by DaedalusGame** [comment]
If you put an ore into a kiln you get two nuggets iirc

**Comment by primetoxinz** [comment]
Nope, it is just faster than a furnace
