### ISSUE TITLE
Incompatibility with Tinkers Construct

### ISSUE THREAD

**Issue by WesCook** [BeetoGuy/BetterWithMods#129]
There appears to be a conflict with Tinkers Construct when the Tinkers setting `B:TinkerGadgets` is set to false (TinkerModules.cfg).

Crashlog: http://pastebin.com/GRjjHR8U

Using latest builds of each:

* Forge v12.18.2.2125
* Better With Mods v0.13.1-1.10.2-hotfix3
* TConstruct v1.10.2-2.5.6b

**Comment by BeetoGuy** [comment]
I think that's going to be taken out in the next build regardless with the filtered hopper rewrite.

**Comment by WesCook** [comment]
Just to confirm, this crash still occurs in the latest builds of Better with Mods and Tinkers.  It's not a show-stopper for me, but the intended fix may not have worked.

* Forge v12.18.3.2185
* Better With Mods-0.14.2-1.10.2-hotfix1.jar
* TConstruct-1.10.2-2.6.1.jar
