### ISSUE TITLE
Windmill issues

### ISSUE THREAD

**Issue by xenoflot** [BeetoGuy/BetterWithMods#133]
Hi,

I've been playing around with BWM in creative today and found some issues with the windmills.

* If I place a column of 7+ axles (say, 8-10), tapping one of the upper axle blocks with a vertical mill usually results in the "too few vertical axles" error. However if I tap one of the lower ones, it will recognise and place the mill. However...

* When the vertical mill is placed, it looks like a regular mill and it doesn't turn.

* When a regular mill (with horizontal gearbox) nearby, ONE blade of the vertical mill rotates in sync with the regular mill! There are no particles coming from the gearbox and if closer than about 12 blocks, the rotation stops.

* Additional axles can be placed on or perpendicular to a regular mill's main axle and additional mills can be placed on those axles. The resulting contraption is awe-inspiring, if slightly unwieldy :-)

* While I'm writing this, it started raining and the gearbox disintegrated. I'm assuming this is intended. What's probably not intended is that the mills are still suspended in mid-air.

This image attempts to illustrate what's happening: http://i.imgur.com/Ij2KOan.png

Cheers!

BWM 0.13.1-1.10.2-hotfix3
Forge 2122
MC 1.10.2

**Comment by DaedalusGame** [comment]
4 and 5 are intended, I'm pretty sure. It's been that way in BTW iirc.
The other ones seem like quality beeto code =P

**Comment by xenoflot** [comment]
I'm not sure that 4 is intended. This is what I'm talking about: http://i.imgur.com/RAvVFSm.png
Physics, as much as some suspension of disbelief is required in Minecraft, don't work that way!

As to 5, I can believe the gearbox disintegrating is intended but I would've thought the attached mills should fall to the ground when it does.

**Comment by BeetoGuy** [comment]
Found what's going wrong with the vertical windmill placement, at least. Everything else will probably need to be looked at.
