### ISSUE TITLE
Filtered Hopper not accepting Items

### ISSUE THREAD

**Issue by zcorcoran** [BeetoGuy/BetterWithMods#14]
It would appear that the Filtered Hopper is not accepting items dropped onto it, which renders Hellfire Dust production impossible.  Both powered and unpowered hoppers exhibit this behavior, whether they're above a valid container or not, and for any item.

The dropped items just behave like they've been dropped on any old block:
http://i.imgur.com/ELpRp4t.png

I replicated this issue with a fresh instance of 10.2 with only Forge 12.18.1.2076 and Better With Mods 0.9.2 beta.

EDIT: OK, I did a little more testing.

A powered hopper **will** drop its items onto the ground if you put them into its inventory via the GUI. It **will not** insert items into chests. Ground Netherrack that's manually inserted into a powered hopper's inventory also will not do anything if an urn is under the hopper, and will just fall out if nothing is under it (I'm assuming it _has_ to be dropped on top of the hopper anyway, what with the conceit of being filtered through the soul sand and all).

So it looks like hoppers aren't accepting items from the top nor are they inserting into inventories (which I think they did before?)

**Comment by BeetoGuy** [comment]
Oh, okay, I'm definitely getting it on that version, as well. I'm going to compile 0.10 for a test instance to see if it's still present outside the dev environment.

**Comment by BeetoGuy** [comment]
Alright, I can confirm that it's been fixed for the next version.
