### ISSUE TITLE
List of features left to port

### ISSUE THREAD

**Issue by primetoxinz** [BeetoGuy/BetterWithMods#141]
This is a list of original features that are not currently in this mod.
Some of these are not necessarily possible with the current features in forge, at least not in a reasonable way that doesn't require heavy coremodding or the like. Unlikely features are marked with *
- [ ] Blood Wood Trees
- [ ] Abandoned Villages*
- [ ] Bellows Blowing Items
- [ ] Infernal Enchanter (WIP)
- [ ] Soap
- [ ] Hardcore Movement 
- [ ] Hardcore Armor/ Hardcore Protection (Partially)* 
- [ ] Hardcore Enchanting 
- [ ] Hardcore Beacons
- [ ] Hardcore Bouncing
- [ ] Hardcore Chickens
- [ ] Hardcore Fishing
- [ ] Hardcore Lactation
- [ ] Hardcore Ores
- [ ] Hardcore Player Names
- [ ] Hardcore Sinkholes
- [ ] Hardcore Packing*
- [ ] Hardcore Darkness
- [ ] Hardcore NothingToWorryAbout
- [ ] Hardcore Hoofsies
- [ ] Dirt,Gravel,Sand slabs
- [ ] Hardcore Brewing
- [ ] Blight
- [ ] Nether Groth
- [ ] Jungle Spiders
- [ ] Hardcore Stratification kinda*
- [ ] Hardcore Smelt*
- [ ] Hardcore Piles
- [ ] Mystery Meat
- [x] Hardcore Decapitation
- [x] Hardcore Melons
- [ ] Lightning Rod
- [ ] Cement

**Comment by blueyu2** [comment]
I could work on porting my old mod [Strata](https://minecraft.curseforge.com/projects/strata) into BWM. Not sure if I can port the dynamic texture generation, considering all the rendering changes that have taken place since 1.7.

**Comment by YaibaToKen** [comment]
Cant the stratification be done in a similar way to the TerraFirmaCraft or Mineralogy mods? I mean, having several stone blocks, with different textures and hardnesses and changing worldGen to use these isntead?

**Comment by DaedalusGame** [comment]
I think that's the idea, yeah

**Comment by Koward** [comment]
I believe it's one of the best hardcore feature in BTW. It just stops optimized branch mining and forces you to travel through caves, which generates a lot of fun encounters and situations.
I have it working with vanilla blocks, but with fixed textures. We would need dynamic texture filters to apply it on mod ores so they don't seem highlighted in caves. That's really the only problem.
