### ISSUE TITLE
[Request] Config to disable Hemp seed drops

### ISSUE THREAD

**Issue by WesCook** [BeetoGuy/BetterWithMods#166]
I'm currently building a pack which includes both Immersive Engineering and BetterWithMods.  However both mods add hemp seed and hemp crop (among other things).

I'd like to be able to use just IE's hemp and disable BWM's for balance/aesthetic reasons.  I was able to make it compatible with BTW's stone mill thanks to oredict support.  As far as I know however, there's no way to disable seed drops.

A config to disable seed drops for BTW hemp would be much appreciated.

**Comment by DaedalusGame** [comment]
This seems scantly related to #22, wherein "config" was mentioned in every single comment but no configs were ever done 👍

**Comment by WesCook** [comment]
Thank you.  :)
