### ISSUE TITLE
Allow Cooking pots to output to inventories

### ISSUE THREAD

**Issue by primetoxinz** [BeetoGuy/BetterWithMods#169]
Specifically so IE conveyor belts work

**Comment by DaedalusGame** [comment]
but why
just tip it

**Comment by primetoxinz** [comment]
that's what I mean, tip directly into an inventory

**Comment by DaedalusGame** [comment]
oh
maybe they could instead drop their items into non opaque blocks for IE conveyors?

**Comment by primetoxinz** [comment]
yeah, that would probably work
