### ISSUE TITLE
Conflict with Vanilla and Steel Anvil

### ISSUE THREAD

**Issue by primetoxinz** [BeetoGuy/BetterWithMods#172]
Unlike BTW, we can't straight up remove the vanilla anvil and make it the Dead Weight, yet having a conflicting name would get confusing.
@BeetoGuy and I have talked about it and think it would be cool to remove the ability to add enchants with the vanilla anvil while still keeping the ability to repair. Along with this we would remodel and rename it to a Rune Forge.

**Comment by Koward** [comment]
A config option to remove this and keep the original BTW balance (where repairing is done by smelting in Crucible and recrafting the tool) would be nice.
