### ISSUE TITLE
[Bug] Vertical Windmills issue

### ISSUE THREAD

**Issue by MysticAura** [BeetoGuy/BetterWithMods#182]
MC: 1.10.2
Forge: 2166
Mod: Better With Mods-0.13.1-1.10.2-hotfix3

When you place a vertical windmill, it turns into a normal windmill. Breaking it results in getting a normal windmill back

**Comment by BeetoGuy** [comment]
Already been fixed in development, I'll try to push an update as soon as everything else seems to be in order.
