### ISSUE TITLE
Issue with SpongeForge 

### ISSUE THREAD

**Issue by FiveEYZ** [BeetoGuy/BetterWithMods#184]
Holding a item in hand and do a right-click in the air generates a error with SF installed.

Running with:
Forge 2171
SF 1933
Better With Mods-0.13.1-1.10.2-hotfix3

Here are some logs:
[fml-server-latest.log](https://gist.github.com/FiveEYZ/280401771f389ab9bfd46afe902d9e29)
[latest.log](https://gist.github.com/FiveEYZ/d6e898136a736b1adcc6d5e950ce7222)

Original issue:
https://github.com/SpongePowered/SpongeForge/issues/1069

**Comment by DaedalusGame** [comment]
SpongeForge might be firing the wrong event. The EventHandler specifically demands RightClickBlock, but gets it even when it should only get RightClickEmpty.

**Comment by primetoxinz** [comment]
Cleaning issues, open a new one if still an issue
