### ISSUE TITLE
[Bug] Hard Crash when respawning at base

### ISSUE THREAD

**Issue by MysticAura** [BeetoGuy/BetterWithMods#187]
MC: 1.10.2
Forge: 2166
Mod: Better With Mods-0.13.1-1.10.2-hotfix3

After dying, when it tried to respawn me at my base (within range of a BWM water mill) I crashed to desktop.

[Crash Log](http://pastebin.com/WcMcpvRe)

**Comment by BeetoGuy** [comment]
I think this was fixed a while back, I just haven't tried pushing an update. I'll see if everything's sorted for an update and try to push one when I get back from errands in a few hours.
