### ISSUE TITLE
Psi CADs can debark trees

### ISSUE THREAD

**Issue by KnightMiner** [BeetoGuy/BetterWithMods#200]
Right clicking on a log with a Psi cad debarks it. This happens even if the cad additionally runs a spell. Really odd issue, but looking at the code it makes sense as [the CAD declares itself an axe](https://github.com/Vazkii/Psi/blob/master/src/main/java/vazkii/psi/common/item/ItemCAD.java#L467) for the sake of being able to harvest all blocks.

Though I doubt its relevant, I am using Using Better With Mods 0.14.2-hotfix1 and Psi 1.0-42, both for 1.10.2

**Comment by KnightMiner** [comment]
Still happening in Better With Mods 0.14.4 Beta.

I feel like its related to the first part of the function, as `playerStack.getItem().getHarvestLevel` returning true treats it as an axe, but its a little hard to tell exactly.

**Comment by BeetoGuy** [comment]
Oh yeah, I didn't notice that.
