### ISSUE TITLE
CraftTweaker recipes not showing in JEI

### ISSUE THREAD

**Issue by WesCook** [BeetoGuy/BetterWithMods#201]
Due to a recent change between CraftTweaker and JEI, native CraftTweaker integration needs to be updated.  Recipes still work but aren't displaying correctly.

[This thread](https://github.com/jaredlll08/CraftTweaker/issues/127) has more info.  See the same bug over on the [Immersive Engineering tracker](https://github.com/BluSunrize/ImmersiveEngineering/issues/1837).

**Comment by BeetoGuy** [comment]
Looks like the solution given isn't working on my end. I'll try and see what's going on and get this resolved.

**Comment by primetoxinz** [comment]
I have a rewritten CraftTweaker support in the major refactor branch that I can port back to master

**Comment by BeetoGuy** [comment]
It's worth a shot.

**Comment by primetoxinz** [comment]
[Here](https://www.dropbox.com/s/m1oz543a64om20j/Better%20With%20Mods-0.14.2-1.10.2-test.jar?dl=0) is a test build with new CraftTweaker support, it now requires [MTLib](https://minecraft.curseforge.com/projects/mtlib/files/2363351) 1.0.1 or greater to show jei recipes

**Comment by WesCook** [comment]
I found none of my rules worked with the test builds (using latest CraftTweaker and MTLib).  Have the function names changes at all?

![crafttweaker](https://cloud.githubusercontent.com/assets/792101/21698044/13971b34-d34a-11e6-9698-647d34410aab.png)

For instance, the first error line comes from:

`mods.betterwithmods.Mill.add(brimstone, null, [<minecraft:netherrack>]); // Brimstone - Millstone`

**Comment by primetoxinz** [comment]
yeah, accidentally changed 'add' to 'addRecipe', already fix it in the code

**Comment by primetoxinz** [comment]
[Here](https://www.dropbox.com/s/275u6fvtkj1mybd/Better%20With%20Mods-0.14.2-1.10.2-test2.jar?dl=0) is a fixed version

**Comment by WesCook** [comment]
It's better.  I'm still getting errors while removing Cauldron, Stoked Crucible, and Steel Anvil recipes.

Though I haven't used every recipe type so this isn't conclusive.

**Comment by primetoxinz** [comment]
what are the errors for those?

**Comment by WesCook** [comment]
`mods.betterwithmods.Cauldron.remove(<minecraft:gunpowder>);` yields "ERROR: Error removing cauldron Recipe for Gunpowder"

`mods.betterwithmods.StokedCrucible.remove(<minecraft:iron_ingot> * 3);` yields "ERROR: Error removing crucibleStoked Recipe for Iron Ingot"

`mods.betterwithmods.SteelAnvil.remove(<betterwithmods:steel_sword>);` yields "ERROR: Error removing steelAnvil Recipe for Soulforged Steel Sword"

**Comment by primetoxinz** [comment]
should be fixed with my most recent commit

**Comment by BeetoGuy** [comment]
Well, it looks like everything needed to update was done on our end, but it seems to be persisting. I guess this would be a "everything's fine here" situation.

**Comment by MechWarrior99** [comment]
So, what is the current status on this?

**Comment by BeetoGuy** [comment]
Looks like the issue's persisting. I'm starting to think that there's something we missed, but I can't see what.

**Comment by BeetoGuy** [comment]
I might have it figured out. Since the entire thing relies on collecting the recipes to put them into the recipe wrappers, it doesn't really refresh. There would need to be some way for the handlers to get the recipes from the list directly to put into the wrapper itself.
