### ISSUE TITLE
Hardcore Stumping Transparency Issue

### ISSUE THREAD

**Issue by WesCook** [BeetoGuy/BetterWithMods#202]
This one is easier to show than to explain.

![2017-01-05_20 33 52](https://cloud.githubusercontent.com/assets/792101/21707722/7549e2e4-d386-11e6-9976-01744404f9cf.png)

The bottom block is a stump.  I'd noticed some quirky behavior with the transparency on the ground, but up in the air with clouds it's even more obvious.

I should also note that stumps don't respect Hardcore Lumberjack, and will still drop bark (I can submit as a separate bug report if you'd prefer).

**Comment by Koward** [comment]
Probably related with how the whole block is stated as translucent to allow overlays over standard wood textures..
About drops, a separate bug report could be useful (with what you used to break it, hand or stump remover, what you got and what should be the expected loot). ATM I think in both cases drops are identical.

**Comment by Koward** [comment]
The approach was chosen mostly to keep one texture applied on all vanilla logs. If only for texture packs.
I'm not sure how blockstates could fix this. As far as I know it allows to change the rendering based on state, but here we need it all the time, and one would take precedence over the other.

**Comment by WesCook** [comment]
Do you mean the variants feature of blockstates?  You could draw the appropriate texture for each log (which still works with resource packs) and overlay the stump texture using layers.  Variants would also be useful for having only a single blockstate file but setting the bottom layer based on the tree type.

Sorry if I've misunderstood you.  I can draw up an example if you're interested though.

**Comment by Koward** [comment]
I'm not aware of an other method to apply a layer other than drawing it in the model (like grass does and like what is done for stumps at the moment). If that exists then yeah that could be the solution.
Note we already have only one blockstate file for the stump, here : 
https://github.com/BeetoGuy/BetterWithMods/blob/master/src/main/resources/assets/betterwithmods/blockstates/stump.json
The model is there:
https://github.com/BeetoGuy/BetterWithMods/blob/master/src/main/resources/assets/betterwithmods/models/block/stump.json

**Comment by WesCook** [comment]
Hey Koward,

Sorry, but I think I misspoke.  I was sure it was possible to apply multiple textures in layers to a model (or directly to a blockstate), but I'm not able to find anything on it for blocks, only items.  I must have misremembered.  Sorry about that!

I was able to find a method [described by TheGreyGhost](http://www.minecraftforge.net/forum/index.php?topic=32015.msg167329#msg167329) of having two overlapping faces with a small offset, or using multiple render layers (which is what I assume you're doing above).  Might lead you in the right direction anyway.

**Comment by KnightMiner** [comment]
No, it's possible, you just need to set the block render type to cutout so the texture is not filled in.

**Comment by Koward** [comment]
Cutout implies pixels are either completely transparent or not transparent at all. The current overlays have transparency 0<alpha<255. I may replace it by per-log overlays with opaque pixels, some stumps look a bit bad with current textures anyway.
