### ISSUE TITLE
Hardcore spawn doesnt work unless you set your spawn

### ISSUE THREAD

**Issue by TheCorruption** [BeetoGuy/BetterWithMods#203]
Tested on 0.14.2-hotfix1 and forge-12.18.3.2185.

**Comment by Koward** [comment]
Hardcore spawn has a ~20min cooldown, did you take that in account ?
Also, does it take you back to the spawn point you set or to 0,0 ?

**Comment by TheCorruption** [comment]
Sorry, I didn't know about the cooldown, that's most likely what was happening.
