### ISSUE TITLE
Soulforged steel tool parts in tinkers are called "material.soulforgedsteel.name"

### ISSUE THREAD

**Issue by TheCorruption** [BeetoGuy/BetterWithMods#205]
Tested on the latest versions of tinker's construct and better than wolves.
![2017-01-08_00 57 26](https://cloud.githubusercontent.com/assets/22695945/21747982/1a45dcfe-d53e-11e6-8d55-9320a3670000.png)

**Comment by BeetoGuy** [comment]
I don't think it's critical enough to warrant a new release, but the line changes in the localization file can fix it.
