### ISSUE TITLE
Hopper Problems with Botania

### ISSUE THREAD

**Issue by 63502** [BeetoGuy/BetterWithMods#206]
There seems to be a bug with the hopper that this mod adds. The bug is as follows:

1. Place hopper(the wooden one that sifts)
2. Place soul sand into hopper's filter slot
3. Drop netherrack dust on top of the hopper.
4. The hopper drops a hellfire dust that I pick up
5. Repeat 3 any number of times after picking up the hellfire dust
6. The hopper eats the dust and makes ghast noises, breaks, spawns a ghast, and drops the dust it ate along with the soul sand used as a filter and some broken pieces.

Only one hellfire dust seems to drop per world regardless of the number of hoppers I place, use, and/or break in the world. the ghast spawning  always happens after the first dust drops, and the hopper attempts to spawn ghasts regardless of whether an urn is present under the hopper or not.

Whatever kind of bug or user error this is, it has prevented me from progressing in the mod. Is there any way to fix this? Am I doing something wrong?

Thanks,
63502

**Comment by primetoxinz** [comment]
The hopper needs to be powered

**Comment by 63502** [comment]
I tried that. All it does is stop the ghast spawning occasionally and cause anything inside of the hopper's inventory to fall through the bottom without doing anything. The Nether dust behavior is unaffected..

**Comment by BeetoGuy** [comment]
Hellfire dust seems to be dropping every time I throw one in. What version are you on?

**Comment by 63502** [comment]
0.14.1 Beta hotfix 1 for BwM

Forge is 12.18.3.2185

**Comment by BeetoGuy** [comment]
Yeah, that's a bit outdated, try updating to the latest and see if the problem persists. Everything looks right on our end.

**Comment by 63502** [comment]
Sorry, I made a mistype above.

BwM version is 014.4 Beta hotfix 1. It is the latest version.

**Comment by BeetoGuy** [comment]
Seems to still work in any scenario on my end. I can't imagine what would cause a bug like that.

**Comment by primetoxinz** [comment]
What other mods do you have?

**Comment by 63502** [comment]
A lot.
I'm not looking forward to testing each and every one of them them either. :P 

I can have a list up, but it will be a little while.

**Comment by primetoxinz** [comment]
go into the your mods folder, open a command prompt and type `dir >> modlist.txt` then upload that to pastebin

**Comment by 63502** [comment]
[Mod List](https://gist.github.com/63502/28f1dc879ae1d1c24f3b9a00fa6394c9)

I just pulled this out of a recent crash log.
Be warned, there is a completely unrelated crash caused by the listed versions of Modular Utilities(0.4.2) and BASE(1.2.2) being in the same folder together. It is advisable to NOT keep them that way for testing purposes.

**Comment by SimonMeskens** [comment]
I have the same issue on my server

mods in common with OP:
- Botania
- Quark
- FastLeaveDecay

**Comment by SimonMeskens** [comment]
Issue doesn't happen without Botania, confirmed. This is a problem with BWM + Botania

**Comment by SimonMeskens** [comment]
@BeetoGuy 
Managed to make it happen on an instance with just BWM installed now, not sure why removing Botania fixed it last time, it's a total heisenbug.

Apparently it only happens with HC Buoy turned off.

Steps to reproduce:

- turn off HC Buoy
- throw ground netherrack into the hopper one by one, slowly, for a while
- you start to see weird item stacks popping up
- pick up all the hellfire dust
- throw in more ground netherrack one by one, it will just eat them and not spit out anything

**Comment by BeetoGuy** [comment]
Yep, that's totally replicable. Guess it's something in the filtered hopper itself.

**Comment by BeetoGuy** [comment]
And this bug is officially squashed.
