### ISSUE TITLE
Hardcore Buckets don't work with Clay Buckets

### ISSUE THREAD

**Issue by SamGunGraven** [BeetoGuy/BetterWithMods#209]
Clay Buckets mod can place water in the world, tested on latest for 1.10.2

**Comment by BeetoGuy** [comment]
Yeah, looks like it's using the old version of fluid handling, which we aren't really looking for.

**Comment by primetoxinz** [comment]
info saved [here](https://github.com/BeetoGuy/BetterWithMods/projects/2)
