### ISSUE TITLE
Hardcore Buckets fails if WTF Expedition is installed

### ISSUE THREAD

**Issue by SamGunGraven** [BeetoGuy/BetterWithMods#210]
If WTF Expedition mod (with Gameplay module turned on) is installed Hardcore Buckets does noe work - water stays in the world after being placed.

Posted in Issue tracker for WTF Expedition as well.

**Comment by BeetoGuy** [comment]
Looks like nothing's really conflicting. It might be Clay Buckets using the deprecated fluid handling library, as stated in #209

**Comment by SamGunGraven** [comment]
This was using a normal Bucket and not Clay Buckets - the two issues are not related but found separately in testing new modpack

**Comment by BeetoGuy** [comment]
Seems to be working on my end. The only time it should place a source is if you're in creative mode.
