### ISSUE TITLE
Crash with HarderOres mod installed

### ISSUE THREAD

**Issue by MechWarrior99** [BeetoGuy/BetterWithMods#211]
Hey, I am not sure if this is your fault or not. But I see Better with mods in the crash log so I thought I would report it here first. If I have Better with mods and Harder ores both installed at the same time the game crashes. 

**Game Version:** 1.10.2
**Forge Version:** 12.18.3.2215
**Mods installed:** 
Better With Mods 0.1.14.4 Beta Hotfix
HardLib
Custom Ore Gen 1.4.2
Ore Flowers 1.1.0b
Harder Ores 1.1.0b
**Crash Report:** [Here](http://pastebin.com/VZaBYUPt)

**Comment by BeetoGuy** [comment]
Looks like the new names for tile entities are conflicting with the ones Harder Ores add. Seems like an easy enough fix.
