### ISSUE TITLE
[Config Request] Disable piles of Dirt/Sand/Gravel

### ISSUE THREAD

**Issue by WesCook** [BeetoGuy/BetterWithMods#217]
Hey devs,

The new dirt piles seem like a good option for hardcore packs.  I'd appreciate if this could be disabled for packs that aren't looking to modify vanilla mechanics though.  Could a config be added?

If one already exists, my apologies.  I compared my old config file to the new and only saw a new line to disable enchanting*, so there doesn't appear to be an option currently.

*Side note: You might want to invert the language on this one.  All the "Hardcore X" features are defaulted to true, but this is written as "Disable X" and defaulted to false.  A bit inconsistent.

**Comment by BeetoGuy** [comment]
It was put in on the 1.11.2 branch, I'll just backport that real quick and see if there's anything else to do before uploading a new build.
