### ISSUE TITLE
[Bug] Hardcore Spawn

### ISSUE THREAD

**Issue by ivanovic77** [BeetoGuy/BetterWithMods#219]
Currently hardcore spawn doesn't work as intended in the last version 
(Better With Mods-0.14.6-1.10.2) . You can return to the world spawn by killing yourself. How to reproduce the bug:

1. Start a new game.

2. Wait one minecraft day, until dawn of the next day.

3. Kill yourself.

4. In this first death, hardcore spawn works as intended and makes you respawn far away from the world spawn. But...

5. Kill yourself immediately, and you'll return to the world spawn.

**Comment by Koward** [comment]
There is a cooldown.

**Comment by ivanovic77** [comment]
That's it. It seems that the HC spawn only works one time after the cooldown. The second time, it sends you back to the world spawn (around coordinates x:0, z:0 indeed).

**Comment by primetoxinz** [comment]
Took a look at this, seems you just got lucky. if you have any more information reopen this.
