### ISSUE TITLE
Tall grass blocks drop Hemp seeds

### ISSUE THREAD

**Issue by Koward** [BeetoGuy/BetterWithMods#22]
Tall grass blocks drop Hemp seeds when harvested. Hemp seeds should only be available by tilling grass/dirt blocks into farmland.

Source : [BTW Change log Version 4.8913 September 3rd, 2013](http://www.sargunster.com/btw/index.php?title=Change_log#Version_4.8913)

> Removed the Hemp Seed drop entirely from tall grass to make the method of obtaining it more clear cut, and because the existing rate had become so low that it was just encouraging people to do a lot of tedious grinding punching grass in the early game. If you want to find Hemp Seeds, the method to do so is through tilling regular grass blocks. If you want to lure chickens in the early game, look for pumpkins.

**Comment by primetoxinz** [comment]
Maybe add this as a hardcore config that is disabled by default

**Comment by Koward** [comment]
Tilling farmland is not really hardcore.
You may think however that removing wood and stone hoe is hardcore, but that's a different thing.
Even for players that play in easy everything non-hardcore, I don't think getting a wooden hoe is hard.

**Comment by primetoxinz** [comment]
people are picky, it doesn't make much difference if you get it from grass or tiling to us, but it will confuse people

**Comment by BeetoGuy** [comment]
It might be beneficial to keep it consistent with other mods, instead of hooking into tilling soil.

**Comment by Koward** [comment]
If people try the mod because they played BTW in the past, they may expect the same behavior they have seen in the original mod.
I think we agree in hardcore mode it has to be through tilling anyway, else the progression tree is broken, and at the moment hardcore things are enabled by default but can be disabled.
So it's a matter of consistency with BTW vs consistency with other mods, dilemma =) !
So an hardcore hemp config then ?

**Comment by BeetoGuy** [comment]
Yeah, I think "when in doubt, config it" is a good strategy.

**Comment by primetoxinz** [comment]
if we do a hemp config, might as well throw in the other seeds into that as well

**Comment by BeetoGuy** [comment]
My main concern with that is other mods that may have different methods of obtaining crops, such as Pam's Harvestcraft.

**Comment by primetoxinz** [comment]
Closing to clean up issues
