### ISSUE TITLE
Many other mod saplings are oak trees when grown.

### ISSUE THREAD

**Issue by Claycorp** [BeetoGuy/BetterWithMods#220]
I assume that Hardcore Stumping is messing with other mods.
Saplings that I have been having issues with:
Integrated Dynamics
All Tinkers slime saplings (Also replaces slime dirt with regular dirt)
Tech Reborn 
Totemic

**Comment by BeetoGuy** [comment]
Game version and mod version?

**Comment by Claycorp** [comment]
My bad. 
1.10.2
Forge: 2221
BWM: 0.14.7

**Comment by BeetoGuy** [comment]
Okay, I see what's going on, the sapling growth event is being greedy and looking for any instance of BlockSapling, rather than just looking for the vanilla sapling block.
