### ISSUE TITLE
 beta 0.6 crashes dedicated Forge 1.11.2 build 2227 when right clicking a machine

### ISSUE THREAD

**Issue by kreezxil** [BeetoGuy/BetterWithMods#223]
Notes:
     was right clicking a machine in the world

crash report:
https://gist.github.com/9e9c756e990a85a5bcb9e303d34904e0

fml server latest:
https://gist.github.com/532c015265b667c3e762cbdc6853c103

**Comment by kreezxil** [comment]
Issue:  beta 0.6 crashes dedicated Forge 1.11.2 build 2227 on connect

Notes:
     technically the same crash report, except after it occurs, the player who causes the first crash, crashes the server when they try to connect

crash report:
https://gist.github.com/648d8965afe9f8e78e552c349c5ac88c

fml server latest:
https://gist.github.com/8bf8bf4b53308468d1ca4d49a6ef25f5

**Comment by BeetoGuy** [comment]
Looks like the method for armor lookup is clientside only for some reason. Looks like a quick enough fix.

**Comment by kreezxil** [comment]
thanks
