### ISSUE TITLE
Axe plank crafting recipe issues.

### ISSUE THREAD

**Issue by Claycorp** [BeetoGuy/BetterWithMods#225]
Techreborn logs http://i.imgur.com/10rYDOG.png These can be sawn
Teraqueous also has the same problem with its fruit trees but also is jumbled up on what plank comes from what tree http://i.imgur.com/JlXtKMC.png These can't be sawn. I feel like it has something to do with the metadata on the logs for these.

I have removed the default log-plank recipe http://i.imgur.com/ZkhlZAG.png and the recipe does not work still.

**Comment by BeetoGuy** [comment]
I've tried a couple things on my end, but not much luck fixing it for either mod.

**Comment by Claycorp** [comment]
Yeah kinda expected that. Would it be possible to add a minetweaker option to define new axe recipes and then I can remove the auto generated ones and the log-plank recipe from the other mod then add my recipe manually?

**Comment by BeetoGuy** [comment]
You can disable "Hardcore Lumberjack" in the configs and do the recipes through a script. I might have to look into a MineTweaker option to make axe recipes easier for people.

**Comment by Claycorp** [comment]
Ehhggg ive done the axe thing before via script and it sucks. Also I can't drop the sawdust or bark when doing it via crafting.
I think people would appreciate the script option much more.

**Comment by BeetoGuy** [comment]
Alright, I've got it set up. I'll update the MT Wiki page, then upload an update in a bit.
