### ISSUE TITLE
Waterwheel on source blocks ignores obstruction checks and always powers.

### ISSUE THREAD

**Issue by Claycorp** [BeetoGuy/BetterWithMods#226]
The tooltip tells you that you need a 5x5 area to place a wheel but doesn't stick to that rule once placed if the water is 3 source blocks. Also if all the water is a source block the wheel will not rotate and still provide power, ignoring any obstructions that are in it.
http://i.imgur.com/YvJLzqc.png 
http://i.imgur.com/gNVbQgM.png

A wheel with flowing water acts as it should. Stopping when obstructed and rotates the proper direction.

**Comment by BeetoGuy** [comment]
Can't seem to replicate it on my end. How do you go about doing it?

**Comment by Claycorp** [comment]
Place a axle above source water and put the wheel on it. Once the wheel is on it the axles should be powered and you should be able to build inside the wheel without it stopping.
