### ISSUE TITLE
[1.10.2] SteelAnvil CraftTweaker format

### ISSUE THREAD

**Issue by Kiyaku** [BeetoGuy/BetterWithMods#228]
Heya,

i'm trying to add some recipes to the anvil but run into this error when loading up the script: 
`
net.minecraft.item.ItemStack cannot be cast to java.lang.Character
`

The script i'm using is following:
```
val steelPlate = <immersiveengineering:metal:38> as IIngredient;
val blastBrick = <immersiveengineering:stoneDecoration:1> as IIngredient;
SteelAnvil.add(<immersiveengineering:stoneDecoration:2>, [[steelPlate, steelPlate, steelPlate, null], [steelPlate, blastBrick, steelPlate, null], [steelPlate, steelPlate, steelPlate, null], [null, null, null, null]]);
```

I know @primetoxinz mentioned in the past that the anvil recipe wasn't working properly. I looked at the source code the other day and it seemed like it's suppose to work now? 

Is my format incorrect? (The wiki still shows the old version when it used addShaped/addShapeless). 

Thanks,
SC

**Comment by BeetoGuy** [comment]
It might be an issue on our side, I'll try to get it figured out.

**Comment by BeetoGuy** [comment]
As a side note, I don't think those null values will be needed in the script.

**Comment by Kiyaku** [comment]
Thanks! Will try it without the null as well with the new version.
