### ISSUE TITLE
[Question] Private access

### ISSUE THREAD

**Issue by sscards55** [BeetoGuy/BetterWithMods#230]
I only consider myself a beginner in java so feel free to correct me.

I was wondering if it wouldn't be better to simply change some of the fields you access in minecraft's classes to public or protected instead of using reflections. From what I understand Forge allows you to change the access level of fields as long as they aren't final. That might reduce some of the overhead from reflection usage.

**Comment by primetoxinz** [comment]
It's a coin flip between access transforming and reflection,The overhead for reflection is minimal at best for most uses in the mod and is not much better than AT. Most developers frown upon AT, yet it does work better in certain situations. So it isn't particularly important either way

**Comment by BeetoGuy** [comment]
Yeah, I think it's more or less a question of whether or not you access it often enough that it would be easier to go through adding it to an AT.

**Comment by sscards55** [comment]
My biggest concern with this was the EntityItemBouy considering you change pretty much every EntityItem into it. Since its is called every tick I believe that changing some of it will actually have and impact on some mid to extreme size modpacks, but not so much on smaller ones.

**Comment by primetoxinz** [comment]
I agreed with EntityItemBuoy, just addressed it in 1.11 [here](https://github.com/BeetoGuy/BetterWithMods/commit/c18b5c3dacf6048c0bf3ec428f1ee5dc0a466247), Will I need to back port it?

**Comment by BeetoGuy** [comment]
Yeah, might as well backport, it might be a while for other mods to catch up to 1.11.
