### ISSUE TITLE
Crafttweaker documentation

### ISSUE THREAD

**Issue by WolfieWaffle** [BeetoGuy/BetterWithMods#231]
I've heard this mod supports Minetweaker/Crafttweaker, if this is true, where can I find some documentation on how to use it?

**Comment by primetoxinz** [comment]
[Here](https://github.com/BeetoGuy/BetterWithMods/wiki/MineTweaker). This may be slightly out of date, if certain things don't work let me know and I'll update it

**Comment by WolfieWaffle** [comment]
Thank you, I'll tell you if something doesn't work.

**Comment by enzyme-a113-2** [comment]
I'm also having issues - all commands / examples on that page give out an error when using the latest BWM and Crafttweaker (they work fine with older versions, though). Might be worth looking into.

**Comment by BeetoGuy** [comment]
Do you have MTLib? The later versions use that for CraftTweaker.

**Comment by enzyme-a113-2** [comment]
I downloaded it and it works now. Thanks a lot.
