### ISSUE TITLE
Pickaxe digs too quickly

### ISSUE THREAD

**Issue by DeGariless** [BeetoGuy/BetterWithMods#232]
When I use a pickaxe on sand/dirt/gravel, it digs at a speed that is about the same as I would expect a shovel to dig. I would expect it to dig at the same speed as my hand.

Extra Info:
Playing on a server
Better With Mods-0.14.8-1.10.2

Config
    B:"Disable Brewing Stand and Enchanting Table Recipes"=true
    B:"Early pickaxes rebalance"=false
    B:"Hardcore Hardness"=false
    B:"Inferior Dirt Drops"=true
    B:"Remove cheapest tools"=false

**Comment by MRebhan** [comment]
Yeah, that is definitely happening to me too. Didn't think this mod did it though :P

**Comment by primetoxinz** [comment]
Fixed in latest release
