### ISSUE TITLE
World-ending lag with overflowing filtered hoppers

### ISSUE THREAD

**Issue by arfink** [BeetoGuy/BetterWithMods#233]
Using version 0.13.1 hotfix beta, have not yet tested if higher versions have this issue.

To replicate, place an unpowered filtered hopper, with no filter, facing into a chest below it. Deposit large amounts of non-stackable items like armor on top until it's full, then keep going. The items will make the "pop" sound and try to go inside, even though there is no room, and then re-render on top. I found that even with only a dozen or so pieces of armor, I could slow my game and everyone else's in render distance to one frame every 30 seconds or so. The items are popping into and out of existence so fast, you cannot use the /kill @e[type=Item] on them to relieve the lag. I had to edit the map to remove the hopper and resume play.

**Comment by BeetoGuy** [comment]
Might be the fact that the sound keeps playing. I had a feeling that would end up causing problems.

**Comment by BeetoGuy** [comment]
I'll upload a new build with the potential fix tonight, will be out of town tomorrow.

**Comment by arfink** [comment]
Just wanted to say that a good workaround for players stuck on old versions in modpacks (cough proton) is to make sure that there is water flowing over the hopper to carry away items that cannot enter and dispose of them elsewhere. With this I found I wouldn't have any lag issues.
