### ISSUE TITLE
Mechanical Rails

### ISSUE THREAD

**Issue by WolfieWaffle** [BeetoGuy/BetterWithMods#234]
I'd like to be able to make mechanical rails move in both directions, right now it looks like they only push in one direction. If I'm just doing this wrong, how do I change the direction? And if not, could this be added as a feature?

**Comment by BeetoGuy** [comment]
In order to do bi-directional boosting, mechanical power needs to be supplied from a downwards-facing gearbox. Otherwise, the rail will only propel carts in a clockwise direction from the input.

**Comment by WolfieWaffle** [comment]
ahhh, thank you.
