### ISSUE TITLE
[Forge 2230] [Better With Mods-1.0-RC4-1.11.2] Cannot craft Cut Leather (Tanned)

### ISSUE THREAD

**Issue by shortybsd** [BeetoGuy/BetterWithMods#235]
MC 1.11.2
Forge 2230
Better With Mods-1.0-RC4-1.11.2

Cannot craft Cut Leather (Tanned) I've tried both the shears and the knife, neither works. In the config I pretty much disabled everything that wasn't particular for the mod itself to function. E.g. Hardcore Beds, tools and e.t.c. I've also tried using the recipe in a Super Crafting Frame (as it will fix any broken or conflicting recipe) still no luck.
http://imgur.com/WlxgUNf

**Comment by BeetoGuy** [comment]
Kind of wishing this was caught earlier, there was some crashy stuff happening behind the part causing the error.

**Comment by shortybsd** [comment]
I was going to submit a lot earlier than I did, a lot of mods were out of date so didn't know if they were causing it til after I updated. Thank you very much for updating the code. Do you know when an updated build will be pushed to CurseForge?

**Comment by BeetoGuy** [comment]
I'm going to add a few fixes from the 1.10.2 branch, and probably update both today.

**Comment by shortybsd** [comment]
Thank you once again! We are dying to make the Sawmill so we can then make the Windmill / Watermill.
