### ISSUE TITLE
[Not sure if bug] Planter crop placement

### ISSUE THREAD

**Issue by RainbowSaber** [BeetoGuy/BetterWithMods#240]
Planters allow you to place crops in them, even if they are filled with unsuitable materials or are completely empty.

**Comment by BeetoGuy** [comment]
Yeah, that's totally a bug, looks like some naming confusion was causing it.

**Comment by drakray** [comment]
this is marked as closed, but in Better With Mods-1.0.5-1.11.2-hotfix1, anything can be placed over "filled" planter, no matter what is inside(sapling over water for example)
