### ISSUE TITLE
CraftTweaker support not working in 0.14.11-hotfix1 (1.10.2)

### ISSUE THREAD

**Issue by zcorcoran** [BeetoGuy/BetterWithMods#241]
In Better With Mods-0.14.11-1.10.2-hotfix1, CraftTweaker support doesn't seem to be working. Scripts that worked in previous versions result in the error "No such member: betterwithmods". MTLib 1.0.1 is installed, Using CraftTweaker-1.10.2-3.0.20 (3.0.21 won't let the game load, but I did try it).

**Comment by BeetoGuy** [comment]
Yeah, that's definitely weird, since the only thing that changed in the hotfix was re-adding an event for the sake of compatibility.

**Comment by BeetoGuy** [comment]
I have no idea what was going wrong, but it looks like a version rollback fixed it. I'll upload the update to CurseForge in a bit.
