### ISSUE TITLE
[Crash/Client] Lookin at Knife usage

### ISSUE THREAD

**Issue by drakray** [BeetoGuy/BetterWithMods#243]
http://pastebin.com/QDJWqKin
crashed when logged in dedicated server

MC 1.11.2
Forge 2233
Quark 81
Better with mods 1.0.0
And others

**Comment by primetoxinz** [comment]
Cannot reproduce, put an attempt fix either way though.

**Comment by drakray** [comment]
it only crash when on a dedicated server with Quark and my other mods, will try only Quark and BWM, see if it comes from another mod

**Comment by primetoxinz** [comment]
right, will attempt with a server

**Comment by primetoxinz** [comment]
yeah, still can't reproduce with those two mods, if you can find more let me know
