### ISSUE TITLE
Improved Steel Anvil CraftTweaker Integration

### ISSUE THREAD

**Issue by WesCook** [BeetoGuy/BetterWithMods#244]
Right now the steel anvil is rather difficult to work with as a modpack author.  It seems to have problems when adding multiple input items, and it doesn't recognize `null`, which would allow for custom shapes.

For instance, take a very simple recipe:
`mods.betterwithmods.SteelAnvil.add(<minecraft:stick>, [[<ore:ingotIron>, <ore:ingotGold>]]);`

It should take an iron and gold ingot.  Yet the outcome is actually just one iron ingot:

![stick](https://cloud.githubusercontent.com/assets/792101/23342951/3168eefc-fc18-11e6-8c65-b87f42a3d7f2.png)

Switching the iron/gold around will make it require only one gold instead.  So it seems to be discarding additional items.

The function name also appears to have changed to `mods.betterwithmods.SteelAnvil.add`, which if I remember correctly was originally `addShaped()`.  At least, that's what I recorded when I originally tested the anvil.

Anvil recipes use the wrapping braces `[[group1], [group2]]` implying it is a shaped recipe.  As it's shaped I would expect `null` to work as well, but it throws an error when used.

Code: `mods.betterwithmods.SteelAnvil.add(<minecraft:stick>, [[null, <ore:ingotIron>], [<ore:ingotGold>, null]]);`
Error: `Invalid shaped ore recipe: [Ljava.lang.String;@48aa6123, A, ingotIron, B, ingotGold, E, null, F, null, 1xitem.stick@0`

I feel the anvil could use a little love.

This was testing in `0.14.11-1.10.2-hotfix2`.

**Comment by primetoxinz** [comment]
I will look into it, the code for anvil is a huge mess anyways

**Comment by primetoxinz** [comment]
I have completely rewritten anvil recipes, they work properly now. Once it releases the new minetweaker info is updated on the [wiki](https://github.com/BeetoGuy/BetterWithMods/wiki/MineTweaker).

**Comment by WesCook** [comment]
You're amazing prime.  Thanks so much.

I'm looking forward to using it for some proper "smithing" recipes.

**Comment by primetoxinz** [comment]
This is in the latest version, open a new issue if there are any with it.

**Comment by WesCook** [comment]
I just tested it and the recipes work great now.  :)

**Comment by primetoxinz** [comment]
Awesome!
