### ISSUE TITLE
Axes are not effective on wood siding

### ISSUE THREAD

**Issue by DeGariless** [BeetoGuy/BetterWithMods#245]
it takes soo long to break wood siding when you use it to build. I'd imagine the same issue exists for stone siding. This issue is also probably closely related to https://github.com/BeetoGuy/BetterWithMods/issues/232

Extra Info:
Playing on a server
Better With Mods-0.14.8-1.10.2

Config
B:"Disable Brewing Stand and Enchanting Table Recipes"=true
B:"Early pickaxes rebalance"=false
B:"Hardcore Hardness"=false
B:"Inferior Dirt Drops"=true
B:"Remove cheapest tools"=false

**Comment by primetoxinz** [comment]
Fixed in latest release
