### ISSUE TITLE
Botanist hour glass and bellows

### ISSUE THREAD

**Issue by wizard1399** [BeetoGuy/BetterWithMods#246]
The bellows doesn't respond to Redstone pulses from the Botanist hourglass. I think this is probably because the bellows is looking for a 2 ticks pulses and the hourglass only emits a 1 ticks pulses.

**Comment by DaedalusGame** [comment]
uh i'm pretty sure bellows only respond to mechanical power

**Comment by wizard1399** [comment]
Axle directly into bellows?

**Comment by DaedalusGame** [comment]
Yes.
