### ISSUE TITLE
NPE 1.0.1-1.11.2

### ISSUE THREAD

**Issue by sdaddy** [BeetoGuy/BetterWithMods#249]
Crash report: http://pastebin.com/raw/nTtiZsub

I tried using the previous 1.0.0 version and disabling foamfix but still got the same crash. I wanted to see if this was a problem with BWM before going through disabling/enabling each mod at a time. Thanks.

**Comment by sdaddy** [comment]
I disabled the [Armor Extended mod](https://minecraft.curseforge.com/projects/armor-extended) and no more crash. If you could let me know if I should report this to that mod author or if it's still a bug on BWM's end it would be much appreciated.

**Comment by BeetoGuy** [comment]
It might have been on our end, it's pointing to a recipe that was still using the old iron nugget lookup method instead of just using the vanilla nuggets for an output.
