### ISSUE TITLE
[1.11.2] Debarked wood isn't consumed when crafting planks.

### ISSUE THREAD

**Issue by MrNinja93** [BeetoGuy/BetterWithMods#250]
All variants of debarked wood are not being consumed when crafting with an axe. Planks can be infinitely crafted from the single debarked wood block.

Happens with just Forge/Better With Mods

Forge: 13.20.0.2252
Better With Mods: 1.0.1-1.11.2

**Comment by BeetoGuy** [comment]
I think it's because the recipe handler was still getting a null ItemStack passed through for bark. I'll try to replicate, then see if the fix works.
