### ISSUE TITLE
[1.11.2][1.0.2]axe + log recipe OR wrong tool on log, still outputing increased bark and sawdust

### ISSUE THREAD

**Issue by Rosethorns** [BeetoGuy/BetterWithMods#251]
Bark produced by either the log+axe crafting table recipe or by punching trees appears to be increasing its bark and sawdust output per operation up to the point of a stack of each.

reproduce.
1. punch a log (output 1 bark 2 sawdust)
2. punch a log (output 2 bark 4 sawdust)
3. punch a log (output 4 bark 8 sawdust)

This issue is server wide and each operation of the craft by anyone, be it by axe in table or by wrong tool on log, will increase the output

**Comment by BeetoGuy** [comment]
Can't seem to replicate on client or server. What's your server running?

**Comment by Rosethorns** [comment]
Server is running on 13.20.0.2252.

Others on the server have had more luck shift clicking the axe recipe to reproduce it.

**Comment by BeetoGuy** [comment]
Still having trouble replicating, I'm not entirely sure if it's on our end.

**Comment by Rosethorns** [comment]
One of my players said it seems to be related to the config file since a default file did not produce these issues in SSP

So here is ours.

http://pastebin.com/1zWDQ3Zh

**Comment by BeetoGuy** [comment]
Okay, that definitely helped with replication. I'll have to re-enable options until I find the one that's the issue.

**Comment by BeetoGuy** [comment]
Looks like Hardcore Buoy being disabled was the culprit, combined with the chopping recipe handler directly passing on the bark and sawdust ItemStacks. This will definitely have to get fixed on both 1.10 and 1.11.

**Comment by BeetoGuy** [comment]
Fixes for both versions are now uploaded to CurseForge.
