### ISSUE TITLE
[1.11.2] Mill's no longer work, previously did. 

### ISSUE THREAD

**Issue by MrNinja93** [BeetoGuy/BetterWithMods#252]
No idea how but the most recent update seems to have broken mill's, they don't work with hand crank or creative mechanical generator/axles when they did previously. (fairly sure It's set-up right)

![mill-set-up](https://cloud.githubusercontent.com/assets/21979276/23649787/9297974a-0317-11e7-9a44-c277a6be4e1f.png)

Progress bar stays stationary block makes noise as if it's working but hemp/wheat etc. stays unprocessed.

Forge: 13.20.0.2252
BWM: 1.0.3-1.11.2

**Comment by BeetoGuy** [comment]
Yeah, that's our fault. Some internal changes prevented the mill from detecting if it had a proper recipe.
