### ISSUE TITLE
Crush with version 0.14.13-1.10.2

### ISSUE THREAD

**Issue by Bulldog83** [BeetoGuy/BetterWithMods#253]
Crush log: https://gist.github.com/Bulldog83/6fb0b16b132765779a0df6578c52eaa5

**Comment by MRebhan** [comment]
Don't use the dev version, it's deobfuscated and will not work in a normal minecraft instance.

**Comment by BeetoGuy** [comment]
Yeah, the dev version's there so people can use it for addon or compatibility development, not regular gameplay.
