### ISSUE TITLE
Turntable switch doesn't operate with item in off-hand

### ISSUE THREAD

**Issue by Vmaximum** [BeetoGuy/BetterWithMods#258]
BetterWithMods/src/main/java/betterwithmods/blocks/tile/TileEntityTurntable.java line 96 prevents the user from operating the turntable switch while holding something in the off-hand.

**Comment by primetoxinz** [comment]
IMO that is a feature not a bug

**Comment by Vmaximum** [comment]
Sure looks like a bug when the hand you hit it with is clearly empty and the switch doesn't operate.  I thought the block was broken till i examined the code and saw that it wanted BOTH hands to be empty.  The BTW wiki even states *with an empty hand*.. not "with empty hands".  To be fair i also found that you can't change the face of EnderIO Capacitors with something in the off-hand, so it's not just this mod that doesn't recognize an empty main hand.
