### ISSUE TITLE
[1.11.2] Axe recipe not working for non vanilla wood

### ISSUE THREAD

**Issue by Rosethorns** [BeetoGuy/BetterWithMods#259]
Description:
While BWM seems to assign an axe recipe to all plankWood types it can find, It doesn't appear to be working.

Recreate:
1. In this example larch wood from forestry shows that it has a axe recipe
http://i.imgur.com/y3kDmPJ.png
In this case the log in the picture is cycling through the first 3 meta of forestry:logs.0

2. attempt to use the axe with the larch log produces no output (no ghost output either)
http://i.imgur.com/Apacvo4.png
Note: In this case the BWM Saw produces the correct results.

Another Example:
1. In this case banana wood from Terraqueous, the recipe shows an output of Mango wood (incorrect)
http://i.imgur.com/OyieL95.png

2. And again, no output
http://i.imgur.com/ht7alVo.png

Note: in this case the saw would not cut the banana wood
http://i.imgur.com/by7QcvZ.png

Versions:
Minecraft: 1.11.2
Forge: 13.20.0.2252
BWM: 1.0.5

**Comment by BeetoGuy** [comment]
Yeah, this was an issue in 1.10.2, as well, at least with Terraqueous. Still at a loss of why the saw wouldn't cut the Terraqueous wood.
