### ISSUE TITLE
Too much "Too Exausted"

### ISSUE THREAD

**Issue by DeGariless** [BeetoGuy/BetterWithMods#261]
MC 1.10.2
When I'm "Too exhausted to turn it" it tells me twice in the chat.

Also, It would be great to see these kinds of messages show up as toast notifications instead of just showing up in the chat.

**Comment by BeetoGuy** [comment]
No idea why it would tell you twice when it only sends clientside. Regardless, I'm going to see if changing it to a status message will help.

**Comment by DaedalusGame** [comment]
Both hands might trigger it?

**Comment by BeetoGuy** [comment]
Yeah, that might be it.
