### ISSUE TITLE
Worldgen crashes with BoP and RTG

### ISSUE THREAD

**Issue by lookbehindyoo** [BeetoGuy/BetterWithMods#262]
Forgive me if this is crash is not the fault of Better with Mods! Attached is a crash report which makes mention of the addStumpsToGeneratedTrees event. I think the root of the issue is actually to do with Biomes o Plenty, but I thought I would post here just in case. Whilst exploring new terrain, the server simply crashes. 

[crash-2017-03-13_23.18.47-server.txt](https://github.com/BeetoGuy/BetterWithMods/files/839882/crash-2017-03-13_23.18.47-server.txt)

As an aside, does anyone know how to make better with mods fertiliser? I see it in JEI, but there are no recipes for the block or fluid!

Cheers!

**Comment by BeetoGuy** [comment]
Seems like it would be a bit odd if the crash was done on our end. That particular line should only be accessed if it's a vanilla log block on top of vanilla dirt blocks. I want to say it looks like something related to Biomes o Plenty. Regardless, maybe disable Hardcore Stumping and see if that helps?

As for fertilizer, it's a special recipe in the cauldron, where you put dung in along with any type of food.

**Comment by lookbehindyoo** [comment]
Thanks for the response. Tried without hardcore stumping and the problem persists, so I suppose this is unlikely to be a problem on your end. Thanks for looking, and cheers for the excellent mod :)
