### ISSUE TITLE
axe+log=8 planks and it shouldnt

### ISSUE THREAD

**Issue by MichinYeoja** [BeetoGuy/BetterWithMods#263]
HI I was wondering about something and I'm not entirely sure if its an issue with your mod better with mods. Do you know of anyone else using your axes and wood log recipe? If so another one makes too many planks and if not its bugging out and added 2 recipes for an  axe and wood log to either turn into 2 planks or 8. My pack needs there to be just one recipe and for it to the making less planks lol. thank you for your time im using 1.10.2 minecraft

**Comment by BeetoGuy** [comment]
If it's a second recipe, it probably isn't BWM adding it. I think I've seen someone else bring this up elsewhere, what modpack are you running?

**Comment by MichinYeoja** [comment]
its a custom pack MSA on curse, as soon as I disable hardcore lumberjack it goes away

**Comment by MRebhan** [comment]
Modlist?

**Comment by MichinYeoja** [comment]
https://minecraft.curseforge.com/projects/magic-survival-adventure/relations/dependencies I cant find an easier way to give you a list

**Comment by BeetoGuy** [comment]
Really seems like it's another mod doing it to me. I initially thought it was a MineTweaker script, but it doesn't look like the pack actually has any.

**Comment by MichinYeoja** [comment]
thank you ill do the whole disable one at a time thing again and get back to you with my results, love the mod btw
