### ISSUE TITLE
More specific recipe removal

### ISSUE THREAD

**Issue by DeGariless** [BeetoGuy/BetterWithMods#264]
I'd like to remove the ability to "recycle" rails back into ingots with the Stoked Crucible. Curretly, it seems like my only option is to remove all recipes that make iron, and then add them all back in just for that 1 item.
Please either add more specific recipe removal, or a way to overwrite the recipe with StokedCrucible.add(<foo:bar>, null, [<minecraft:rail>]);

The reason why this is a problem, is that other mods (like railcraft) are adding way to make track more efficiently, or with different material or items. I cant have a way to make infinite iron.

**Comment by DeGariless** [comment]
Also, Thanks so much for this mod. You all do an awesome job of fixing things quickly and answering requests. :)

**Comment by DeGariless** [comment]
https://github.com/elytra/Unabridged/issues/591

**Comment by BeetoGuy** [comment]
Yeah, I figured that would have ended up being an issue down the line. Just need to refine the solution, and the new version will have it possible for the cauldron, crucible, and mill under remove(output, [input]);.

**Comment by DeGariless** [comment]
Any way youd be willing to add a config to just remove that one recipe ... just for the time being?

**Comment by DeGariless** [comment]
or an `if(railcraft) {tracks smelt to <railcraft:rail>} else {tracks smelt to <minecraft:iron_ingotl>}`

**Comment by BeetoGuy** [comment]
It's pretty much all implemented on the MineTweaker part, just need to commit it and upload the update.

**Comment by DeGariless** [comment]
oh it's done already? great. I'll just wait patiently then, Thanks :)

**Comment by WesCook** [comment]
Well that allowed me to shave about 50 lines from my CraftTweaker file.  Fantastic!

![zs](https://cloud.githubusercontent.com/assets/792101/23946053/18e03536-0936-11e7-9826-8c5a0406c12a.png)

**Comment by DeGariless** [comment]
@WesCook knows what's up.
