### ISSUE TITLE
Creative Bellows

### ISSUE THREAD

**Issue by DeGariless** [BeetoGuy/BetterWithMods#265]
A creative Bellows might be nice, Certainly not a necessary item, but it would make setting up a stoked crucible much easier.

**Comment by WesCook** [comment]
I have to admit, setting up a redstone clock for bellows use is my least favorite part about the current BWM tech tree.  I'd love this just for testing, but heavily customized packs could use it as an upgraded item as well.

**Comment by primetoxinz** [comment]
I like the idea of an advanced bellows that can maintain itself

**Comment by primetoxinz** [comment]
Take a look at [this](https://streamable.com/eixyx)

**Comment by BeetoGuy** [comment]
I like the idea of springs and a steel gear for the recipe, but I more imagine the crafting recipe being a standard bellows in the middle, with a clock on top, springs on the sides, and the gear on the bottom. Seems like a better representation of a "timed bellows" to me.

**Comment by DeGariless** [comment]
For me, BTW/BWM is about having to set things up rather than just plop down a "magic machine".  Somethink like advanced axles or gearboxes that let you span 5 blocks instead of 3 sound nice. But a block that says "you don't have to worry about all that redstone stuff" block doesn't feel right to me. But that's just my opinion, man.

**Comment by BeetoGuy** [comment]
We could always have the recipe configured out, but my opinion on this is that it would make sense to have it gated behind the steel anvil, since it would take a while to craft all the soulforged steel necessary to actually make the upgrade.

**Comment by DeGariless** [comment]
I'm aware that it can be confused out, I just felt like expressing my opinion.
