### ISSUE TITLE
BWM has a World Leak

### ISSUE THREAD

**Issue by abculatter2** [BeetoGuy/BetterWithMods#266]
I don't really know what more to say, other then that I have isolated the leak from my modpack to only BWM and reproduced it on its own without any other mods installed.  I'm also using forge version 13.20.0.2259 at the moment, though I also noticed it with 13.20.0.2228

**Comment by abculatter2** [comment]
I just found out that disabling Hardcore Redstone causes the leak to go away., and it comes back when it's re-enabled. So something in there is causing the leak.

**Comment by BeetoGuy** [comment]
I think Hardcore Redstone's block notification changes need to be revisited, if that's the case. For now, I suppose it would be best to disable it.

**Comment by BeetoGuy** [comment]
I might have it figured out, but it's a big "might," since I wasn't able to actually replicate the message.
