### ISSUE TITLE
add a oredict input to the axe cutting crafttweaker handler

### ISSUE THREAD

**Issue by megaloloful** [BeetoGuy/BetterWithMods#267]
I want to add a chopping recipe which turns planks into sticks but I get an error when I try to use <ore:plankWood> as an input for the handler

**Comment by primetoxinz** [comment]
What version?

**Comment by BeetoGuy** [comment]
Well, the chopping recipe only looks for an ItemStack as the log input, so the CraftTweaker recipe reflects that.

**Comment by primetoxinz** [comment]
can always allow it to support oredictionary

**Comment by BeetoGuy** [comment]
Will probably need to be redone a bit, but yeah, might as well.
