### ISSUE TITLE
Bizarre behavior between the millstone and hand crank MC1.11.2 1.0.8

### ISSUE THREAD

**Issue by Jleepevner** [BeetoGuy/BetterWithMods#270]
Running forge 13.20.0.2228. No other mods.

When the hand crank is right clicked on top of a filled millstone, the millstone will not begin grinding for up to a few minutes. The GUI is still accessible, but the cog does not fill up, and no particles, item drops, or sounds occur.

The millstone may spontaneously decide to start "catching up", and will begin grinding for a while, without any input.

**Comment by BeetoGuy** [comment]
Replicated on that version, looks like it's been fixed after the commit to address #266
