### ISSUE TITLE
Disabling hardcore hardness doesn't update the stone pickaxe durability 

### ISSUE THREAD

**Issue by megaloloful** [BeetoGuy/BetterWithMods#271]
So I turned off hardcore hardness in my pack and the stone pick durability is still 5. Even if I enable hardcore hardness and change the stone pick value it stays on 5

**Comment by BeetoGuy** [comment]
Try disabling "Early Pickaxes Rebalance." It's a completely separate config option then Hardcore Hardness.

**Comment by megaloloful** [comment]
Oh. Right. But still, it looks like you can't currently change the stone pick durability with the  "hardcore hardness stone durability" config
