### ISSUE TITLE
Multiplayer server + powered turntable + clay = crash

### ISSUE THREAD

**Issue by Jleepevner** [BeetoGuy/BetterWithMods#273]
Better With Mods-1.0.8-1.11.2.jar
Server + client: forge-1.11.2-13.20.0.2250-universal.jar

Default configs except for hardcore redstone = false.

Attempting to shape a clay block in multiplayer with a powered turntable results in a server crash.
Singleplayer games do not replicate the behavior.

**Comment by BeetoGuy** [comment]
Replicated, looks like it's trying to access something that's clientside only for some reason.
