### ISSUE TITLE
lntentional? Hardcore Hunger and sandwiches'/ingredients' food values

### ISSUE THREAD

**Issue by Jleepevner** [BeetoGuy/BetterWithMods#276]
Better With Mods-1.0.8-1.11.2.jar
Client: forge-1.11.2-13.20.0.2250-universal.jar

Default configs except for hardcore redstone = false.

Hardcore Hunger = true
Eating two sandwiches restores just about the exact same hunger (~2 shanks), as eating 1 bread and 1 steak. There's no benefit, so far as I can tell, to making the item. The only benefit I can see is maybe consolidating inventory space, but it's still pretty much 1:1.

I haven't tested any of the other items, but I'm hearing similar things about other complex foodstuffs. Intended?

Since it's topical, adding in separate toggles for some of hardcore hunger's features would be appreciated. I'm down with hunger changes, but waiting 30 seconds for half a heart is pretty punishing. Ditto with the fat feature.

**Comment by primetoxinz** [comment]
The values for the foods in code are as follows currently: 
Steak: 8 food
Bread: 5 food
Sandwich : 6 food * 2 per craft = 12 food

I see the point and have increased sandwiches to 7 per giving them slight benefit. 

If you find other foods that are inconsistent open a new issue
