### ISSUE TITLE
Hemp shown as Wood Gear in Waila tooltip

### ISSUE THREAD

**Issue by mankra** [BeetoGuy/BetterWithMods#277]
Better With Mods: 0.14.17
[Hwyla](https://minecraft.curseforge.com/projects/hwyla): 1.8.11-B25

It's only the case when the Hemp is not grown mature.

![2017-03-19_10 56 07](https://cloud.githubusercontent.com/assets/22047030/24079870/f18ee68e-0c92-11e7-8d34-552fcd4d609d.jpg)

**Comment by BeetoGuy** [comment]
I think I know what's causing it, but the solution might involve making an addon to support it.

**Comment by primetoxinz** [comment]
Appears to be fixed with Hwyla B26
