### ISSUE TITLE
[1.11.2 - v.1.0.8] attempt to use turntable causes Server Crash in SMP

### ISSUE THREAD

**Issue by GeekBeam** [BeetoGuy/BetterWithMods#279]
Setup for the bug: place down Turnable atop an already turning axle, place Clay block on top of that.

seeing as I do not have access to the logs in the backend of the server, I have attempted to replicate the bug in a SinglePlayer environment, to no result, so this bug seems to be specific to MP servers only.

will elaborate on this issue once I have more information.

**Comment by primetoxinz** [comment]
believe this is fixed in (v1.10)[https://minecraft.curseforge.com/projects/better-with-mods/files/2394835]

**Comment by BeetoGuy** [comment]
Yeah, can confirm that it's fixed.
