### ISSUE TITLE
Knife on Planks [Bug Report]

### ISSUE THREAD

**Issue by zlainsama** [BeetoGuy/BetterWithMods#28]
I made a iron knife, tried to use on oak planks, and it made the plank into the Oak Debarked Log.

Mod Version: Better With Mods-0.10-1.10.2
Modpack: Proton 1.0.5 (on Curse launcher)

**Comment by BeetoGuy** [comment]
Oh, that's an interesting one. Looks like the changes in the debarking event were getting too greedy and looked for anything the saw can cut, instead of being limited to logs. It's been fixed, I'll probably push an update soon.
