### ISSUE TITLE
[1.11.2] Pully/Elevator Elevator stopping randomly on the way UP

### ISSUE THREAD

**Issue by Rosethorns** [BeetoGuy/BetterWithMods#281]
Description:
It appears on an elevators ascent it will sometimes stop at random spots the elevator will go back down from that point fine but will not come up past the point that it stopped.

The only way to bring it up is to brake the entire rope chain (anyway is fine) and to drop the rope back down via the pully to the elevator and then bring it back up. Even then it may infact get stuck again and you have to repeat the entire process again.

Repeat:
1. set up fairly large elevator.
2. send it to the bottom
3. raise the elevator
4. should arbitrarily get stuck

Versions:
Minecraft: 1.11.2
Forge: 13.20.0.2252
Better With Mods: 1.1.0

**Comment by BeetoGuy** [comment]
How large of an elevator would be needed to replicate it?

**Comment by Rosethorns** [comment]
The one in question was down to about Y 7 from about 110

**Comment by BeetoGuy** [comment]
Does it ever come adjacent to a solid block, like obsidian? That seems to be the constant I'm seeing in the bug replication.
