### ISSUE TITLE
[1.11.2 - 1.1.0] Bellows puts out fires instead of stoking them

### ISSUE THREAD

**Issue by GeekBeam** [BeetoGuy/BetterWithMods#282]
I'm not sure exactly why this is, but this doesn't seem like it's supposed to be happening. is a hibachi needed to keep the fire going?

**Comment by BeetoGuy** [comment]
Yeah, a hibachi is required.

**Comment by GeekBeam** [comment]
if that is so, then how does one attain Hellfire dust without an urn from a kiln, which requires a hibachi to operate correctly? looping recipes.
