### ISSUE TITLE
[1.11.2] BWM+JEI attempting to enter cheat mode refuses/gives player 64 nether stars.

### ISSUE THREAD

**Issue by MrNinja93** [BeetoGuy/BetterWithMods#285]
This is one of the most random bugs I've ever come across, as soon as JEI and BWM are in an instance together attempting to enter cheat mode in JEI will fail unless the player is in creative mode. Stranger still is the fact that on receiving the "You don't have permission" message the player is given a stack of nether stars every time in SP

This happens regardless of what Item the player is searching for or if cheats are enabled or not. SP only issue, doesn't happen on servers (at-least not without op)

I'm going to assume it's something on BWM's end as I've never seen this happen with JEI and countless other mods, pinging @mezz Just in-case though.

Forge: 13.20.0.2259
BWM: 1.1.0-1.11.2
JEI: 4.2.10.248

**Comment by BeetoGuy** [comment]
Just out of curiosity, does this happen if Hardcore Buoyancy is disabled?

**Comment by MrNinja93** [comment]
Just gave it a test and can confirm with it disabled it doesn't happen

**Comment by BeetoGuy** [comment]
Probably teething issues with the workaround for a previous issue with the /give command.

**Comment by mezz** [comment]
JEI checks the `/give` command permissions to see if you can be in cheat mode, if you are not an OP or in creative.
Ways the mods might disable this accidentally: They replace the command and the player does not have permission, or they cancel the event that is fired when the give command is executed.

**Comment by BeetoGuy** [comment]
Yeah, that's pretty much exactly what's happening.

**Comment by mezz** [comment]
Unless BWM is doing something super weird with reflection or ASM, receiving items and getting the disabled message sounds like a JEI bug. If you have steps to reproduce it, please post to the JEI issue tracker on github.

**Comment by BeetoGuy** [comment]
All we're really doing is canceling the event and passing the parameters to a different /give command so any items given don't duplicate. I'll try looking into seeing if it's more an issue with buoyant items and try to get the event out of the way.

**Comment by BeetoGuy** [comment]
Got it working as intended on this end. Shouldn't be a problem anymore, @mezz

**Comment by mezz** [comment]
Is it related to this? https://github.com/MinecraftForge/MinecraftForge/issues/2349

**Comment by BeetoGuy** [comment]
I'm pretty sure it was, yeah. Since we were grabbing the EntityItem to replace it with our own variant the moment it spawns, I guess the "fake item" values don't take hold.
