### ISSUE TITLE
Hardcore Features & Information

### ISSUE THREAD

**Issue by bookerthegeek** [BeetoGuy/BetterWithMods#286]
I am loving the mod. Loving it. And the players of my pack, it's going to get them screaming. muahahaha...

Except....

I have no idea what the Hardcore config options do. Nothing. Well, I do know that the hunger one crashes when eating food and Spice of life is also being used. And buoyancy causes my beast of a machine to act more like a potato. Most likely my fault since I spawned in about 1 of every item at the same time to see if they float or not. (Not a good idea by the way)

But the other options? No idea. I can see that the redstone one modifies some recipes, but it does not remove the old ones? Also, stumping, diamond ingots, dirt drops and steel are sorta self explanatory. Speaking of the diamond ingot, any chance to leave it in game even if the Hardcore option is turned off? would be fun with some recipies.

Really what this Issue is about is the complete lack of easily findable information about the Config options. Also about many of the blocks in game. What in the hell is a lens and how do you use it?

So my request is two fold.
1) Take a small break, say an hour or so, and type up a quick synopsis of what the config options do
2) Take a slightly longer break and document your in game items. (or have a trusted user document them for you).

If you don't want to spend the time to make it pretty, I'll be more then happy to formate and update your github Wiki with any information you care to provide. Thank you for this great looking mod, and I look forward to what comes next.

**Comment by WesCook** [comment]
I usually consult the Config class when looking up a feature.  For some reason Forge comments are really weird in config files, and often don't get included or later get wiped out.

https://github.com/BeetoGuy/BetterWithMods/blob/16d0d9adbdcc4559675c9d00a0d8a65c38b74972/src/main/java/betterwithmods/config/BWConfig.java#L80-L98

I also sometimes use the actual Better Than Wolves wiki from time to time, but it can be hard to translate feature names.

A Wiki page with an overview of each feature seems like a good suggestion.

**Comment by primetoxinz** [comment]
1.11 version will now contain actual information in the config.
