### ISSUE TITLE
Incorrect math

### ISSUE THREAD

**Issue by DeGariless** [BeetoGuy/BetterWithMods#287]
It takes (the equivalent of) 20 iron nuggets to make a chain mail helmet. You get 25 nuggets from putting a chain mail helmet in a crucible. Same for chestplate, leggings, and boots.

In a stoked crucible...
helmet should yield 20 nuggets
chestplate should yield 32 nuggets
leggings should yield 28 nuggets
boots should yield 16 nuggets

**Comment by meelock** [comment]
Bump.
