### ISSUE TITLE
[1.11.2] [Raxpack 2] Placing item in vase voids rather than storing

### ISSUE THREAD

**Issue by Ayrrow** [BeetoGuy/BetterWithMods#291]
As per title. Tried to place an item in the vase and it was voided, and not returned on breaking the vase.

**Comment by DaedalusGame** [comment]
aaaaaa everything was working when i made these why does this happen
also #256

**Comment by BeetoGuy** [comment]
Looks like an issue with harvest levels, breaks just fine with a diamond pickaxe.
