### ISSUE TITLE
[0.14.19] Hardcore Redstone bug

### ISSUE THREAD

**Issue by Erik3003** [BeetoGuy/BetterWithMods#292]
I found a bug that happens under very specific conditions: pressing a button on the back of a dispenser or block placer freezes the game (no crash). It only works with a button and only on the opposite side to the output, only when the button is placed directly on the device. I haven't tested the dropper or other redstone devices...

**Comment by BeetoGuy** [comment]
Yeah, I'm seriously considering removing the Hardcore Redstone event, it seems like there isn't a way to do it efficiently and have it still work.

**Comment by primetoxinz** [comment]
Hardcore Redstone is an extreme hack that actually was having issues with mods like MCMultipart in my testing. It's not good to override such an integral part of the game as block updates

**Comment by BeetoGuy** [comment]
Yeah, I think @Koward did that with grass and mycelium, but we had to remove it because it would crash the game outside of a deobfuscated environment.

**Comment by primetoxinz** [comment]
Right, I believe there are issues with it on forges end that everyone is avoiding. Maybe someday
