### ISSUE TITLE
Water puddles don't decay when the puddle source is picked up with a bucket

### ISSUE THREAD

**Issue by enzyme-a113-2** [BeetoGuy/BetterWithMods#294]
Like the title says, when placing water with a bucket in survival, and picking up the source of the puddle with the same bucket, the remains of the puddle don't decay fully.

On a similar note, would it be possible to change the way water puddles work? In older versions of Better than Wolves, rather than placing a water puddle block that spread out, a single flat "tile" of water was placed which decayed after half a second.

**Comment by primetoxinz** [comment]
I cannot reproduce the lack of decay in 1.11.2

I doubt we can get the old way of BTW back as water has changed and we cannot modify the game directly. So for now it will stay as is
