### ISSUE TITLE
[request] Config Options

### ISSUE THREAD

**Issue by bookerthegeek** [BeetoGuy/BetterWithMods#295]
## Heyo! ##
Hello Great Sirs or Madams!

May I request a simple config file for adding blocks to your list [HERE][1]. Thank you for taking the time to consider my humble request. This is mainly to add mod added blocks (BoP) to the config.

[1]:https://github.com/BeetoGuy/BetterWithMods/blob/0861b8375a0499dca92a9ce4ab0bd1010ab40563/src/main/java/betterwithmods/event/InferiorDropsEventHandler.java

**Comment by primetoxinz** [comment]
you can now assign an ItemStack to a Block with Minetweaker in the 1.11.2 version only.
here is an example:
`mods.betterwithmods.Piles.addPile(<minecraft:sand:1>,<betterwithmods:sand_pile>*3);`
