### ISSUE TITLE
Hardcore lumberjack breaks both mekanism and thermal expansion sawmill

### ISSUE THREAD

**Issue by Octopork** [BeetoGuy/BetterWithMods#297]
BWM version 0.14.20-1
Mek version 9.2.2.301
TE version 5.0.4.90

It seems whatever method both these sawmills are using to create recipes is broken by the method hardcore lumberjack uses to change wood crafting recipes to require an axe. 

Without hardcore lumberjack on both work fine and create 6 planks, with hardcore lumberjack on both won't accept any log as input.

Hopefully this is fixable, would be great to have the smooth progression of 2, 4, then 6 planks per log.

**Comment by BeetoGuy** [comment]
Might be something as simple as establishing load order. I'll have to check.

**Comment by BeetoGuy** [comment]
Changing the load order works for Mekanism, but it doesn't look like TE gets the recipes the same way. I'll probably have to mess with IMC for that.
