### ISSUE TITLE
[Bug]Crafttweaker Turntable Support is ineffective

### ISSUE THREAD

**Issue by Titus-Armillius** [BeetoGuy/BetterWithMods#299]
T tried the format below, changing the inputs and outputs and/or removing the extra material; it continuously gave me an error upon reload. Could you identify what's wrong?

mods.betterwithmods.Turntable.addRecipe(<input>, <output>, <extra_materials>);

mods.betterwithmods.Turntable.addRecipe(<minecraft:clay>, <cs3_1:unfired_clay_water_vessel>, <minecraft:clay_ball>);

**Comment by BeetoGuy** [comment]
The additional outputs need to be in an array, so the recipe should be Turntable.addRecipe(<minecraft:clay>, <cs3_1:unfired_clay_water_vessel>, [<minecraft:clay_ball>]);

**Comment by LordDan1989** [comment]
I've started to crawl through the source and made a few amendments to the Wiki where an array is required, but not documented. I had the same trouble with the Kiln.add(<output>, <input>); needing to be Kiln.add([<output>], <input>); 
I'll continue to amend the Wiki as I discover these, I think this can be closed for now.
