### ISSUE TITLE
Crash when filtered hopper collects item with non-empty block below

### ISSUE THREAD

**Issue by LGcommisar** [BeetoGuy/BetterWithMods#30]
Crashlog: http://pastebin.com/7AcpAk32

So... I have done it again.  Tossed a potato into a powered hopper that was set to output into a dirt block. 

Yay for breaking things.

:3c

**Comment by BeetoGuy** [comment]
Looks like it's related to the buoyancy addition. I'm currently trying to figure out why it can't find the reflection value, as the mappings for it seem correct, at least as of a few weeks ago.

**Comment by LGcommisar** [comment]
http://pastebin.com/PL8yD5PN

You mentioned the EntityItemBouy function, I just produced another crash involving it by hooking up a handcrank to a millstone and grinding a flower.  When the dye popped out... ticking entity crash.

**Comment by BeetoGuy** [comment]
Yep, that's definitely the same source of the crash. I'll see what I can do about it.

**Comment by LGcommisar** [comment]
Thanks, I'll do what I can to break it again~  

Definitely very happy you brought this up to 1.10.2 so keep up the good work!

**Comment by BeetoGuy** [comment]
Welp, looks like the problem was a naming discrepancy between the MCP mappings and what the srgname for the field actually was. Don't know why the mappings are inconsistent, but at least it's fixed. Hotfix should be up soon.
