### ISSUE TITLE
Pulley not 'pulling' rope up.

### ISSUE THREAD

**Issue by Octopork** [BeetoGuy/BetterWithMods#302]
Whenever i activate a pulley to pull(hope I'm making sense there) it deletes the anchor, platforms and last rope then proceeds to do nothing but flood my console with:
[STDERR]: [betterwithmods.util.AABBArray:func_72321_a:225]: AABBArray.addCoord() is stub
[STDERR]: [betterwithmods.util.AABBArray:func_186664_h:231]: AABBArray.contract() is stub

Even after deactivating or destroying the pulley.

**Comment by MRebhan** [comment]
Huh. I wrote that code, I never expected those methods to be called. What mods have you installed?

**Comment by Octopork** [comment]
here i was reading that error and thinking someone had made a minor derp and left some test code in or forgot to finish something off ;)  

It's ValkyrienWarfare causing the issue somehow.

**Comment by MRebhan** [comment]
Airship mod, huh? Let me check this out and try to fix it

**Comment by MRebhan** [comment]
So ValkyrienWarfare crashes if you load the jar in the dev environment and the mappings are incompatible. 
This means I can either not debug it at all or update their mappings which would take me forever and I really don't want to do that. 
The thing is, there is no good way to implement these methods, they already return a reasonable value and without debug tools I have no way to figure out the real issue.
Try reporting this on their github issue page :/
