### ISSUE TITLE
Detector blocks detecting something from zombie awareness

### ISSUE THREAD

**Issue by Octopork** [BeetoGuy/BetterWithMods#303]
Version 0.14.21

After a seemingly random number of updates detector blocks are getting stuck in their 'detected' state after a block is removed from in front of it. It remains in this state for ~30 seconds to 2 minutes before finally switching back off.

This only occurs when placing down blocks, it does not occur with items, mobs or the player.

![Example](https://cloud.githubusercontent.com/assets/8586800/25039586/9c80efec-2147-11e7-9608-aefd065ee3a3.png)
(part of an attempt to automate soul urns, occurs with block just on it's own too so it's not the project red placer causing this)

**Comment by Octopork** [comment]
Ignore for now, very likely to be linked with #302. I'll try and track down the offending mod.

**Comment by Octopork** [comment]
After bumbling around for a bit being mighty confused as to whats going on and I've narrowed it down to what i believe is the cause.

after a random number of breakages it seems  that it's detecting an entity from zombie awareness, a sound 'marker'  i believe. I don't know if this is something the detector block should should filter out or if it's an issue with [zombie awareness](https://github.com/Corosauce/ZombieAwareness) itself.

**Comment by BeetoGuy** [comment]
I suppose the best way to fix this on our end would be to filter out anything that doesn't extend EntityItem or EntityLivingBase, since the detector block should only be looking for those two cases.
