### ISSUE TITLE
Buildcraft compat

### ISSUE THREAD

**Issue by meelock** [BeetoGuy/BetterWithMods#306]
Since Buildcraft is (sort of) out on CurseForge, maybe it should be time to brainstorm compatibility with Buildcraft, and how it would be implemented.

Anyway, I hope something can be done in the near future.

**Comment by primetoxinz** [comment]
What do you have in mind?

**Comment by meelock** [comment]
First, make water not infinite with pumps. Second, recipes should likely be modified to match btw balance, such as engines being harder to craft. Third, miscellaneous changes to Buildcraft, such as change crafting mechanics or add new ones to get components for Buildcraft.

**Comment by primetoxinz** [comment]
If you want to mock up any recipes and put them here I can implement them

**Comment by meelock** [comment]
All good, I will work on recipes when I have time.

**Comment by meelock** [comment]
(Man I hope I can do school work, with this new modpack being made. I often get really sidetracked when working on modpacks.)

**Comment by DaedalusGame** [comment]
maybe it's time to port better with addons 🤔
