### ISSUE TITLE
[1.11.2] Actually Additions dropper infinite dupe bug with hardcore buoy

### ISSUE THREAD

**Issue by Aphyxia** [BeetoGuy/BetterWithMods#307]
Actually Additions: r106
Better with mods: 1.1.5
Forge: 2282

Actually Additions Automatic Precision Dropper keeps the item(s) when outputting them when hardcore buoy is ON resulting in infinite items.

Tested also without other mods and in singleplayer and multiplayer.

Video of it happening: https://www.youtube.com/watch?v=9z_Hnwqo4iI (only important part is the dropper)

Maybe related to this bug: https://github.com/BeetoGuy/BetterWithMods/issues/248

**Comment by primetoxinz** [comment]
I have fixed this issue, but be warned if you update to the version with the fix certain things may break such as millstones, turntables, cooking pots. So if you update backup your world
