### ISSUE TITLE
Script Support

### ISSUE THREAD

**Issue by bookerthegeek** [BeetoGuy/BetterWithMods#308]
## Heyo ##
Just a quick Question / Favor if you could please...

Can you please support Ore dictionary in your MineTweaker Scripts? Specifically [here][script] in the `@NotNull IItemStack input` ? Basically a quality of life improvement so I can have one line of code per type of ore instead of one line per ore? 

Thank you for considering my request. 

[script]:https://github.com/BeetoGuy/BetterWithMods/blob/07a1a2ddc316ff834cbfb8e408e33aec061a8f3a/src/main/java/betterwithmods/integration/minetweaker/Kiln.java#L29

**Comment by primetoxinz** [comment]
Sure thing, has been added to the 1.11.2 version

**Comment by bookerthegeek** [comment]
@primetoxinz Thank you very much for the quick response. Would it be to much to ask to include this in the 1.10 branch?
