### ISSUE TITLE
Compatability requests.

### ISSUE THREAD

**Issue by bookerthegeek** [BeetoGuy/BetterWithMods#309]
## Heyo ##
Love your mod, but am wondering if you could add some cross mod support for some things...

- Hardcore Stumping, Bark & Debarked Logs
  - [ ] Natura
  - [ ] Pam's Harvest Craft
  - [ ] Random Things
  - [ ] TSON Craft
  - [ ] IC2

**Comment by primetoxinz** [comment]
Bark items are fairly easy to add in a more dynamic way and I may decide to do it sometime. 

But Stumps and debarked logs are frankly a lot of work to add for a new tree and kind of an unnecessary use of block ids. If there was a way to add stumping without adding a completely new block each time, I would consider it but cannot think of any ways to do. I'd like to see what @BeetoGuy thinks about this.

**Comment by DaedalusGame** [comment]
doesn't stumping hook into tree generation events? so it'd be even more of a pain to do it for modded trees...?

**Comment by primetoxinz** [comment]
exactly my point, it could be done but it wouldn't be fun

**Comment by BeetoGuy** [comment]
I think I'm with prime on this, it's possible, but it's honestly a question of whether or not we would want to take up additional block IDs and see if it would even be possible to hook into the tree generation.
