### ISSUE TITLE
[1.11.2] Hunger System don't functioned

### ISSUE THREAD

**Issue by cyberpunkbln** [BeetoGuy/BetterWithMods#311]
Hello:

Mod: Better With Mods-1.1.7-1.11.2
Forge: forge-1.11.2-13.20.0.2286

With this new version, the hungersystem is not functioned. The old hunger system from minecraft is still active. I have deleted the old config and used a fresh configured config. I don't use Apple Core and the Switch is to force on enabled.

And Animals produces not dung.

Can it be that some new Config-Variables are a little bit buggy, that the new config-system ist at the moment not 100% bugfree and the Mod search for the old config-vars or trigger them?

**Comment by cyberpunkbln** [comment]
It's a config-vars problem, when i use 1.1.6 and then 1.1.7 load all functioned when the old config-vars are in the config.

**Comment by cyberpunkbln** [comment]
I'm searching for my own in the source code of the last 1.11.2 commit and i think the bug must happend after the 20 April and with the Quarks-Config-Module.

For now i must fix the gradle for all apis that will be called in the 1.11.2-1.1.7 Code and that are not in the gradle.build file.

Around the border i think some api-requirements can be deleted like Immersive Engineering, when this mod will be updated to 1.11.2 Man are on Mars:), smile.

Knows anybody the complete list for the deobf-dependecies list for all supported moduls?

**Comment by primetoxinz** [comment]
yeah, the new config system was not very highly tested. I will look into it

**Comment by primetoxinz** [comment]
Turns out I just forgot a line that enables HCHunger and Dung was not working due to a bug which I fixed

**Comment by cyberpunkbln** [comment]
Wow cool thx.

Short Question out of the bug: How i can implement the needed deobfs and apis without gradle or give it mave-repos for that? At the moment i try to get the dev-deobf for MCMultiPart and Mantle. I wonder why the Source for 1.11.2 has immersive-engineering deps, where immersive engeneering has no dev-deobfs?

When i try to compile yout last bugfix-commits before it gets to curseforge (oh yeah i cant wait:)) i need this information:), thx.

**Comment by primetoxinz** [comment]
1.11.2 branch does not require immersive engineering at all, but you have to use gradle as that is what Forge is built on.

**Comment by cyberpunkbln** [comment]
Yeah but when i try to compile the Mod he says me some Symbols not find and all symbols are from external apis like mantle, tconstruct or immersive engeenering.

Oh oi understand give it a special gradle task to resolve this?

i clone the newest branch with the commits and the i can paste an example compile error

**Comment by primetoxinz** [comment]
Due to the way our mod compatibility system functions you cannot simply clone and compile. You will have to load into an IDE and exclude the erroring mod compat classes or it will not compile

**Comment by primetoxinz** [comment]
Actually, there is another way. Simply delete `BetterWithMods/src/main/java/betterwithmods/integration/<Erroring Mods>`

**Comment by cyberpunkbln** [comment]
oh okay cool, i have only begin to grab my old j2me knowledges for only compile the newest versions from mods when it gives no jenkins-exp-builds or curseforge releases :).

Yeah cool thats the way, so i can have the latest bugfix-commit before it will be release on curseforge,smile.

thx

**Comment by primetoxinz** [comment]
No problem

**Comment by cyberpunkbln** [comment]
I have my bugfixed 1.1.7 Version of BWM :) .

A Warning i have, think this is the new Forge-Coding-Suggestion.

isEmpty() using ???
`
bwm-bugfix\build\sources\main\java\betterwithmods\common\BWCrafting.java:386: warning: non-varargs call of varargs method with inexact argument type for last parameter;
        addTurntableRecipe(BWMBlocks.UNFIRED_POTTERY, EnumPotteryType.CRUCIBLE.getMeta(), BWMBlocks.UNFIRED_POTTERY, EnumPotteryType.PLANTER.getMeta(), null);

 cast to ItemStack for a varargs call
  cast to ItemStack[] for a non-varargs call and to suppress this warning`

**Comment by primetoxinz** [comment]
it's not an actual issue, have to keep it like that for the varargs ability though

**Comment by cyberpunkbln** [comment]
Perfect, i hunger, iam fat and the cows are making dung:).
