### ISSUE TITLE
[1.11.2] [1.1.7] Eggs?

### ISSUE THREAD

**Issue by cyberpunkbln** [BeetoGuy/BetterWithMods#313]
Hello,
where can i disable the egg break into raw eggs, or is this a config that needs to be included?
greetz

**Comment by primetoxinz** [comment]
Why would you want to disable it? They still spawn baby chickens the same amount, just whenever it doesn't spawn a chicken it gives you food instead.

**Comment by primetoxinz** [comment]
Eh, I'll separate it anyways. I can see a purpose.

**Comment by cyberpunkbln** [comment]
Wow thx cool, more controll over the mechanism.
