### ISSUE TITLE
Hardcore stumping - add stump texture toggle

### ISSUE THREAD

**Issue by Coldwire** [BeetoGuy/BetterWithMods#314]
It'd be nice to have a config option to remove the special stump texture.

BWM seems very texture pack friendly, since it avoids using a lot of custom textures. The stumps are very out of place when using texture packs without custom mod support.

**Comment by primetoxinz** [comment]
Like all blocks stumps have a blockstate model which you can override in a resourcepack with whatever texture you want. There is no reason to add a config for something which can be done with resourcepacks already.
