### ISSUE TITLE
[1.11.2] Dust smelting recipes are affected by HCOres setting

### ISSUE THREAD

**Issue by jesmores** [BeetoGuy/BetterWithMods#318]
When HCOres is on, ore dusts added by other mods (in my case, FuturePack machine output and Rustic ironberries) also wind up smelting into a single nugget instead of an ingot.

While this does keep with the spirit of HCOres in that the ore multiplication afforded by advanced machinery still increases the amount you get from each ore (in nuggets instead of ingots), it makes it kinda hard to balance tech mods against magic mods which don't go through dust recipes and straight up produces ingots from ores (like Astral Sorcery) or goes through molten processes (like Embers).

Perhaps adding a config option to turn off adjusting dust recipes would be useful here?

**Comment by jesmores** [comment]
I forgot to mention, some mods (I think IC2/TechReborn/Gregtech) add "tiny dusts" which themselves smelt into nuggets, but when combined 3x3 make a full dust item that is supposed to smelt into an ingot. With the HCOres setting, you'd have the silly situation where 9 tiny dusts (which smelt into a nugget each) combine into one dust (which smelts into a nugget as well).

**Comment by BeetoGuy** [comment]
Could have sworn I had that as a separate feature already, but it looks like the rewrite ended up losing that in translation.

**Comment by jesmores** [comment]
Thanks!
