### ISSUE TITLE
Changes to default config

### ISSUE THREAD

**Issue by Coldwire** [BeetoGuy/BetterWithMods#322]
1.1.9 - 1.11.2
I base these changes on the assumption that the default should be as close to BTW as possible.

        # Only Wolves will produce dung
        B:"Only Wolves"=false

Defaulting this to false means that wolves (by default) are pointless in this mod. Wolves only producing dung gives them a unique purpose, and gives players a reason to explore to find them.

        # Amount (in nuggets per ingot) tools and armor in the crucible reclaim. Does not affect diamond or soulforged steel ingot reclamation. (Set to 0 to disable reclamation entirely.)
        I:"Reclaming Count"=9

BTW gives 6 nuggets per iron, to further encourage mob farming. With it defaulting to 9, once you have an iron pickaxe and a crucible, you'll never need to worry about investing resources in another iron pick again.

**Comment by primetoxinz** [comment]
I'll make these the defaults when I get the chance

**Comment by primetoxinz** [comment]
Fixed in 1.2.0, will be on curse soon.
