### ISSUE TITLE
Hibachis accept indirect redstone signals

### ISSUE THREAD

**Issue by Coldwire** [BeetoGuy/BetterWithMods#323]
1.1.9-1.11.2

Hibachis activate when the block next to them receives a strong redstone signal. This isn't necessarily a "bug" - many mechanisms in the game work this way... but it is inconsistent with BTW.

It's an incredibly tiny thing, but I'm sure there's some minuscule implications to this.
The images explain it best.
[Imgur gallery](http://imgur.com/a/f2MGI)

**Comment by primetoxinz** [comment]
We let this through, as it makes it so you can power hibachis with redstone blocks.
