### ISSUE TITLE
Implement "Too exhausted for manual labor"

### ISSUE THREAD

**Issue by Coldwire** [BeetoGuy/BetterWithMods#324]
1.1.9 - 1.11.2

In BTW, once the player reaches 3 hunger shanks, they are met with the message "You're too exhausted for manual labor" when attempting to right click a hand crank.

This helps to prevent the player from overdoing things and possibly killing themselves if not paying attention.

**Comment by primetoxinz** [comment]
Fixed in 1.2.0, will be on curse soon.
