### ISSUE TITLE
No hunger penalty for jumping

### ISSUE THREAD

**Issue by Coldwire** [BeetoGuy/BetterWithMods#325]
1.1.9 - 1.11.2

In BTW, jumping has a fairly steep cumulative cost on hunger. In fact, every time you jump, the hunger bar vibrates a bit, to accentuate the cost.

The mechanic promotes the creation of proper stairways, and makes you think twice (and plan ahead) before you decide to drop down a deep chasm or climb a tall mountain.

I'm not sure if this is implemented in BWM, but I can say that cursory testing shows BWM being far less penalizing. Adding the vibrating hunger bar would also help.

There are a couple of considerations to keep in mind when implementing this.

Your hardcore hunger is a heck of a lot more hardcore than BTW's. Steak only fills a shank and change in BWM, where in BTW it looks like a little over 2. I haven't tested other foods, but I'll assume that the steak isn't an isolated example. If you increase the cost of jumping, you'll probably want to buff hunger values too, otherwise it's going to be way too easy to starve early game.

Autojump could pose an issue. I think that forcing the player to deliberately hit the spacebar every time they want to jump helps to remind them of the cost. If you can just walk up to a block and hop up effortlessly, it's going to be very easy for people to forget about the mechanic until they are starving. Therefore, it could be worthwhile to bundle in config to kill autojump altogether.

**Comment by primetoxinz** [comment]
If you could do some tests as to how many jumps it takes to lose a pixel of the hunger bar in BTW that would be helpful.

**Comment by Coldwire** [comment]
7 jumps causes the very first visible decrease.

**Comment by Coldwire** [comment]
The number between visible intervals is decreased to 4-5 when wearing full iron armor.

**Comment by Coldwire** [comment]
When wearing full leather armor, it takes 6-7 jumps.

**Comment by primetoxinz** [comment]
Alright, seems to be almost perfectly the same for that now :)
If you want, a table of hunger values for items would help me fix them.

**Comment by Coldwire** [comment]
I can do that.

**Comment by primetoxinz** [comment]
Also, does the hunger bar shake when sprinting?

**Comment by Coldwire** [comment]
Yes, it shakes constantly.

**Comment by Coldwire** [comment]
I'm testing the hunger values by right clicking hand cranks until it gives me the exhaustion message, which always leaves me at whatever 3 shanks minus one pixel/interval is. I'm going to eat the food, then give you the number of jumps it takes to get me back to 3 shanks minus one pixel. That way we can see the values with greater resolution, since we know 7 jumps = 1 pixel.

**Comment by Coldwire** [comment]
You know, I could do all that work, or I could just give you a link to the wiki, which lines up with my tests so far.
http://sargunster.com/btw/index.php?title=Hardcore_Hunger

**Comment by primetoxinz** [comment]
oh, lol didn't know they had that

**Comment by Coldwire** [comment]
It also looks like every single edible item in BTW (including weird crap like pumpkin seeds and poisonous potatoes) has a stack size of 16.

**Comment by primetoxinz** [comment]
so, turns out it's not very easy to change hunger values... I've been thinking of making HCHunger require AppleCore and this might be the reason to do so.

**Comment by Coldwire** [comment]
I'll have to take your word for it.

Hope you don't mind, but while I'm on a roll I'm gonna keep opening up issues on nitpicky inconsistencies.

**Comment by primetoxinz** [comment]
go for it.

**Comment by primetoxinz** [comment]
Fixed in 1.2.0, will be on curse soon.
