### ISSUE TITLE
Breaking a Cauldron gives you a Crucible

### ISSUE THREAD

**Issue by kojul** [BeetoGuy/BetterWithMods#327]
MC: 1.11.2
Forge: 13.20.0.2296
BWM: 1.1.9

To reproduce:
Add BetterWithMods to any pack/vanilla instance.
Cheat in/make cauldron.
Place it, then break it with a stone pickaxe or better.
Have a crucible!

**Comment by primetoxinz** [comment]
Fixed in 1.2.0, will be on curse soon.
