### ISSUE TITLE
Implement gloom

### ISSUE THREAD

**Issue by Coldwire** [BeetoGuy/BetterWithMods#328]
One of my favorite features from BTW.

When below a certain lightlevel, the text "Gloom" appears above the hunger bar, and the FOV very, very slowly starts to increase, creating a lengthening tunnel effect. Most importantly, it plays some creepy cave sounds every now and then. They become more frequent as time goes on. You move and break blocks more slowly.

"If the player is affected by Gloom, his exhaustion level will be multiplied by 50%."

**Comment by Coldwire** [comment]
There's a lot going on in this feature in BTW. After being in darkness long enough, Gloom becomes Dread, with more sound cues and probably steeper costs, and then Terror, in which you slowly start taking damage, coupled with the nausea effect.

**Comment by primetoxinz** [comment]
This feature is more or less not possible as it requires large modifcations through a core mod, which I'd prefer to avoid

**Comment by Coldwire** [comment]
That's a shame. I don't know anything about the backend of this, but it could be possible to come up with a watered down version that might serve the same purpose of discouraging pitch-dark exploration.

**Comment by primetoxinz** [comment]
that's the major change that can't be done, pitch-dark. I could likely implement all the negative effects, but you'd still be able to see

**Comment by Coldwire** [comment]
Personally, I think the negative effects are the most important part. The pitch black thing is cool, but hardly necessary. There's always [this](https://minecraft.curseforge.com/projects/hardcore-darkness) if it's really important to people.

**Comment by primetoxinz** [comment]
Do you know if the Gloom Effect takes precedent over Hunger or Fat status effects?

**Comment by Coldwire** [comment]
The Hunger effect doesn't make a text line, it only shows up as "food poisoning" in the inventory. Gloom only shows up as text, it doesn't have its own placard in the inventory.

Testing fat.

**Comment by primetoxinz** [comment]
By hunger I meant Starving/Famished/etc

**Comment by Coldwire** [comment]
http://imgur.com/a/kbIN7

**Comment by primetoxinz** [comment]
ok, does the gloom effect stay at that position when "Hungry" isn't there?

**Comment by Coldwire** [comment]
http://imgur.com/a/cWUke

**Comment by primetoxinz** [comment]
ok, thanks!

**Comment by Coldwire** [comment]
happy to help

**Comment by primetoxinz** [comment]
could you get a rough estimate for how long each gloom phase lasts?

**Comment by Coldwire** [comment]
Yep.

Gloom lasts for 1 minute.
Dread lasts for 1 minute.
Terror lasts until death.

**Comment by primetoxinz** [comment]
uploading to curse ;)
