### ISSUE TITLE
Hand crank can have right click held down

### ISSUE THREAD

**Issue by Coldwire** [BeetoGuy/BetterWithMods#330]
In BTW, one click=one crank. Holding it down won't keep cranking. You also can't right click a crank, keep holding down the button, and moving your mouse over another crank. You can only right click again once the stick has moved back to the starting position.

This makes it easier to prevent AFKing, and also means that it's harder to run two cranks at the same time.

**Comment by primetoxinz** [comment]
Not exactly sure if this is possible due to how minecraft works.

**Comment by kojul** [comment]
I'm not sure why it matters considering the hunger cost of cranking.

**Comment by Coldwire** [comment]
I definitely wouldn't rank it as a game breaking bug lol
