### ISSUE TITLE
Remove Easy and Peaceful

### ISSUE THREAD

**Issue by Coldwire** [BeetoGuy/BetterWithMods#337]
If possible, remove peaceful and easy, leaving only normal and hard. This "protects" the player from the temptation to throw the game on peaceful in a rough spot.

**Comment by KnightMiner** [comment]
There is a difficulty lock in vanilla that serves the same purpose, and I feel like removing g difficulties without a core mod would be difficult.

**Comment by Coldwire** [comment]
Yeah, that's what I was afraid of. I forgot about the lock, it definitely helps to fill in the same role.
