### ISSUE TITLE
Combined bugs/tweaks/additions

### ISSUE THREAD

**Issue by Coldwire** [BeetoGuy/BetterWithMods#339]
## Bugs
- [ ] Make a creative world, make a light level 0 area, then change to survival. No gloom. _oh well, no idea_

## Tweaks
**Recipes**
- [ ] Axes, including the [soulforged steel axe](http://www.sargunster.com/btw/index.php?title=Refined_Axe/Recipe), should have their cost reduced to only 2 ingots or stone.
- [ ] Add in useful 1 plank -> 2 sticks recipe.

**Other**
- [ ] Make steel blocks wither-proof

## Additions
- [ ] **HCItemDecay**
"Added a new system for despawning items dropped on player death. Instead of using the regular item despawn timer, these items will disappear one Minecraft day after the player dies (20 minutes real time), regardless of whether the chunks they are in are loaded or not. This makes the behavior of these items more consistent regardless of whether you are near original spawn or not, and reduces the effectiveness of gamey behavior like avoiding the area in which you died so that the items don't despawn. It will also hopefully further encourage the building of infrastructure like road and rail networks to quickly return on death. Note that in single player if time advances to the next day due to a death, this is taken into account by the system and it does not cause you to lose the time in between in terms of item despawn. Also note that this change will not affect items dropped on death previous to installation of this version, so if you have any lingering in the world, they will despawn as normal."

yeah... no
- [ ] **HCFurnaces**
- [ ] **HCChickens**
- [ ] **HCSquids**
- [ ] **Animal panic**
- [ ] **Stake**

## Changes
**5/27**
- HCVillages!

**5/25**
- Reduced number of doors crafted from 3 to 1.
- Added HCSaw
- Slowed down millstone grinding/added config
- Gigantic change to hand crank balance (1 less crank wowzers)

**5/24**
- Fixed HCLumber description
- Remove crafting bonemeal directly from bone in crafting bench
- **HCSpawn**   _untested_ In SSP, if the player dies at night, set it to day and clear up rain/storms. Tied in with the 20 minute timer that prevents players from killing themselves repeatedly to find a better spawn.
- **HCInjury** Can't damage when affected by injury. Various "oof" noises. Blindness at 1 heart.

Earlier
- ~~**HCNames**~~
- ~~**HCSeeds**~~
- ~~**Kibble**~~
- ~~**HCBonemeal**~~
- ~~**Redstone block light**~~
- ~~Chickens can endlessly be fed hemp seeds~~

**Comment by primetoxinz** [comment]
Tanned Leather: idk, armor is a lot of work and not particularly worth it.
Light blocks already do this.
Removing difficulties: what @KnightMiner said
Animal Panic: not even sure if that is possible, if so I have no idea how.
Kibble: on the todo
Stake: maybe
HCBone: done
Glow: done
Autojump: tried, didn't work. just disable it manually.

**Comment by primetoxinz** [comment]
HCFurnace: Impossible with vanilla sadly, it has been tried. I could be done, but would require adding a separate furnace and disabling the vanilla one. Maybe someday.

HCSquids: Have made attempts, need small changes in Forge to make it happen correctly, will look into it some day.

Player Name: Randomthings did it by coremod :/

**Comment by Coldwire** [comment]
You have a donation link? Me and a few other people are having a lot of fun with this, it'd be nice to give a bit for your work.

**Comment by primetoxinz** [comment]
I do, you really don't have to, do this entirely for fun, but if you are that [convinced](paypal.me/primetoxinz).

**Comment by primetoxinz** [comment]
Well, Thanks man. You really didn't have to, but I do appreciate it very much though. 
I suggest joining the irc on esper.net #betterwithmods as I might start a dev server soonish and I'd say you get an invite for that ;)

**Comment by Coldwire** [comment]
I appreciate that, I'll pop in every now and then.

**Comment by Coldwire** [comment]
Is there a technical reason why coremod features couldn't just be in their own little config section, disabled by default?

**Comment by DaedalusGame** [comment]
I have a feeling that coremods, because of how deep they go, need to be loaded always and you can't make a config for it. I don't think I've ever seen a forge mod that had a toggle-able coremod.

**Comment by Coldwire** [comment]
I'm totally talking out of my ass here, I have 0 idea how any of this works. I'd appreciate if you could help me understand.

What I'm getting is if you have coremod functionality, your mod is a coremod, regardless of whether or not you use that functionality. No matter what your config file says, forge loads your mod as a coremod.

My question is, is that what breaks compatibility? If you have a coremod that has all of its coremod-y things turned off, is it still going to interfere with anything?

**Comment by DaedalusGame** [comment]
Yes, it will still inject into vanilla code and break anything that tries to inject into the same methods, if i understood correctly. This is why the forge team considers it a very selfish practice.

**Comment by primetoxinz** [comment]
Yeah, there is no way to have a configurable coremod because the coremod has to load before minecraft even gets to load, so configs can't even exist at that phase. Additionally coremodding is incredibly hard to do as it requires a deep understanding of how Java looks to a computer rather than to a person, doubling the efforts required to make it work. All in all it's really hard and bad practice which I'd like to avoid.

**Comment by Coldwire** [comment]
Is it possible, for HCVillages, to flat out stop the generation of villages inside the HCStructures radius, or is any kind of tampering with the villages not possible? It'd accomplish the same goal.

I'm not gonna open any more issues unless it's a bug. If I think of what seems like doable tweaks, I'll throw it in OP, and maybe leave a message for the notification.

**Comment by DaedalusGame** [comment]
It looks like that would be easily possible. I think there's an event for village generation that can be cancelled.

**Comment by primetoxinz** [comment]
The axe recipe change _can_ be done, but I kinda feel like its unnecessary and would end up requiring a lot of mod compat because so many mods add tools. Not sure if it should be done

**Comment by Coldwire** [comment]
If it were me, I'd stick it as a default disabled config with a disclaimer that minetweaker is needed for other mods. Then again, the change could be made with minetweaker in the first place.

**Comment by primetoxinz** [comment]
Not sure if semi-abandoned villages are worth the effort. Thoughts?

**Comment by Coldwire** [comment]
As opposed to completely abandoned? What's the difference?

**Comment by primetoxinz** [comment]
```
Villages within 2000 blocks (circular) from Spawn are abandoned, meaning that there are no crops, water in the farms, loot in the blacksmiths house, or windows present. However there is a chance that a farmer (brown) villager may still spawn here. They also provide excellent shelter in the early game, provided that the player covers the windows and doors. Within this circumference desert and jungle temples are "looted", having none of the loot an untouched temple would have, however the jungle temple still has all the redstone circuitry and devices.

Villages between 2000 and 3000 blocks from spawn are "semi-abandoned", meaning that while still missing the windows these villages contain crops (less than in full villages) and villagers, with the mention that librarians (white) and priests (purple) are unable to spawn in semi-abandoned villages. Starting at 2000 jungle and desert temples are no longer "looted" and contain their respective unique loots.

Villages further than 3000 blocks from spawn are intact, containing everything vanilla villages have. However it is important to note that specific villager spawn together with their respective buildings, so a village without a church will not have a priest. This, together with the fact that baby villagers take the profession of one of their parents means that even an intact village may not be complete, requiring the player to seek out more.


```

**Comment by Coldwire** [comment]
I don't think it's a huge difference. The main point of the feature imo is limiting crop spawns.

**Comment by primetoxinz** [comment]
right, if you want to be fully faithful though it's not that much work
