### ISSUE TITLE
[1.11.2] Pulley stole Hopper's recipe

### ISSUE THREAD

**Issue by jesmores** [BeetoGuy/BetterWithMods#345]
This is on the latest version (as of now) 1.2.7

Filtered Hopper has no recipe in JEI. When attempting to craft it using the recipe, you get a pulley instead. JEI reports the recipe for pulley is the one that's supposed to be for the hopper.

**Comment by jesmores** [comment]
That was quick 👍 

Was about to log another issue for the turntable recipe, but from the commit looks like you fixed it too (among others).

**Comment by primetoxinz** [comment]
Yeah, knew the exact issue, just missed it on my last pass
