### ISSUE TITLE
[1.11.2] Food value tooltips incorrect with HCHunger

### ISSUE THREAD

**Issue by jesmores** [BeetoGuy/BetterWithMods#346]
There's a couple of mods that add food value to the tooltip. When HCHunger is enabled, these tooltips don't match what the food actually restores when eaten. For example Steak and Potatoes has the value tooltips shown below, but when eaten only restore about 3 pips on the hunger bar.

AppleSkin - 1.0.6
![image](https://cloud.githubusercontent.com/assets/125214/26038526/48ac8176-38bf-11e7-988b-333a5d488b17.png)

Quark - r1.2-91
![image](https://cloud.githubusercontent.com/assets/125214/26038509/cb868b10-38be-11e7-875a-2e12769f1baf.png)

BWM Version: 1.2.7

**Comment by primetoxinz** [comment]
That is due to the fact that hunger is entirely different in BWM. We scaled the hunger bar to have be 6 times as large, so that food can be more finely valued. So, divide what is shows by 6, and that is the proper value.

**Comment by jesmores** [comment]
Should the affected mods update their tooltip rendering to account for max hunger then? Is that a value that can be taken easily or is it internal to BWM?

**Comment by primetoxinz** [comment]
It's certainly possible for other mods to take into account if HCHunger is available and react accordingly, that would be up to them.

**Comment by Vazkii** [comment]
How exactly would one go about fixing this?

**Comment by primetoxinz** [comment]
I have added an event into our API, FeatureEnabledEvent. Just subscribe to that and when "hchunger" is enabled, you would simple have to divide the food value by 6.

**Comment by squeek502** [comment]
@Vazkii it looks like the method of including the event class is not currently working--the event listener never gets called (new Quark version doesn't do the hunger value scaling, and couldn't get it to work in AppleSkin).

@primetoxinz is it certain that the event is being fired?

**Comment by primetoxinz** [comment]
The event is post definitely fired during preInit (here)[https://github.com/BeetoGuy/BetterWithMods/blob/1.11/src/main/java/betterwithmods/module/Module.java#L136]

**Comment by squeek502** [comment]
Perhaps it's being fired before Quake/AppleSkin's handlers are registered? 

I just stumbled on the fact that (I think) any mod that includes the BWM API package-info gets put in the load order after the dummy BWM API container, which is loaded after BWM, so it seems like it might not be possible for this event to be heard during preInit (I found it by creating an impossible load order by trying `before: betterwithmods` in AppleSkin).

Seems like the event will need to be delayed until after we can register our event handlers.

**Comment by primetoxinz** [comment]
I can always fire it in init or post, which ever you'd prefer

**Comment by squeek502** [comment]
Doesn't matter to me, whatever you think would be best. I'll be registering the listener in preInit.

**Comment by primetoxinz** [comment]
Alright. This change to the event firing does in fact fix Quark's implementation. Although @Vazkii I did not take into account your existing division by 2, it should be actually be 6

**Comment by squeek502** [comment]
Alright, cool, support added to AppleSkin via https://github.com/squeek502/AppleSkin/commit/3e45fe0c187a10320920dd079cbc695e84e0547d, will be in the next version.

**Comment by primetoxinz** [comment]
Awesome, gonna close this unless something else comes up.
