### ISSUE TITLE
Seed changes

### ISSUE THREAD

**Issue by Coldwire** [BeetoGuy/BetterWithMods#348]
1.2.8

Wheat/wheat seeds should only be found from inhabited villages outside the radius defined by HCStructures, not dropped from tall grass. Villages within that radius shouldn't have any kind of crops, loot, or living villagers. Occasional zombie villagers could be a nice touch. This mechanic is one of the primary motivators for early game exploration.

Hemp seeds can currently be endlessly fed to chickens until they breed.

Chickens aren't following players holding hemp seeds.

Hemp tall grass config should default to false a la BTW. This prevents players from immediately having the means to lure chickens - they need a hoe or pumpkin seeds first.
        # Hemp Seeds will drop when breaking Tall Grass
        B:"Tall grass Hemp Seeds"=true

**Comment by Koward** [comment]
Assuming official stance has not changed from #22 , it defaults to true to keep consistency with vanilla/other mods and avoid confusion for the main player base.

**Comment by Coldwire** [comment]
I feel like we've already crossed the point of confusion for the average MC (and even modded MC) player. Someone installing this mod knows exactly what they're getting into - the features are all copy pasted from BTW. I mean, no one's even bothered with extensive documentation, something I attribute to the fact that the BTW wiki itself works just fine.

Vanilla people are already going to be lost. Progression in the mod beyond punching the first tree is largely distinct from vanilla. I'd bet that BWM has an ass "retention rate" of players - little Johnny downloads the "windmill mod", and uninstalls it when he realizes his stone pick has 6 uses. And that's fine. BWM caters to a different group of people, just like BTW did.

What it comes down to is this - is this an infrastructure mod based on BTW with optional hardcore elements, or is it a _recreation_ of BTW (a complete progression overhaul) with more configurability and transparency?

If it's the first, then we should make all hardcore elements disabled by default. That'd keep little Johnny happy, and probably get more users to hang around. If it's the second (definitely what I'm after), then there's no sense dancing around the fact, and it should come configured with the intent of boxing the player into its revised progression.

**Comment by primetoxinz** [comment]
HCVillages is not implemented due to lack of control over village generation without heavy coremodding. For that reason, crops will stay in their vanilla stance until there is a way to do it that is reasonable, and to follow suit with that Hemp will also stay as a tall grass seed to not be overly confusing. 
Animal code will also require a large amount of replacement that may happen someday, but not any time soon.
