### ISSUE TITLE
Block hardness and bare-hand punching

### ISSUE THREAD

**Issue by Coldwire** [BeetoGuy/BetterWithMods#349]
1.2.8

If possible, HCHardness should include changes to blocks typically punched (grass, dirt, sand, gravel, wool, and wood/planks).

Here are BTW's times to break by hand - it attributes the same values to its slabs (e.g. dirt slab takes 5 seconds).

Grass - 6 seconds
Dirt - 5s
Sand - 5s
Gravel - 6s
Wool - 10s
Wood/logs - 12.5s
Planks - 10s

**Comment by DaedalusGame** [comment]
It appears to already try to do that, but setting the speed modifier is commented out.

**Comment by primetoxinz** [comment]
At the current moment with the way minecraft works it's very difficult to control this, it was attempted before and had many issues.
