### ISSUE TITLE
suggestion Portcullis

### ISSUE THREAD

**Issue by Varg95** [BeetoGuy/BetterWithMods#350]
this should work just like the platform and the pulley but instead of ropes it could use chains(different name and texture should be enough) and the platform could be replaced with portcullis blocks with a higher blast resistance  and hardness.

**Comment by meelock** [comment]
This sounds like an interesting addition, maybe as well chain would have higher length maximum (If there is already a length maximum, and if there isn't one, then it might be wise to add one.)

**Comment by DaedalusGame** [comment]
I believe there is no length maximum, as the pulley has 4 slots (iirc) for 256 total length.
I'd actually be more in favor of just adding an iron portcullis block (or making iron bars pullable) instead of duplicating ropes into chains for that purpose.
