### ISSUE TITLE
HCLumber incorrect drops

### ISSUE THREAD

**Issue by Coldwire** [BeetoGuy/BetterWithMods#353]
1.2.8

Punching wood currently drops 2 planks, 1 sawdust, and 1 bark.

It should drop (per BTW) 1 plank, 1 bark, and 3 sawdust.

**Comment by KnightMiner** [comment]
I personally like the two planks as otherwise wood early game is just painful, so if it is changed, can it be configurable?

**Comment by primetoxinz** [comment]
I am going to keep the current values as it is now default as this is never going to be a fully port and I see no point in being ridiculous. I will add a config
