### ISSUE TITLE
[API] IDebarkable

### ISSUE THREAD

**Issue by DaedalusGame** [BeetoGuy/BetterWithMods#354]
IDebarkable currently doesn't seem to do anything. The debark event already hardcodes the check for vanilla woods, and all other woods are handled on the basis that they have a saw recipe. IDebarkable appears to only be used on aforementioned vanilla woods, and obtains the bark type for them. It's also implemented on already debarked logs (odd).

I'd suggest 
- adding a check for IDebarkable in the DebarkEvent
- have a method IBlockState getStrippedState(IBlockState state)
- adjust/add an overload to getBark that takes an IBlockState parameter (for mods that compress their logs into one class)
- (optionally) when adding recipes for the saw automatically, see if the block is IDebarkable and add the recipe with the correct bark

Alternatively, just remove it from the api and keep it for internal use?

Also, thing to note is that saw recipes don't affect debarking with an axe, it just lets you debark it, but creates oak stripped log and oak bark.

**Comment by primetoxinz** [comment]
I'm thinking Lumber and Debarking honestly need completely refactored to not depend on the Saw at allI'm going to put this on the back burner  though because... bleh
