### ISSUE TITLE
[1.10.2] Crash when using Aether legacy sky toot bucket + HCLiquids

### ISSUE THREAD

**Issue by Claycorp** [BeetoGuy/BetterWithMods#355]
https://gist.github.com/anonymous/2645b081a5ab0d3bb5df1e5d8e0403fe

Also on totally different topic, are you done updating 1.10.2 with features? Seeing lots of new stuff coming but only for 1.11 :/

**Comment by BeetoGuy** [comment]
For the most part, yeah. It's probably going to be mostly bugfixes from here on out.

**Comment by Claycorp** [comment]
It's times like this that stuck... There's about an equal number of people not on 1.11 as there is people doing only 1.11. I'll look forward to the day I can purely work with 1.11 and all the new stuff until then. Thanks for the quick response and good work :+1:

**Comment by BeetoGuy** [comment]
Trust me, I'm waiting on some updates myself before I fully commit to 1.11, it's just that maintaining two codebases gets pretty tedious. In any case, looking at Aether Legacy, it looks like they don't assign a container item for their bucket. Not really something I can fix on my end, but I can catch the container item being null and not follow through with the event.

**Comment by Claycorp** [comment]
Don't blame ya for dropping 1.10 to bugfix only.
I'll pop an issue over there so it gets properly fixed also.
