### ISSUE TITLE
Null Pointer Exception for minetweaker support

### ISSUE THREAD

**Issue by WolfieWaffle** [BeetoGuy/BetterWithMods#358]
I have this line in a minetweaker script:
`mods.betterwithmods.Mill.add(<immersiveengineering:metal:18> * 2, <immersiveengineering:metal:13>, [<ore:oreIron>])`

and I get a Null Pointer Exception when trying to reload minetweaker, and the recipe is not added

**Comment by primetoxinz** [comment]
can you give fml-latest.log` and `minetweaker.log`?

**Comment by WolfieWaffle** [comment]
https://pastebin.com/M91ad9sM

https://pastebin.com/fWaqm1Wg

**Comment by primetoxinz** [comment]
Can you post the entire `ores.zs`? there is nothing indicating this is our fault

**Comment by WolfieWaffle** [comment]
All it is right now is this:
`var dustCopper = <immersiveengineering:metal:9>;
var dustIron = <immersiveengineering:metal:18>;
var dustNickel = <immersiveengineering:metal:13>;

mods.betterwithmods.Mill.add(<immersiveengineering:metal:18> * 2, <immersiveengineering:metal:13>, [<ore:oreIron>])`

**Comment by WolfieWaffle** [comment]
agh that code formatting did not work

**Comment by primetoxinz** [comment]
The missing semicolon on the last line is likely causing this

**Comment by WolfieWaffle** [comment]
Oh wow how did I not see that, I usually look for those things first. Oh well it fixed it, thanks and sorry for me being dense XP
