### ISSUE TITLE
Ｈｅｒｅ   ｗｅ   ｇｏ - Issues with Recipes

### ISSUE THREAD

**Issue by DaedalusGame** [BeetoGuy/BetterWithMods#362]
- [x] Diamond Ore smelts into diamond nuggets, which can be turned into Diamond Ingots, skipping the iron and creeper cost of the cauldron recipe.
- [x] Brick, Condensed Hellfire, Nether Brick have recipes for smelting in a stoked crucible, but because no nuggets exist, they don't have any input at all.
- [x] Diamond Nuggets to Ingots appears twice in stoked crucible
- [x] Iron Nuggets can be smelted into Iron Ingots in an unstoked crucible (this is probably intended???)
- [x] K-Kiln still smelts ores into ingots instead of nuggets?

- [x] Hopper looks like pulley on its recipe handler (#361)
- [x] Turntable looks like hopper on its recipe handler (#361)

**Comment by primetoxinz** [comment]
- Iron nugget in unstoked was unintentional 
- Kiln can smelt ingots when `HCOres: Ore to Nugget Smelting` is disabled.
