### ISSUE TITLE
[Enhancement] Add Biomes O Plenty Support to hardcore piles and seeds

### ISSUE THREAD

**Issue by KnightMiner** [BeetoGuy/BetterWithMods#363]
Currently I have hardcore piles enabled which causes sand, gravel, and dirt to drop piles, but it does not affect Biomes O Plenty dirt variants. It would be nice if they were all affected for consistency.

In addition, it seems Biomes O Plenty grasses still drop seeds when hardcore seeds is enabled.

Using version 1.2.11-1.11.2 if relevant.

**Comment by primetoxinz** [comment]
I'll add this soon, but for the time being you can register the vanilla piles to any block using `mods.betterwithmods.Piles.addPile(input, output)`
