### ISSUE TITLE
Cauldron recipes (yepp)

### ISSUE THREAD

**Issue by DaedalusGame** [BeetoGuy/BetterWithMods#365]
#Ender Slag doesn't cook into Soul Flux anymore, which makes it impossible to obtain SFS
I've verified that all secondary outputs are vaporized. they don't show in JEI and they aren't returned on crafting.
Anytime an item cooks in the cauldron, it will fill the entire cauldron with phantom items.
[Example](https://image.prntscr.com/image/bf21d122b5da402cba9b3eea2559729a.png)
Oh also, I'm sitting at one stack of tallow from 16 Porkchops. The longer the phantom items stay in the cauldron, the more items will be created from one craft process. (I think)

**Comment by primetoxinz** [comment]
Oi... I'll look at this tomorrow

**Comment by BeetoGuy** [comment]
I think I've figured it out. Since InvUtils::insert doesn't break the for loop after inserting an item into the inventory, it just keeps adding the item repeatedly.

**Comment by Konclan** [comment]
Has this been implemented in V1.2.12-1.11.2? I'm still getting the bug if so

**Comment by primetoxinz** [comment]
This will be on curse soon, please try this https://github.com/BeetoGuy/BetterWithMods/releases/download/1.2.13/Better.With.Mods-1.2.13-1.11.2.jar

**Comment by Konclan** [comment]
Yeeeess!!! Thank you so much. This mod is fantastic!
