### ISSUE TITLE
[1.10.2] Tinkers issues.

### ISSUE THREAD

**Issue by Claycorp** [BeetoGuy/BetterWithMods#367]
I'm combining them all into one issue as it deals with the same mod.

1. Mattocks don't count as shovels. Digging with them just gives back piles.
2. Slime liquid counts as water and will hydrate farm land but isn't affected by HCBuckets.

**Comment by KnightMiner** [comment]
Slime water is a limited resource, no infinite sources, so placing flows instead of sources means a loss of the liquid entirely.

----

Mattocks use the tool class "mattock" internally if you want to add a case for it.

**Comment by Claycorp** [comment]
I don't think we are on the same fluid mechanics page. 
The slime liquid that spawns in islands is finite in the sense that only X amount will ever be generated. Correct, but HC Liquids doesn't stop sources form generating it stops the player from moving source blocks at all. You can't move the liquid at all without out it 100% totally being destroyed. If you pick up a bucket of water and place it the fluid then is destroyed as it 'flows' away. 

Allowing slime to be moved as a block while it works the same as water breaks this whole mechanic as the slime isn't hard to get. Yes I could make islands harder to find but that also affects slime trees and other things I don't want to change.

**Comment by KnightMiner** [comment]
You pick up the source block with the bucket. The source is deleted from the world. You place it down, you get no source.

Also, slime water has properties beside those of regular water (slime spawning stuffs), so it has a use case to be moved outside of farms.

**Comment by Claycorp** [comment]
I don't think we are talking about the same version then. Blue slime in 1.10 doesn't spawn slimes. It also is place-able in the world and flows, thus making it a source block.

**Comment by KnightMiner** [comment]
I make the mod. The blue liquid is where they spawn, or on the slimy grass. I don't recall if they spawn outside of slime island boxes, but being able to move the liquid within the box is useful.

It is normally placable, but you are proposing that hcbuckets applies to it making it no longer placable.

**Comment by Claycorp** [comment]
I know you make the mod.... I know how it works in-game as I have/am tested/ing it. Slimes spawn in islands limits not on stuff moved outside of that area.

Yes I am proposing that once its picked up its destroyed as it acts like water for crops and that is part of why someone would use HC water or buckets whatever... You can easily make whatever slime farms you want around the island without moving anything. Else you can grow trees for slime.

**Comment by BeetoGuy** [comment]
I'm with Knight on this, in regards to slime water. I figure, since it's a finite resource that's both difficult to obtain and could easily be destroyed from a misclick, it's not too game-breaking to leave it as-is.

I'll add an exception for mattocks into the HCPiles event.

**Comment by Claycorp** [comment]
Its not really that difficult to obtain though. Default slime island generation is fairly common and you can pillar up into the bottom and just grab a bucket out with no issues at all.

**Comment by BeetoGuy** [comment]
Pillaring might be addressed in the future, if we can manage to get HCJumping to cooperate. I think it's more or less one of those issues where we just have to trust the player to make the judgement call.

**Comment by Claycorp** [comment]
HCJumping won't be in 1.10 though right? I guess I'll just find some way around stopping people then as you can't trust people to do as you wish. I've tried that in the past.

**Comment by BeetoGuy** [comment]
Oh, right, I forgot this was a 1.10 issue. My suggestion would probably be something along the lines of increasing slime island rarity, or just disabling them entirely.

**Comment by Claycorp** [comment]
Yeah... I don't want to limit people finding them like I said above. I'll find a way around it don't worry. It's not a huge deal, just not preferred.
