### ISSUE TITLE
Hardcore ores dust amount unaffected by config

### ISSUE THREAD

**Issue by KnightMiner** [BeetoGuy/BetterWithMods#368]
The config allows you to determine how many nuggets are returned from smelting ores, but there is no option for dusts resulting in dust always smelting to one nugget. It would be nice if it were its own config even rather than just using the ore production count config.

Using Better With Mods 1.2.11-1.11.2.

**Comment by DaedalusGame** [comment]
I thought the production modifier was only for the kiln, and you can't put dusts in the kiln anyway?

**Comment by primetoxinz** [comment]
There is an Ore Production modifier for both the Kiln and normal furnace smelting. I will add a separate one for dusts in the furnace.
