### ISSUE TITLE
Duplication glitch with crucible and cauldron

### ISSUE THREAD

**Issue by Konclan** [BeetoGuy/BetterWithMods#369]
As shown in my video, there is a huge duplication glitch regarding the cauldron and crucible outputs. https://youtu.be/2gO3mtM5-Z4 (Headphone Warning: There is a very loud noise at the end of the video)
The output system for all the 'machines' themselves seem very impractical and would recommend a different slot for outputs.

**Comment by BeetoGuy** [comment]
Already reported in #365, I'm going to be taking a look at it, see what's going on.
