### ISSUE TITLE
[0.11-1.10.2-hotfix2] Vertical windmill rendering bug?

### ISSUE THREAD

**Issue by Senjosei** [BeetoGuy/BetterWithMods#37]
This is my setup 
![2016-09-14_15 50 38](https://cloud.githubusercontent.com/assets/17807328/18506129/a0d79974-7a94-11e6-8a95-cfa92b0fce67.png)
if i place a gearbox on top of the windmill it turns into this
![2016-09-14_15 50 48](https://cloud.githubusercontent.com/assets/17807328/18506156/b9736fda-7a94-11e6-8d5d-8d426e36888b.png)

**Comment by DaedalusGame** [comment]
https://en.wikipedia.org/wiki/The_dress

**Comment by BeetoGuy** [comment]
Strange, I can see a shadow happening with default brightness and any in-between value, but if the lighting's configured to "bright," it doesn't happen. I'm sure I'm missing something in the TESRs, but I'm not entirely sure what.

**Comment by primetoxinz** [comment]
Close as it doesn't seem to be present anymore
