### ISSUE TITLE
1.2.13-1.11.2 Block Properties

### ISSUE THREAD

**Issue by sdaddy** [BeetoGuy/BetterWithMods#372]
I noticed in the changelog for 1.2.13 it has "Fix block properties." Is there any way to change this behavior? I created a new config, but I'm not seeing anything. I love a lot of the things BTM adds, but I'm trying to keep my pack close to vanilla mechanics. Thanks!

**Comment by primetoxinz** [comment]
This changed blocks added by the mod only, such as hardness and sound values for steel or soap, not vanilla blocks.
