### ISSUE TITLE
Survivalist Compatibility problem

### ISSUE THREAD

**Issue by Beardedflea** [BeetoGuy/BetterWithMods#373]
Versions
Minecraft: 1.11.2
Forge: 2299
Survivalist: 1.9.0
Betterwithmods: 1.2.13

Logs cannot be placed on top of the chopping block. Instead they are placed in the new block space above it, similar to placing a full block on top of a half slab. This includes all logs; Vanilla and Modded.
There are no crashes. There are no errors/warns or anything in the console. The block is merely being treated as a basic half slab.

The problem persists through multiple versions of both mods, so there is definitely a compatibility issue.
The problem can be fixed by changing the config:

#Makes Punching Wood return a single plank and secondary drops instead of a log, to get a log an axe must be used.
    B:HCLumber=false

However it would be nice to have the choice available to do both survivalist and HC betterwithmods without having to compromise one for the other.

Sidenote: This bug has currently been sent to the "Survivalist" mod author on the github issue page. So before people have the idea of posting, the mod author may already be aware of this issue.

**Comment by primetoxinz** [comment]
Probably fixed, no idea though.
