### ISSUE TITLE
Pulley glitches when rope is removed

### ISSUE THREAD

**Issue by DaedalusGame** [BeetoGuy/BetterWithMods#377]
...and it's currently extending rope. The entity keeps moving and the rope it places just pops off immediently.
Additionally, the rope entity can actually glitch through blocks, using up more and more rope. It can even extend into the void, eating up all the rope forever.

**Comment by MRebhan** [comment]
Looks like I need to rewrite the whole thing… Eventually, I have a lot to do at the moment and I'll not be here the next two weeks. After that I'll look into it unless someone else has already fixed it, the whole pulley code is a giant mess iirc

**Comment by DaedalusGame** [comment]
This one seems like a simple fix, actually. The entity just needs to check if the block above is rope.

**Comment by MRebhan** [comment]
Alright I'm on it

**Comment by MRebhan** [comment]
there we are. Again the whole thing is a huge mess, at some point I need to rewrite it completely.

**Comment by DaedalusGame** [comment]
👍
