### ISSUE TITLE
[1.2.13] Hemp appears as gear in Hwyla

### ISSUE THREAD

**Issue by kreezxil** [BeetoGuy/BetterWithMods#378]
In reference to #277, hemp is again appearing as Wooden Gear in the tooltip.

Using Hwyla-1.8.13-B26_1.11

**Comment by kreezxil** [comment]
Personally I'm going to switch tool-tip providers. I don't see anyone reporting on TUMAT or The One Probe.

**Comment by primetoxinz** [comment]
I'm fairly certain I know the cause of this but I believe it would require a rewrite of the hemp block that I don't think is worth the trouble.
