### ISSUE TITLE
HCHunger=false not working

### ISSUE THREAD

**Issue by drakray** [BeetoGuy/BetterWithMods#387]
If HCHunger=false, there is still notification and debuff ingame, as if HCHunger=true

MC 1.11.2
Forge 2310
BWM 1.2.16

**Comment by drakray** [comment]
HCInjury=false doesn't work either

**Comment by primetoxinz** [comment]
Only notifications should be showing up. Any debuffs that exist are due to your player existing with HCHunger enabled at some point and having leftover data, to stop the HCHunger you will have to kill your player.
