### ISSUE TITLE
NullPointerException at putting hemp into the mill

### ISSUE THREAD

**Issue by MatthiasMann** [BeetoGuy/BetterWithMods#388]
The crash: https://pastebin.com/tPNeBDEJ

Exceptions reported by JEI while starting the game: https://pastebin.com/gFN24rhw and https://pastebin.com/fU3S2f8c.

I'm using Better With Mods-0.14.24-1.10.2.jar.

**Comment by MatthiasMann** [comment]
After discussion on IRC: I updated Pam's Harvestcraft from
"Pam's HarvestCraft 1.9.4-1.10.2h.jar" to "Pam's HarvestCraft 1.10.2j.jar"
and I have the harvest craft compatibility enabled in the config.

**Comment by MatthiasMann** [comment]
Disabling harvest craft compatibility seems to work around the crash with the mill.

But JEI still complains about invalid crafting recipes (the https://pastebin.com/gFN24rhw one) - this might have been caused by disabling all hardcore features?

**Comment by primetoxinz** [comment]
No, it's likely a recent change in JEI's API from when we implemented it originally 1.10.2 requiring recipes to be more strict and clean, which BWM was definitely not in that version. I think it would require a pretty large refactor if that's the case.

**Comment by WesCook** [comment]
Ah, just hit this one too.

As a workaround, maybe we should disable Harvestcraft integration and replace it with a CraftTweaker script?  It looks like the list isn't too long.

https://github.com/BeetoGuy/BetterWithMods/blob/2d21b517642ea5469beaf8eb2b717a1c3b199203/src/main/java/betterwithmods/integration/Harvestcraft.java#L25

In all cases (that I've seen), the new Harvestcraft IDs in 1.10.2j are just lowercased.  So `___Item` becomes `___item`.

**Comment by primetoxinz** [comment]
yep, that would cause the bug right there. crafttweaker is probably the best bet.

**Comment by WesCook** [comment]
Alright, here's the integration written as a CraftTweaker's script.  Anyone is free to use it.

```
// Mill
mods.betterwithmods.Mill.add(<harvestcraft:cornmealitem>, null, [<harvestcraft:cornitem>]);
mods.betterwithmods.Mill.add(<harvestcraft:blackpepperitem>, null, [<harvestcraft:peppercornitem>]);
mods.betterwithmods.Mill.add(<harvestcraft:cocoapowderitem>, null, [<minecraft:dye:3>]);
mods.betterwithmods.Mill.add(<harvestcraft:groundcinnamonitem>, null, [<harvestcraft:cinnamonitem>]);
mods.betterwithmods.Mill.add(<harvestcraft:groundnutmegitem>, null, [<harvestcraft:nutmegitem>]);
mods.betterwithmods.Mill.add(<harvestcraft:currypowderitem>, null, [<harvestcraft:curryleafitem>]);

// Cauldron
mods.betterwithmods.Cauldron.add(<harvestcraft:boiledeggitem>, null, [<minecraft:egg>]);
mods.betterwithmods.Cauldron.add(<minecraft:bread>, null, [<ore:foodDough>]);

// Ore Dictionary
<ore:foodDonut>.add(<betterwithmods:donut>);

// Recipes
recipes.addShapeless(<betterwithmods:chocolate> * 2, [<ore:foodCocoapowder>, <ore:listAllmilk>, <minecraft:sugar>, <ore:toolSaucepan>]);
```

**Comment by MatthiasMann** [comment]
Still - I think it would be best if BWM checks if items are available before adding the recipe - to prevent an NPE later one.

**Comment by primetoxinz** [comment]
That's a lot of worth to do in a version that is only in support mode, not to mention mod authors rarely change item names in the middle of a version; Pam made a mistake doing that.

**Comment by TomberWolf** [comment]
Still no fix for this?

**Comment by DaedalusGame** [comment]
There's a crafttweaker script

**Comment by TomberWolf** [comment]
That's a workaround, not a fix.

**Comment by primetoxinz** [comment]
1.10.2 is no longer support @TomberWolf

**Comment by TomberWolf** [comment]
You're kidding?

**Comment by primetoxinz** [comment]
No, I'm not.

**Comment by TomberWolf** [comment]
So, 1.10.2 ist the most used version besides 1.7.10 and BWM doesn't support it anymore?
At least bugfixes?

**Comment by primetoxinz** [comment]
You can easily fix the issue with a simple config option and a crafttweaker script, sorry not all of us have time to support 3 different mod versions. Especially a code base as ancient as 1.10.2 in terms of this mod.

**Comment by BeetoGuy** [comment]
Especially at the point in time where we're discussing plans on how to expand the mod going forward. A lot has changed between the 1.10.2 and 1.11.2 versions, so I'd suggest looking into seeing if your modpack would be able to be updated to it.
