### ISSUE TITLE
HCPiles only drops piles the first time when broken on server

### ISSUE THREAD

**Issue by SwordShaman** [BeetoGuy/BetterWithMods#395]
While testing my multiplayer server and having HCPiles = true on both client and server configs, resulting piles of dirt/gravel are only obtained the first time on breaking said block.  Further digging of the same type of block only causes the block to be destroyed without dropping piles.  I haven't experience this issue on singleplayer.

**Comment by primetoxinz** [comment]
Interesting that it only happens on a server. Pretty sure I know the issue, no clue why it wouldn't happen on  single player
