### ISSUE TITLE
Crashing Incompatability

### ISSUE THREAD

**Issue by purestone9** [BeetoGuy/BetterWithMods#401]
When I use a Turntable from Better With Mods to rotate a block from Terraqueous it crashed my game. Both in single player and on servers as well.

**Comment by primetoxinz** [comment]
You're going to have to give me the crash report

**Comment by purestone9** [comment]
[crash-2017-06-04_13.50.02-server.txt](https://github.com/BeetoGuy/BetterWithMods/files/1050670/crash-2017-06-04_13.50.02-server.txt)

**Comment by kreezxil** [comment]
Here is the real server-side crash report to accompany the above client crash report: 

https://gist.github.com/anonymous/d7f2fbd8535cd00bcf2b442da9dc99b2

**Comment by primetoxinz** [comment]
This is not something I can fix on my end. It has to be fixed in Terraqueous.

**Comment by kreezxil** [comment]
Dratz Sheti just posted on the version we posted to him what the problem was and how you can fix it.

https://github.com/ShetiPhian/Localizations-and-Issues/issues/81

**Comment by primetoxinz** [comment]
no, I said that if you'd read the name

**Comment by kreezxil** [comment]
my deepest apologies, bug reports are link strong meade to me
