### ISSUE TITLE
[1.10.2] Anvil recipes don't support transforms?

### ISSUE THREAD

**Issue by Claycorp** [BeetoGuy/BetterWithMods#402]
Script: ``mods.betterwithmods.SteelAnvil.addShaped(<immersiveengineering:material:20>,   
[[<immersiveengineering:material:30>, <immersiveengineering:material:30>,
 <immersiveengineering:tool:0>.anyDamage().transformDamage(1), null], 
[null,null,null,null],  
[null,null,null,null],  
[null,null,null,null]]);  
``
Result: Nothing. No error, No recipe.
MT log: https://gist.github.com/Claycorp/7502898fbf261acee1bcb62c9c9a9f79

``mods.betterwithmods.SteelAnvil.addShapeless(<immersiveengineering:material:20>, 
[<immersiveengineering:material:30>, <immersiveengineering:material:30>, <immersiveengineering:tool:0>.anyDamage().transformDamage(1)]);
``
I also tried shapeless and it gives: https://pastebin.com/zV90V1JB

**Comment by primetoxinz** [comment]
Will be fixed in 1.11.2, might get back ported as it's a simple fix.
