### ISSUE TITLE
[1.11 suggestion] Add a registry for blocks usable in the kiln

### ISSUE THREAD

**Issue by KnightMiner** [BeetoGuy/BetterWithMods#403]
I make a mod called Ceramics, and it would be nice if my clay brick types could be used to make a kiln. Its a pretty minor feature, but something I think would be pretty cool to have if it is not too much of an issue to make it support other bricks.

If this can be handled with IMC/a config option it would be especially great to reduce build dependencies.

**Comment by primetoxinz** [comment]
The only issue with adding other blocks to the kiln is the base block is turned into a BlockKiln

**Comment by KnightMiner** [comment]
How does BlockKiln do the rendering currently? I noticed it supported three different blocks, one of which is from another mod.

**Comment by primetoxinz** [comment]
It's just a normal block state model but I'm willing to make it a custom bake to support blocks

**Comment by KnightMiner** [comment]
All my bricks use a static model (it is randomized, but that is not a big deal), so that would work if its simple enough to do.

**Comment by primetoxinz** [comment]
I'll look into it some time tomorrow

**Comment by primetoxinz** [comment]
You should now be able to send an imc message with key 'registerKilnBlock' and an ItemStack for the block

**Comment by primetoxinz** [comment]
Having issues get the TileCamo to keep the blockstate in nbt and I'm entirely unsure why

**Comment by KnightMiner** [comment]
I think it might be because you forgot to call `super` on the read from and write to NBT methods, so when loading the game it is missing the location data and likely ignored.

**Comment by primetoxinz** [comment]
Should be fixed

**Comment by KnightMiner** [comment]
Yep, the latest build has the NBT saving and loading for me. Thanks for adding this feature! [And here is a screenshot of the feature working with my bricks](http://i.imgur.com/Pp1s382.png)

**Comment by primetoxinz** [comment]
Great! Looks awesome!
