### ISSUE TITLE
Add more foods.

### ISSUE THREAD

**Issue by primetoxinz** [BeetoGuy/BetterWithMods#424]
Apple Pie

Rustic Food Values:
Grape 3/6

**Comment by abculatter2** [comment]
Recipe for Rabbit Stew

Maybe add something that uses Chorus Fruit?

**Comment by primetoxinz** [comment]
Remove bread from cauldron, kiln only

**Comment by DaedalusGame** [comment]
![apple pies](http://i.imgur.com/DUvcFvQ.png)
[pick any one you like](http://imgur.com/a/FvvqV)
