### ISSUE TITLE
[1.11.2] Soul Forged Steel recipe asks for a different Charcoal meta than what you can produce.

### ISSUE THREAD

**Issue by Rosethorns** [BeetoGuy/BetterWithMods#430]
The current Soul Forged Steel recipe asks for Charcoal Dust betterwithmods:material:18

However milling produces betterwithmods:material:39

This causes Soul Forged Steel to be un-producable

**Comment by primetoxinz** [comment]
SFS uses Coal Dust, not Charcoal Dust

**Comment by Rosethorns** [comment]
oh... oh. I'm an idiot. Sorry!
