### ISSUE TITLE
[1.2.25-1.11.2] Saw Issue

### ISSUE THREAD

**Issue by kreezxil** [BeetoGuy/BetterWithMods#431]
With only your mod and jei installed using forge 13.20.0.2315, when place a spruce wood siding in front of the blade the return is oak wood moulding.

Just tested it with all of the wood sidings in standard vanilla and they all return an oak wood moulding.

**Comment by kreezxil** [comment]
![Video Bug Reporting](https://www.youtube.com/watch?v=nR0dmZzBYCg)

**Comment by primetoxinz** [comment]
Yes, fix in dev. Will release in a bit.
