### ISSUE TITLE
[Feature Request] Neither 1 nugget per ore nor 9 feels balanced; 3 maybe?

### ISSUE THREAD

**Issue by WazWaz** [BeetoGuy/BetterWithMods#432]
I tried playing with with now-default 1 nugget per ore. I gave up and switched it off, but definitely one whole ingot per ore quickly floods you with ore. If the number made was adjustable, I expect 3 would have kept me playing full hardcore. 1 nugget isn't enough to keep you in pickaxes if you strip-mine, let alone advancing on other items. 1 is a good setting if you want to force exploration for caverns. It might also be okay if BwM is the only mod, but even just with BwA and Rustic I felt starved for iron.

**Comment by primetoxinz** [comment]
If you are on 1.11.2 there is a config for this exact thing in HCOre and KilnOres separately, 1.10.2 is not receiving any new features.

**Comment by WazWaz** [comment]
I am on 1.11.2, but can't see anything like this in the cfg (or the source code). I can see that I can choose either 1 nugget or 1 ingot, but nothing in between such as 3 nuggets.

**Comment by primetoxinz** [comment]
HCOres > Ore Production Count and KilnOres > Ore Production Count
