### ISSUE TITLE
Recipe Issues and Tweaks

### ISSUE THREAD

**Issue by abculatter2** [BeetoGuy/BetterWithMods#435]
First off, the amount of time that is required to make a windmill with the handcrank is ridiculous. With default config options, it takes a minimum of 45 minutes of staring at the crank right-clicking to grind enough hemp to make a windmill. Comparatively, in BTW, it only takes a minimum of 9 minutes.

Also, wheat cannot be ground into flour, and debarked logs produce two charcoal if cooked in a furnace. (Not sure if that last one is intentional?)

It would also be nice if you could add self-dropping saw recipes for grass and flowers, for automation.

**Comment by primetoxinz** [comment]
There are issues with how the handcrank is implemented currently that I need to think about how to fix. All the rest is fixed.
