### ISSUE TITLE
Request: Gearbox Breakage Disabled?

### ISSUE THREAD

**Issue by Darkosto** [BeetoGuy/BetterWithMods#447]
Hello!

Is it possible to add a config option to disable gearboxes breaking when overpowered? 

MC: 1.11.2
BWM: 1.2.27
Forge: 2315

Thank you very much for your time!
Darkosto

**Comment by DaedalusGame** [comment]
That feature already exists tho. It's called a wind chime.

**Comment by Darkosto** [comment]
Interesting. Is this information available from within the mod, too?

**Comment by DaedalusGame** [comment]
I don't think so and I'm not sure how it could be done. The name is kind of a good indicator already?
Maybe the recipe could use a redstone latch instead to indicate that it will emit redstone in a storm?

Oh yeah, for the same purpose you can also use a Detector Block facing upward. But the wind chime is a better choice because it's not SFS-tier.

**Comment by Darkosto** [comment]
Honestly, I appreciate your suggestions but I don't see how those would clearly indicate to a player that a wind chime would stop a gearbox from breaking. Typically, a wind chime would be viewed as a decorative item and not a functional item unless it had a tooltip associated with it. I think a recipe is not always indicative of what something can do, especially in this particular instance due to the nature of what a wind chimes purpose is. 

I think a tooltip would be the best bet to explain the functionality.

**Comment by primetoxinz** [comment]
I agree that giving more information for these types of things is desperately needed. I intend to make an ingame manual of sorts soon, probably for the large changes that will likely come with the 1.12 version. I will try to put tooltips on things for now

**Comment by primetoxinz** [comment]
Add more info to a bunch of blocks in next release.
