### ISSUE TITLE
Unable to disable soulforged steel recipe through minetweaker

### ISSUE THREAD

**Issue by joegman** [BeetoGuy/BetterWithMods#448]
Minecraft Version: 1.11.2
BWM Version: 1.2.27
Crafttweaker Version: 3.0.26
MTLib Version: 2.0.3

This code:
`mods.betterwithmods.StokedCrucible.remove(soulforged_steel, [<ore:dustCarbon>, <betterwithmods:urn:8>, <ore:ingotIron>]);`
Doesn't remove the recipe, but moves the recipe to the end of the JEI pages - as if it is re adding it.

This code:
`mods.betterwithmods.StokedCrucible.remove(soulforged_steel);`
Removes all of the recipes except for the main one

Note I have harder steel recipe turned off,
I also have MTLib installed

**Comment by primetoxinz** [comment]
This is fixed in the next version by adding a more specific remove method like so
`@ZenMethod
    public static void remove(IItemStack output, @Optional IItemStack secondary, @NotNull IIngredient[] inputs) {
        MineTweakerAPI.apply(new BulkRemove(StokedCrucibleRecipeCategory.UID, StokedCrucibleManager.getInstance(), InputHelper.toStack(output), InputHelper.toStack(secondary), InputHelper.toObjects(inputs)));
    }`
