### ISSUE TITLE
Crash ItemStack BetterWithMods unplayable [1.10.2] [Modpack Forever Stranded 1.9.0]

### ISSUE THREAD

**Issue by Kenshij** [BeetoGuy/BetterWithMods#453]
In the new Version1.9.0 of the Modpack after update mods, BetterWithMods is unplayable, all inventories crash the game when putting an item in which is prozessed. 
Can be teste with fresh install of Forever Stranded, start new map, place Handcrank and Millstone, put hemp in Millstone and run Handcrank -> crash

Crashlog:
[https://pastebin.com/Rp3JzC2B](url)

```
java.lang.NullPointerException: Ticking block entity
    at net.minecraft.item.ItemStack.func_77952_i(ItemStack.java:245)
    at betterwithmods.craft.bulk.CraftingManagerBulk.containsIngredient(CraftingManagerBulk.java:185)
```
Alot mods hade this problem from time to time and fixed it but no one shows how >_>. Have read a little best answer is other mods register null Items so Itemstack crashes internal.

Have look into your code, why you convert obj 3 times to Itemstack instead of only one at the beginning of the if ? 

```
184            if (obj instanceof ItemStack) {
->185                if (ItemStack.areItemsEqual((ItemStack) obj, stack) || (((ItemStack) obj).getItemDamage() == OreDictionary.WILDCARD_VALUE && stack.getItem() == ((ItemStack) obj).getItem())) {
186                    return !((ItemStack) obj).hasTagCompound() || ItemStack.areItemStackTagsEqual(stack, (ItemStack) obj);
} 
```

getItemDamage() or getItem() crashes in Itemstack class, can you try catch ist so the server not crash

Edit:
have search further : ItemStack.java:245 ist the getItemDamage() function
have read in bucket forum [https://bukkit.org/threads/player-kicked-when-using-command.46933/](url) a very similar problem with null and the same crash with CraftItemStack class and solve with the test .getItemInHand().getTypeId() == 0 befor do something with it.

A solution can be to check the `stack.getItem() == ((ItemStack) obj).getItem())` first and then check the `((ItemStack) obj).getItemDamage() == OreDictionary.WILDCARD_VALUE` so null and buggy items are filtered out befor using getItemDamage wich failed on them.

**Comment by DaedalusGame** [comment]
Disable harvestcraft compatibility in the config

**Comment by Kenshij** [comment]
Its not only the mill and hemp was an example, i can put leather in the mill and have the same effect. I can put items in the cauldron and have the same effect. But will try it out and edit this post.
