### ISSUE TITLE
Water puddles sometimes don't fully decay

### ISSUE THREAD

**Issue by enzyme-a113-2** [BeetoGuy/BetterWithMods#456]
Occasionally, water puddles won't decay when placed down with a bucket (with Hardcore Buckets enabled). This is a bit tricky to reproduce, but occasionally happens when putting water on slopes. This can be reproduced by going into survival, filling a bucket and clicking the corner of a slope. Occasionally the "puddle" blocks will stick around. Reloading the world (SSP) removes the temporary water, but I haven't tried with a server. This happens using version 1.2.28-1.11.2.

[demonstration.zip](https://github.com/BeetoGuy/BetterWithMods/files/1083927/demonstration.zip)

**Comment by primetoxinz** [comment]
Finally took a look at this, not much we can do as it's just vanilla water

**Comment by enzyme-a113-2** [comment]
Surely there isn't anything you could do? It's not exactly a major bug, but it's pretty annoying when you know it exists.
