### ISSUE TITLE
crash with ImmersiveEngineering

### ISSUE THREAD

**Issue by Hypsellis** [BeetoGuy/BetterWithMods#458]
Better With Mods crashes with Immersive Engineering https://pastebin.com/H32sGw8c

**Comment by drakray** [comment]
[Same](https://pastebin.com/MyaZV2fv)

**Comment by primetoxinz** [comment]
Give this a try for me, might fix it. https://github.com/BeetoGuy/BetterWithMods/releases/tag/1.2.30

**Comment by drakray** [comment]
.30 seams to work fine(no crash on load)

**Comment by primetoxinz** [comment]
Cool, I'll release it then.
