### ISSUE TITLE
Fix Endermen (or all mob) boat cheese

### ISSUE THREAD

**Issue by primetoxinz** [BeetoGuy/BetterWithMods#463]

**Comment by DaedalusGame** [comment]
is this really a problem?

**Comment by primetoxinz** [comment]
it's really broken, no effort to kill them

**Comment by DaedalusGame** [comment]
maybe i'm misunderstanding, is it that you put your boat in water or a boat on land and they won't be able to attack you?

**Comment by primetoxinz** [comment]
any boat, as long as the enderman touches it it cannot move. I simply want to add an AI to make it dismount if it's trying to attack you

**Comment by DaedalusGame** [comment]
ah ok, yeah that sounds pretty reasonable.

**Comment by Joxxs** [comment]
Releasing the krakens (squids) could help with boat issue as well more so at night than during day though.
