### ISSUE TITLE
Crash while cutting down trees.

### ISSUE THREAD

**Issue by Alpha866** [BeetoGuy/BetterWithMods#464]
The game crashes every time I try to cut down a tree. It will insert a new log into the spot I just cleared a couple times and then when it finally breaks for good the game crashes.
I have a fresh install of 1.11.2 with no other mods installed. I have tried it on multiple new worlds with the same affect.
Thank you.

**Comment by primetoxinz** [comment]
I need a crash log

**Comment by Alpha866** [comment]
I increased the amount of ram it can use from 1 gig to 4 and that seems to have solved the problem. I will post a crash log if it happens again.

**Comment by Alpha866** [comment]
It just did it again. Here's the crash report.
[crash-2017-06-26_13.24.34-server.txt](https://github.com/BeetoGuy/BetterWithMods/files/1103410/crash-2017-06-26_13.24.34-server.txt)

**Comment by primetoxinz** [comment]
Nothing to do with ram usage, hopefully fixed in next version though.
