### ISSUE TITLE
[Issue] Axles always always placing upwards

### ISSUE THREAD

**Issue by Vajrapo** [BeetoGuy/BetterWithMods#467]
active mods:
animania 1.2, BiblioCraft 2.3.2, gravestone 1.6.6, level-up-mod, Pam's harvestcraft 1.11.2h, tconstruct 2.7.0.26, ToughAsNails 2.1.0.51, Forge 13.20.0.2315, OptiFine HD_U_C1

I am no more able to place axles the desired ways.

Any ideas?

**Comment by bookerthegeek** [comment]
## Heyo ##
Also having this issue. Axel's were placed against the GearBox's while standing on the Laips block. Interestingly enough, the Treated Axel will place correctly but do not work.

![Proof](https://i.imgur.com/NlC19pU.png)
---
### Versions ###
- Better With Mods-1.2.35-1.11.2
- Forge-1.11.2-13.20.1.2388-universal.jar
- [Complete List](https://gist.github.com/bookerthegeek/60a1f006486131a091013dbd02a7480f)

**Comment by DaedalusGame** [comment]
this is a duplicate of #466 
seems this is fixed in dev already.
treated axles can be placed on the inputs of IE kinetic generators to generate RF from the BWM mechanical system.

**Comment by Vajrapo** [comment]
it is a dublicate of #466 idd but it's clearly not fixed (-> still havin' the issue, no capability to flip the axles around) nor is there any comment stating any fix.

**Comment by DaedalusGame** [comment]
[except here, of course](https://github.com/BeetoGuy/BetterWithMods/commit/f5191a25f46433407cdaa28840334e07aee0ba83)

**Comment by Vajrapo** [comment]
true :). Didn't see this one. So lets w8 for the official submit :).
