### ISSUE TITLE
filtered hopper not filtering

### ISSUE THREAD

**Issue by Mailleweaver** [BeetoGuy/BetterWithMods#468]
It appears that filtered hoppers are broken in 1.2.35.

In a system that was working in version 1.2.27, I'm unable to get any hellfire dust or a soul urn from it. It just spits out the ground netherrack in batches of 8. It is powered, has an urn beneath, and has a soul sand in the filter slot, of course.

I've tried breaking and replacing it, breaking and replacing the urn below, removing and replacing the soul sand, and filling it with a few stacks of ground netherrack while it was unpowered and then powering it.

**Comment by primetoxinz** [comment]
I'll take a look

**Comment by primetoxinz** [comment]
can I have some pictures of the setup? It works fine on my end

**Comment by primetoxinz** [comment]
You are _physically_ throwing the ground netherrack on the hopper in entity form and not putting it in the _inventory_?

**Comment by Mailleweaver** [comment]
Yes, I put it in the inventory. That's what worked before and is most intuitive for non-automated systems as that is the way vanilla hoppers work. Apparently it does work to throw stuff on top.

**Comment by primetoxinz** [comment]
No, the inventory should have never worked before, even if it did for some reason it was unintentional. You can easily automate it the way it should be.

**Comment by Mailleweaver** [comment]
Then perhaps the inventory slots should be made to be output-only (like the far right slot in furnaces) to prevent confusion.

**Comment by primetoxinz** [comment]
No thanks, you're the first person to ever get confused considering the JEI handler literally says "Throw"
