### ISSUE TITLE
[Improvement] Destroyed gearbox drops configurable

### ISSUE THREAD

**Issue by braeven** [BeetoGuy/BetterWithMods#47]
Currently when a gearbox is destroyed by the weather, it's dropping hardcoded materials in form of: gold nuggets, gears, sawdust and wooden gears.
Since I changed the recipe for the gearbox using crafttweaker, in my recipe there is no gold involved in crafting a gearbox(since gold will become avaible later in my modpack). So currently, it would create a way to get a material that should not be avaible.

My suggestion would be to change the event of a gearbox being destroyed to check the recipe for the gearbox and drop randomly 1-9 involved items instead of the hardcoded ones.

If this is not possible, please add a config-option to disable drops from a destroyed gearbox.

Also a config option to give gearboxes a chance of beeing destroyed by the weather would be nice. Like a chance of 1/100 per second, that a gearbox will break instead of always breaking.

**Comment by MRebhan** [comment]
Maybe add it as a MineTweaker integration thing so you can change the drops completely? Let's see what Beeto thinks.

**Comment by BeetoGuy** [comment]
Out of town at the moment, so I can't really do any extended comments on it, but making it tweakable might be best.
