### ISSUE TITLE
Mod logs not working in saws?

### ISSUE THREAD

**Issue by primetoxinz** [BeetoGuy/BetterWithMods#471]

**Comment by Rosethorns** [comment]
Can confirm this issue. It appears along with the Hardcore Lumber fix, basic mod compat was lost for mod woods.

Currently in my instance any forestry log can be crafted normally into 4 planks.
drops a log when punched.
does not have a crafting grid axe recipe.
And does not interact with the saw in any way.

If one cannot HCLumber cannot be had with mod compat automatically, a craft tweaker recipe that adds a log to all of the above behavior would be an ideal alternative.

**Comment by BeetoGuy** [comment]
Looks like it's firing on preInit, causing it to miss pretty much everything.
