### ISSUE TITLE
Weird crash while using mill stone

### ISSUE THREAD

**Issue by Williamhb** [BeetoGuy/BetterWithMods#472]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CoreMod (Aroma1997Core-1.9.4-1.1.1.2.jar)
  TANLoadingPlugin (ToughAsNails-1.9.4-1.1.1.21-universal.jar)
  CTMCorePlugin (CTM-MC1.10.2-0.1.1.16.jar)
  FMLPlugin (InventoryTweaks-1.62-dev-66.jar)
  LoadingPlugin (ResourceLoader-MC1.9.4-1.5.1.jar)
  AppleCore (AppleCore-mc1.10.2-2.2.0.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.66-beta.jar)
Contact their authors BEFORE contacting forge

// You should try our sister game, Minceraft!

Time: 7/7/17 6:33 PM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at net.minecraft.item.ItemStack.func_77952_i(ItemStack.java:245)
	at betterwithmods.craft.bulk.CraftingManagerBulk.containsIngredient(CraftingManagerBulk.java:185)
	at betterwithmods.craft.bulk.CraftingManagerBulk.getValidRecipes(CraftingManagerBulk.java:164)
	at betterwithmods.craft.bulk.CraftingManagerBulk.getMostValidRecipe(CraftingManagerBulk.java:145)
	at betterwithmods.craft.bulk.CraftingManagerBulk.getValidCraftingIngredients(CraftingManagerBulk.java:197)
	at betterwithmods.blocks.tile.TileEntityMill.validateContents(TileEntityMill.java:221)
	at betterwithmods.blocks.tile.TileEntityMill.func_73660_a(TileEntityMill.java:75)
	at net.minecraft.world.World.func_72939_s(World.java:1804)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.item.ItemStack.func_77952_i(ItemStack.java:245)
	at betterwithmods.craft.bulk.CraftingManagerBulk.containsIngredient(CraftingManagerBulk.java:185)
	at betterwithmods.craft.bulk.CraftingManagerBulk.getValidRecipes(CraftingManagerBulk.java:164)
	at betterwithmods.craft.bulk.CraftingManagerBulk.getMostValidRecipe(CraftingManagerBulk.java:145)
	at betterwithmods.craft.bulk.CraftingManagerBulk.getValidCraftingIngredients(CraftingManagerBulk.java:197)
	at betterwithmods.blocks.tile.TileEntityMill.validateContents(TileEntityMill.java:221)
	at betterwithmods.blocks.tile.TileEntityMill.func_73660_a(TileEntityMill.java:75)

-- Block entity being ticked --
Details:
	Name: bwm_millstone // betterwithmods.blocks.tile.TileEntityMill
	Block type: ID #516 (tile.bwm:single_machine // betterwithmods.blocks.BlockMechMachines)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-615,64,-312), Chunk: (at 9,4,8 in -39,-20; contains blocks -624,0,-320 to -609,255,-305), Region: (-2,-1; contains chunks -64,-32 to -33,-1, blocks -1024,0,-512 to -513,255,-1)
	Actual block type: ID #516 (tile.bwm:single_machine // betterwithmods.blocks.BlockMechMachines)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1804)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)

-- Affected level --
Details:
	Level name: New World
	All players: 1 total; [EntityPlayerMP['w1liam'/219, l='New World', x=-612.00, y=64.00, z=-312.46]]
	Chunk stats: ServerChunkCache: 1960 Drop: 0
	Level seed: -5503546991410462096
	Level generator: ID 09 - RTG, ver 0. Features enabled: true
	Level generator options: rtg
	Level spawn location: World: (-35,64,-40), Chunk: (at 13,4,8 in -3,-3; contains blocks -48,0,-48 to -33,255,-33), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 248068 game time, 92207 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 108001 (now: false), thunder time: 97582 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1183930592 bytes (1129 MB) / 3517530112 bytes (3354 MB) up to 8520204288 bytes (8125 MB)
	JVM Flags: 18 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8192m -Xms256m -XX:PermSize=256m -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:MaxTenuringThreshold=15 -XX:MaxGCPauseMillis=30 -XX:-UseGCOverheadLimit -XX:+UseBiasedLocking -XX:SurvivorRatio=8 -XX:TargetSurvivorRatio=90 -XX:+UseCompressedOops -XX:+OptimizeStringConcat -XX:+AggressiveOpts -XX:ReservedCodeCacheSize=2048m -XX:+UseCodeCacheFlushing -XX:SoftRefLRUPolicyMSPerMB=20000
	IntCache: cache: 0, tcache: 0, allocated: 9, tallocated: 61
	FML: MCP 9.32 Powered by Forge 12.18.3.2316 69 mods loaded, 69 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2316.jar) 
	UCHIJAAAA	Forge{12.18.3.2316} [Minecraft Forge] (forge-1.10.2-12.18.3.2316.jar) 
	UCHIJAAAA	Aroma1997Core{${version}} [Aroma1997Core] (Aroma1997Core-1.9.4-1.1.1.2.jar) 
	UCHIJAAAA	animania{1.2} [Animania] (animania-1.10.2-1.2.jar) 
	UCHIJAAAA	JEI{3.14.7.420} [Just Enough Items] (jei_1.10.2-3.14.7.420.jar) 
	UCHIJAAAA	AppleCore{2.2.0} [AppleCore] (AppleCore-mc1.10.2-2.2.0.jar) 
	UCHIJAAAA	appleskin{1.0.7} [AppleSkin] (AppleSkin-mc1.10.2-1.0.7.jar) 
	UCHIJAAAA	Aroma1997CoreHelper{1.1.1.2} [Aroma1997Core|Helper] (Aroma1997Core-1.9.4-1.1.1.2.jar) 
	UCHIJAAAA	AromaBackup{2.0.0.0.b62} [AromaBackup] (AromaBackup-1.9.4-2.0.0.0.b62.jar) 
	UCHIJAAAA	AromaBackupRecovery{1.0} [AromaBackup Recovery] (AromaBackup-1.9.4-2.0.0.0.b62.jar) 
	UCHIJAAAA	Baubles{1.3.11} [Baubles] (Baubles-1.10.2-1.3.11.jar) 
	UCHIJAAAA	mantle{1.10.2-1.1.5.205} [Mantle] (Mantle-1.10.2-1.1.5.jar) 
	UCHIJAAAA	tconstruct{1.10.2-2.6.5.10} [Tinkers' Construct] (TConstruct-1.10.2-2.6.5.jar) 
	UCHIJAAAA	immersiveengineering{0.10-61} [Immersive Engineering] (ImmersiveEngineering-0.10-61.jar) 
	UCHIJAAAA	natura{1.10.2-4.1.0.73} [Natura] (natura-1.10.2-4.1.0.73.jar) 
	UCHIJAAAA	betterwithmods{0.14.24 Beta} [Better With Mods] (Better With Mods-0.14.24-1.10.2.jar) 
	UCHIJAAAA	BiblioCraft{2.2.4} [BiblioCraft] (BiblioCraft[v2.2.4][MC1.10.2].jar) 
	UCHIJAAAA	BiomesOPlenty{5.0.0.2236} [Biomes O' Plenty] (BiomesOPlenty-1.10.2-5.0.0.2236-universal.jar) 
	UCHIJAAAA	Botania{r1.9-341} [Botania] (Botania r1.9-341.jar) 
	UCHIJAAAA	Chameleon{1.10.2-2.3.0} [Chameleon] (Chameleon-1.10.2-2.3.0.jar) 
	UCHIJAAAA	ChestTransporter{2.5.17} [Chest Transporter] (ChestTransporter-1.10.2-2.5.17.jar) 
	UCHIJAAAA	chisel{MC1.10.2-0.0.11.26} [Chisel] (Chisel-MC1.10.2-0.0.11.26.jar) 
	UCHIJAAAA	extendedrenderer{v1.0} [Extended Renderer] (coroutil-1.10.2-1.1.18.jar) 
	UCHIJAAAA	coroutil{1.10.2-1.1.18} [CoroUtil Library] (coroutil-1.10.2-1.1.18.jar) 
	UCHIJAAAA	configmod{v1.0} [Extended Mod Config] (coroutil-1.10.2-1.1.18.jar) 
	UCHIJAAAA	crafttweakerjei{1.0.1} [CraftTweaker JEI Support] (CraftTweaker-1.10.2-3.0.26.jar) 
	UCHIJAAAA	MineTweaker3{3.0.26} [MineTweaker 3] (CraftTweaker-1.10.2-3.0.26.jar) 
	UCHIJAAAA	ctgui{1.0.0} [CT-GUI] (CraftTweaker-1.10.2-3.0.26.jar) 
	UCHIJAAAA	ctm{MC1.10.2-0.1.1.16} [CTM] (CTM-MC1.10.2-0.1.1.16.jar) 
	UCHIJAAAA	custommainmenu{2.0.5} [Custom Main Menu] (CustomMainMenu-MC1.10.2-2.0.5.jar) 
	UCHIJAAAA	defaultworldgenerator-port{1.9.4-0.4} [Default World Generator] (DefaultWorldGenerator-port-1.9.4-0.4.jar) 
	UCHIJAAAA	endercore{1.10.2-0.4.1.66-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.66-beta.jar) 
	UCHIJAAAA	extrautils2{1.0} [Extra Utilities 2] (extrautils2-1.10.2-1.4.4.jar) 
	UCHIJAAAA	fastleafdecay{v11} [Fast Leaf Decay] (FastLeafDecay-v11.jar) 
	UCHIJAAAA	forestry{5.2.17.377} [Forestry] (forestry_1.10.2-5.2.17.377.jar) 
	UCHIJAAAA	gravestone{1.5.13} [Gravestone Mod] (gravestone-1.5.13.jar) 
	UCHIJAAAA	grimoireofgaia{1.5.6} [Grimoire of Gaia 3] (GrimoireOfGaia3-1.10.2-1.5.6.jar) 
	UCHIJAAAA	Waila{1.8.17-B31_1.10.2} [Waila] (Hwyla-1.8.17-B31_1.10.2.jar) 
	UCHIJAAAA	InfernalMobs{1.7.1} [Infernal Mobs] (InfernalMobs-1.10.jar) 
	UCHIJAAAA	inventorytweaks{1.62-dev-66-c082db3} [Inventory Tweaks] (InventoryTweaks-1.62-dev-66.jar) 
	UCHIJAAAA	ironbackpacks{1.10.2-2.2.27} [Iron Backpacks] (IronBackpacks-1.10.2-2.2.27.jar) 
	UCHIJAAAA	ironchest{1.10.2-7.0.15.804} [Iron Chest] (ironchest-1.10.2-7.0.15.804.jar) 
	UCHIJAAAA	journeymap{1.10.2-5.4.9b1} [JourneyMap] (journeymap-1.10.2-5.4.9b1.jar) 
	UCHIJAAAA	jeresources{0.5.9.3} [Just Enough Resources] (JustEnoughResources-1.10.2-0.5.9.3.jar) 
	UCHIJAAAA	levelup{${version}} [Level Up!] (LevelUp!-0.12.9-1.10.2.jar) 
	UCHIJAAAA	llor{1.1.1-mc[1.9-1.11]} [Light Level Overlay Reloaded] (LLOverlayReloaded-1.1.1-mc[1.9-1.11].jar) 
	UCHIJAAAA	nsa{1.0.0} [No Sleeping Allowed] (MC1.10.2 NoSleepingAllowed1.0.1.jar) 
	UCHIJAAAA	minecolonies{@VERSION@} [MineColonies] (minecolonies-universal-1.10.2-0.8.3056.jar) 
	UCHIJAAAA	mtrm{1.2.1.26} [MineTweakerRecipeMaker] (MineTweakerRecipeMaker-1.10.2-1.2.1.26.jar) 
	UCHIJAAAA	mtlib{@VERSION@} [MTLib] (MTLib-1.0.3.jar) 
	UCHIJAAAA	modtweaker{2.0.13} [Mod Tweaker] (ModTweaker2-2.0.13.jar) 
	UCHIJAAAA	railcraft{10.1.2} [Railcraft] (Railcraft_1.10.2-10.1.2.jar) 
	UCHIJAAAA	morebees{1.10.2-1.4.1.1} [More Bees] (morebees-1.10.2-1.4.1.1.jar) 
	UCHIJAAAA	mousetweaks{2.8} [Mouse Tweaks] (MouseTweaks-2.8-mc1.10.2.jar) 
	UCHIJAAAA	Neat{1.3-12} [Neat] (Neat 1.3-12.jar) 
	UCHIJAAAA	yurtmod{7.01} [Nomadic Tents] (NomadicTents[1.10.2]-7.01.jar) 
	UCHIJAAAA	harvestcraft{1.10.2j} [Pam's HarvestCraft] (Pam's HarvestCraft 1.10.2j.jar) 
	UCHIJAAAA	ResourceLoader{1.5.1} [Resource Loader] (ResourceLoader-MC1.9.4-1.5.1.jar) 
	UCHIJAAAA	roguelike{1.5.9} [Roguelike Dungeons] (RoguelikeDungeons-1.10.2-1.5.9.jar) 
	UCHIJAAAA	RTG{4.2.0.0-snapshot-4} [Realistic Terrain Generation] (RTG-1.10.2-4.2.0.0-snapshot-4.jar) 
	UCHIJAAAA	StorageDrawers{1.10.2-3.7.10} [Storage Drawers] (StorageDrawers-1.10.2-3.7.10.jar) 
	UCHIJAAAA	survivalistlighting{1.10.2-1.1} [Survivalist Lighting] (Survivalist Lighting-1.10.2-1.1.jar) 
	UCHIJAAAA	survivalist{1.10.1} [Survivalist] (Survivalist-1.10.2-1.10.1.jar) 
	UCHIJAAAA	ToughAsNails{1.1.1.21} [Tough As Nails] (ToughAsNails-1.9.4-1.1.1.21-universal.jar) 
	UCHIJAAAA	WailaHarvestability{1.1.10} [Waila Harvestability] (WailaHarvestability-mc1.10.2-1.1.10.jar) 
	UCHIJAAAA	wailaplugins{MC1.10.2-0.3.0-26} [WAILA Plugins] (WAILAPlugins-MC1.10.2-0.3.0-26.jar) 
	UCHIJAAAA	harvesttweaks{1.10.2-0.1.2.DEV.9651204} [Harvest Tweaks] (HarvestTweaks-1.10.2-0.1.2.jar) 
	UCHIJAAAA	hungeroverhaul{1.10.2-1.1.0.jenkins118} [Hunger Overhaul] (HungerOverhaul-1.10.2-1.1.0.jenkins118.jar) 
	Loaded coremods (and transformers): 
CoreMod (Aroma1997Core-1.9.4-1.1.1.2.jar)
  
TANLoadingPlugin (ToughAsNails-1.9.4-1.1.1.21-universal.jar)
  toughasnails.asm.transformer.BlockCropsTransformer
  toughasnails.asm.transformer.EntityRendererTransformer
  toughasnails.asm.transformer.WorldTransformer
CTMCorePlugin (CTM-MC1.10.2-0.1.1.16.jar)
  team.chisel.ctm.client.asm.CTMTransformer
FMLPlugin (InventoryTweaks-1.62-dev-66.jar)
  invtweaks.forge.asm.ContainerTransformer
LoadingPlugin (ResourceLoader-MC1.9.4-1.5.1.jar)
  lumien.resourceloader.asm.ClassTransformer
AppleCore (AppleCore-mc1.10.2-2.2.0.jar)
  squeek.applecore.asm.TransformerModuleHandler
EnderCorePlugin (EnderCore-1.10.2-0.4.1.66-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- WailaIntegration (Enabled/Not Forced)

	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaDecorative (Enabled/Not Forced)
		- NaturaTools (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)
		- WailaIntegration (Enabled/Not Forced)

	Pulsar/harvesttweaks loaded Pulses: 
		- blocks (Enabled/Forced)
		- items (Enabled/Forced)
		- tconstruct (Enabled/Forced)

	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['w1liam'/219, l='New World', x=-612.00, y=64.00, z=-312.46]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by DaedalusGame** [comment]
#388

**Comment by Williamhb** [comment]
ill try that thx so very much your the king :-D

**Comment by Williamhb** [comment]
Yup, That Fixed it.

Changing Pam's Harvestcraft Compability to False in the BWM cfg did the trick.

**Comment by DaedalusGame** [comment]
there's a compat minetweaker script if you really need it
