### ISSUE TITLE
Possible incompatability with Tech reborn

### ISSUE THREAD

**Issue by Matikari** [BeetoGuy/BetterWithMods#474]
I've posted the problem to Tech Reborn but bringing it to your attention as well. Something is causing us the inablilty to use tools to break their cable.

https://github.com/TechReborn/TechReborn/issues/1195

**Comment by DaedalusGame** [comment]
can you provide the bwm config perhaps

**Comment by grimkorlp** [comment]
Here is the config from the A Grim Life modpack.  1.10.2 pack.

[betterwithmods.zip](https://github.com/BeetoGuy/BetterWithMods/files/1136518/betterwithmods.zip)

**Comment by Matikari** [comment]
yes, but I also deleted the configs to regen at default and would still get a crash.

then I changed a few things myself, don't know what they were set at for the pack but here's mine after
I tried to change some stuff
[betterwithmods.txt](https://github.com/BeetoGuy/BetterWithMods/files/1136539/betterwithmods.txt)

**Comment by primetoxinz** [comment]
1.10.2 is not supported any longer
