### ISSUE TITLE
Incompatible with Tcon 2.5.0+

### ISSUE THREAD

**Issue by MechWarrior99** [BeetoGuy/BetterWithMods#48]
When using Tcon 2.5.0+, the game will crash. As stated in the 2.5.0 changelog for Tcon "This update comes with several internal restructures and WILL break compatibility with some other mods. The changes are easy to adapt to, however. This will be the only time this happens, but it'll take the other mod authors some days to update, so you might not be able to include this version directly into a modpack. Sorry for that, but it was much needed"
Just thought I would report this on the off chance that you didn't already know.

**Comment by BeetoGuy** [comment]
I think I've been using the latest version with the latest Tinkers without much problem, thanks to the reflection workaround. Regardless, I'll probably commit a proper switchover to the new API and see if everything's ready enough for a proper release.
