### ISSUE TITLE
Game crashes when clicking recipe book icon (1.12)

### ISSUE THREAD

**Issue by enzyme-a113-2** [BeetoGuy/BetterWithMods#480]
Using only Better With Mods-1.3.2-1.12.jar and 1.12-forge1.12-14.21.1.2387
[crash-2017-07-15_17.03.30-client.txt](https://github.com/BeetoGuy/BetterWithMods/files/1150088/crash-2017-07-15_17.03.30-client.txt)

**Comment by BeetoGuy** [comment]
It's unfortunately a bug with vanilla. Forge has a workaround implemented as of 2403, so I'd recommend updating to that.
