### ISSUE TITLE
Turning off hardcore logs makes it impossible to get tanned leather

### ISSUE THREAD

**Issue by SamGunGraven** [BeetoGuy/BetterWithMods#481]
If you turn off the ability to get Bark by punching trees - the only source of bark is using the saw, but the saw requires tanned leather to make - catch 22, tanned leather is impossible

**Comment by DaedalusGame** [comment]
Right-click with any axe on a log

**Comment by BeetoGuy** [comment]
I think the axe thing is no longer possible in 1.12, so dung is pretty much the way to go.

**Comment by Mailleweaver** [comment]
With mods like Animania and Wolf Armor, though, there's no way to get dung since vanilla animals don't spawn. Debarking logs with an axe was the only way to get into Better With Mods in the pack that I play with, and now that it's been removed Better With Mods is useless.

**Comment by BeetoGuy** [comment]
Yeah, I see your point. I really like debarked logs as an aesthetic option, so I'll look into restoring functionality with an addon.

**Comment by BeetoGuy** [comment]
Addon's done, or at least, the barebones version of it is. You can find it [here.](https://minecraft.curseforge.com/projects/debarked-logs)

**Comment by KnightMiner** [comment]
Any reason they were removed from Better With Mods?

**Comment by BeetoGuy** [comment]
I think it was due to redundancy, and prime has noted that it would be a bit difficult to provide support more mods with debarked variants of their own. I think the addon might be the best approach for it.
