### ISSUE TITLE
Ghasts spawned from soul urns occasionally get stuck in blocks

### ISSUE THREAD

**Issue by enzyme-a113-2** [BeetoGuy/BetterWithMods#482]
When chucking a soul urn at a vertical surface, or in a tiny hole, for example, the ghast will be spawned in the hole and will suffocate (making it trivially easy to farm ghast tears). In the original mod, the ghast is spawned far away from any blocks so it never suffocates).

**Comment by primetoxinz** [comment]
Hopefully improved.
