### ISSUE TITLE
Duplication glitch with Immersive engineering

### ISSUE THREAD

**Issue by enzyme-a113-2** [BeetoGuy/BetterWithMods#486]
When breaking IE multiblocks with a block dispenser, the multiblock drops 2 blocks (when it should drop one). It would be nice to fix this, or alternatively add a blacklist of what blocks can be safely broken / placed by block dispensers.

**Comment by DaedalusGame** [comment]
This may actually be an issue with Immersive Engineering, considering that this was a problem with Quark Endermen picking up multiblocks aswell...
