### ISSUE TITLE
[1.11.2] Cannot remove certain Cauldron recipes

### ISSUE THREAD

**Issue by isto2278** [BeetoGuy/BetterWithMods#490]
Hi =)

I have the following lines in scripts/Cauldron.zs:

    mods.betterwithmods.Cauldron.remove(<betterwithmods:chocolate>);
    mods.betterwithmods.Cauldron.remove(<betterwithmods:chowder>);

However, the recipes not only still appear in JEI but they actually work.
Let me know if you need further info like a mod list or if this is not BWM's fault. I thought it would be, since these are as far as I can tell the only recipes it won't remove (at least the only ones I stumbled upon) and I'd guess it's BWM's implementation of the CraftTweaker API?

Sorry if I'm wrong in these assumptions.

EDIT: I just tried to replicate the error in a new profile. The recipes still work when the two lines are the only content in the /scripts folder and the only mods installed are BWM, CraftTweaker and MTLib.

**Comment by BeetoGuy** [comment]
Looking at it, does `mods.betterwithmods.Cauldron.remove(<betterwithmods:chocolate> * 2);` work?

**Comment by isto2278** [comment]
Nope, the recipe still works.

**Comment by isto2278** [comment]
Thanks for the quick fix =D

I was waiting with closing the issue until it hit curseforge, any ETA for that? Just curious, this is obviously no big thing I'm holding my breath for.

Thanks anyway, you're doing great stuff with this mod, love it.

**Comment by primetoxinz** [comment]
I'll build it right now and put it on curse

**Comment by isto2278** [comment]
Wow thanks. I really appreciate it
