### ISSUE TITLE
[1.12] HCHunger bugs

### ISSUE THREAD

**Issue by DaedalusGame** [BeetoGuy/BetterWithMods#491]
possibly also affects 1.11 past the Apple Core integration.

Food seems to heal twice as much as shown with Apple Skin
Fat either doesn't render properly or partial fat doesn't exist
Exhaustion is harsher on lower difficulties than higher ones (11-13 jumps for one pixel on normal vs 25-28 jumps on hard)

**Comment by primetoxinz** [comment]
Mostly fixed, will look at the other stuff.
