### ISSUE TITLE
[1.11] HCStructures desert/jungle temples

### ISSUE THREAD

**Issue by vhd** [BeetoGuy/BetterWithMods#492]
If HCStructures are on, desert and jungle temples seems to not generating at all in 1.11.
In 1.10 it works fine. 
For easier testing i'm using http://mineatlas.com with minimal setup:
forge-1.11.2-13.20.1.2421
Better With Mods-1.2.38-1.11.2

**Comment by DaedalusGame** [comment]
There's a [mod](https://minecraft.curseforge.com/projects/magical-map?gameCategorySlug=mc-mods&projectID=261281) that adds a map for finding specific structures if you want to test it ingame.

**Comment by primetoxinz** [comment]
Yeah, I've definitely seen structures in 1.11.2 as well, no changes have to been made that would break it that I'm aware of

**Comment by vhd** [comment]
Just tested different versions:
1.2.30 broken
1.2.28 broken
1.2.27 works
1.2.25 works
1.2.23 works
1.2.20 works

**Comment by primetoxinz** [comment]
Fixed in latest, uploaded to curse
