### ISSUE TITLE
Injury debuffs do not take max health into account

### ISSUE THREAD

**Issue by Pyrofab** [BeetoGuy/BetterWithMods#493]
Currently, the mod assumes the player has 10 hearts when it inflicts health-related debuffs. However, some mods (or vanilla commands) modify the maximum amount of hearts a player has, which leads to annoyances like being crippled at all time. I suggest that instead of checking for a hardcoded health amount, you check for a fraction of the maximum health.

**Comment by primetoxinz** [comment]
I will do this, do you need it on 1.11.2 or is just 1.12 fine?

**Comment by Pyrofab** [comment]
1.12 is all I need :)

**Comment by primetoxinz** [comment]
cool :D

**Comment by primetoxinz** [comment]
If you need it know it's here http://ci.blamejared.com/job/BetterWithMods/19/
