### ISSUE TITLE
1.11.2 game crashes upon loading a new world

### ISSUE THREAD

**Issue by Armokthespideroverlord** [BeetoGuy/BetterWithMods#497]
for some reason I've been getting this crash whenever I load up a new world, this seems to only happen on forge versions newer then 2282. (I've messed around with the modpack by removing some of it's mods, which is how I figured out better with mods is to blame) ---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// I feel sad now :(

Time: 7/26/17 2:16 PM
Description: Ticking block entity

java.lang.NoSuchMethodError: net.minecraft.profiler.Profiler.startSection(Ljava/lang/Class;)V
	at net.minecraft.world.World.func_72939_s(World.java:1801)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1801)

-- Block entity being ticked --
Details:
	Name: minecraft:chest // net.minecraft.tileentity.TileEntityChest
	Block type: ID #54 (tile.chest // net.minecraft.block.BlockChest)
	Block data value: 3 / 0x3 / 0b0011
	Block location: World: (-352,35,355), Chunk: (at 0,2,3 in -22,22; contains blocks -352,0,352 to -337,255,367), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Actual block type: ID #54 (tile.chest // net.minecraft.block.BlockChest)
	Actual block data value: 3 / 0x3 / 0b0011
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1801)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621)

-- Affected level --
Details:
	Level name: New World
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 625 Drop: 0
	Level seed: -7505260993279932319
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-166,64,318), Chunk: (at 10,4,14 in -11,19; contains blocks -176,0,304 to -161,255,319), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 1 game time, 1 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 50508 (now: false), thunder time: 169324 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 662345928 bytes (631 MB) / 2003828736 bytes (1911 MB) up to 2863661056 bytes (2731 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3072m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.38 Powered by Forge 13.20.0.2296 Optifine OptiFine_1.11.2_HD_U_B8 16 mods loaded, 16 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2296.jar) 
	UCHIJAAAA	forge{13.20.0.2296} [Minecraft Forge] (forge-1.11.2-13.20.0.2296.jar) 
	UCHIJAAAA	jei{4.3.3.270} [Just Enough Items] (jei_1.11.2-4.3.3.270.jar) 
	UCHIJAAAA	mantle{1.11.2-1.2.0.26} [Mantle] (Mantle-1.11.2-1.2.0.26.jar) 
	UCHIJAAAA	tconstruct{1.11.2-2.7.1.34} [Tinkers' Construct] (TConstruct-1.11.2-2.7.1.34.jar) 
	UCHIJAAAA	immersiveengineering{0.11-63} [Immersive Engineering] (ImmersiveEngineering-0.11-63.jar) 
	UCHIJAAAA	betterwithmods{1.2.9-1.11.2} [Better With Mods] (Better With Mods-1.2.41-1.11.2.jar) 
	UCHIJAAAA	betterwithaddons{@VERSION@} [Better with Addons] (Better With Addons-0.18.jar) 
	UCHIJAAAA	xaerobetterpvp{1.12.7} [Better PvP] (BetterPvP_1.12.7_Forge_1.11.jar) 
	UCHIJAAAA	betterwithhardersteelrecipe{1.1.0} [Better With Harder Steel Recipe] (BetterWithHarderSteelRecipe-1.1.0.jar.jar) 
	UCHIJAAAA	ceramics{1.11.2-1.2.2b} [Ceramics] (Ceramics-1.11.2-1.2.2b.jar) 
	UCHIJAAAA	immersivepetroleum{1.1.0} [Immersive Petroleum] (immersivepetroleum-1.11.2-1.1.0.jar) 
	UCHIJAAAA	tcomplement{${version}} [Tinkers' Complement] (TinkersComplement-1.11.2-0.1.2.jar) 
	UCHIJAAAA	tinkertoolleveling{1.11.2-1.0.1.DEV.641b08f} [Tinkers Tool Leveling] (TinkerToolLeveling-1.11.2-1.0.1.jar) 
	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

	Pulsar/tcomplement loaded Pulses: 
		- ModuleCommons (Enabled/Forced)
		- ModuleFeature (Enabled/Not Forced)
		- CeramicsPlugin (Enabled/Not Forced)

	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.11.2_HD_U_B8
	Render Distance Chunks: 2
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.0.0 - Build 8.15.10.2291
	OpenGlRenderer: Intel(R) HD Graphics Family
	OpenGlVendor: Intel
	CpuCount: 2

**Comment by primetoxinz** [comment]
Optifine is the issue.
