### ISSUE TITLE
Bread dough recipe?

### ISSUE THREAD

**Issue by darthvader45** [BeetoGuy/BetterWithMods#498]
Could you possibly OreDictionary the flour item, or make it so you can craft it with salt and a water bottle/bucket into bread dough, which can then be smelted into bread?  Would add a bit more work, but with this mod, it would be nice.  Also seems a bit more logical, as why would cooking flour suddenly turn it into a loaf of bread?

Also, obligatory JoJo reference: How many loaves of bread have you eaten in your lifetime?

**Comment by primetoxinz** [comment]
Possible future plans *could* lead to this being implemented but for now it won't be, sorry. I suggest adding your own recipe with minetweaker.

**Comment by darthvader45** [comment]
Okay then.  If you change your mind, you know who to message.

**Comment by darthvader45** [comment]
Okay, seems your flour item is OreDict'd so it works with Pam's Harvestcraft.  I'll use that from now on.
