### ISSUE TITLE
Question : gearbox ?

### ISSUE THREAD

**Issue by wizard1399** [BeetoGuy/BetterWithMods#499]
Hello, 
I am using the 1.10.2 version in a pack I am creating. I noticed there is an advanced gearbox. What does this item do? Does it not break in weather? How is it different from the creative gearbox? Thanks for your efforts in working on this mod.

**Comment by primetoxinz** [comment]
The advanced gearbox was an attempt at a new mechanical system that never happened in 1.10.2, so it is useless in that version. The system for it is being implemented into 1.12 currently.
