### ISSUE TITLE
Hand crank giving "Too exhausted" message even when saturation bar is full

### ISSUE THREAD

**Issue by darthvader45** [BeetoGuy/BetterWithMods#500]
Running Forge 13.20.1.2425 and BWM 1.2.9.  Even with a full hunger/saturation bar, I still get the message "You are too exhausted to turn this."  What I don't understand is how a fully-fed, energized, ready-to-kick-mob-arse Steve is too exhausted to turn a simple hand crank.

**Comment by primetoxinz** [comment]
Please update to BWM 1.2.41

**Comment by darthvader45** [comment]
Thanks, fixed that.
