### ISSUE TITLE
How to debark logs before getting a saw

### ISSUE THREAD

**Issue by darthvader45** [BeetoGuy/BetterWithMods#501]
I cannot debark logs using an axe like 1.2.9.  Running same Forge as #500, but 1.2.41 of BWM.  Noticed a knife blade was added.  Will this be used for a knife item for early-game debarking?

**Comment by arfink** [comment]
Debarking in non-hardcore has been moved to a separate mod. https://minecraft.curseforge.com/projects/debarked-logs

**Comment by darthvader45** [comment]
Okay.  Is 1.11.2 no longer supported?

**Comment by DaedalusGame** [comment]
barely. either make your own recipe with crafttweaker or enable hardcore lumber.
