### ISSUE TITLE
(1.12) Many duplicate recipes in JEI

### ISSUE THREAD

**Issue by arfink** [BeetoGuy/BetterWithMods#504]
Using version 1.3.4 for Minecraft 1.12, I have noticed that some recipes in JEI are weird. I have disabled the more expensive redstone options, so things like dispensers and droppers and observers should not be craftable with the more expensive redstone latch. I can still craft using the standard vanilla recipe, but the harder recipes are still in both the regular crafting table section and in the anvil section of JEI. I have also noticed that the anvil recipes do not necessarily follow changes made to crafting table recipes. For example, I have modified several vanilla recipes for the crafting table using CraftTweaker, and the old vanilla recipes will still show up in the anvil. Is this intended, or should I be also editing the anvil recipes?

**Comment by primetoxinz** [comment]
the duplicate recipes is due to exporting all the recipes to json and accidentally forgetting to remove the ones which are optional. I'll fix it eventually.

 The anvil takes all the vanilla recipes on load before CraftTweaker gets a chance to do anything, there might be a way to fix that. I'll have to look into it

**Comment by primetoxinz** [comment]
I'm going to point out that the next release is a VERY large one and will be breaking any mechanical power systems. Both of these fixes will only come to that version.

**Comment by primetoxinz** [comment]
I have fixed most of the duped recipes.

Unfortunately the way we register anvil recipes will not be able to cooperate with crafttweaker, I believe removing it from the anvil through crafttweaker will work though.
