### ISSUE TITLE
postInit Crash when embers is installed

### ISSUE THREAD

**Issue by Pyrofab** [BeetoGuy/BetterWithMods#508]
https://gist.github.com/Pyrofab/c0935e186135e568955817b05eaa4d2a

Minecraft 1.12, Better with mods 1.3.4, Embers 0.221 and AppleCore 2.2.2
Happens on postInit

**Comment by DaedalusGame** [comment]
I think this is fixed in dev, you can grab dev builds from the [jenkins](http://ci.blamejared.com/job/BetterWithMods/)

**Comment by Pyrofab** [comment]
Good to know ! Since I don't have any mods that add dust, I can personally just disable the config option for Hardcore Dusts though.
