### ISSUE TITLE
Implement Animal Breeding Automation tweaks

### ISSUE THREAD

**Issue by BBoldt** [BeetoGuy/BetterWithMods#51]
http://sargunster.com/btw/index.php?title=Animal_Tweaks#Baiting.2FBreeding_Animals

Specifically the part about animals eating food thrown on the ground.

**Comment by BeetoGuy** [comment]
Got a tentative AI solution for this that seems to work. I'll leave this issue open for a day to see if anyone can find any flaws or improve on it.

**Comment by DeGariless** [comment]
When you throw a piece of food on the ground, more than one animal can eat it.

**Comment by BeetoGuy** [comment]
I think I got that solved. Wasn't able to reproduce it in half a stack of wheat with the new checks.
