### ISSUE TITLE
[1.11.2] HCLumber and Harvestcraft Maple Wood

### ISSUE THREAD

**Issue by nmarshall23** [BeetoGuy/BetterWithMods#515]
When HCLumber is enabled it only registers on Plank per Log. 

If Harvestcraft is installed it add a Maple Wood which gives Spruce Planks.
This means that Spruce Logs can not be used to get Spruce Planks.
The same it true of Jungle Wood.

**Comment by primetoxinz** [comment]
This is a bug with pam's, even with HCLumber disabled it doesn't drop a log.
