### ISSUE TITLE
Request: Allow ore-dicted netherrack to be milled.

### ISSUE THREAD

**Issue by arfink** [BeetoGuy/BetterWithMods#516]
It would be awesome if I could grind any flavor of netherrack from Nether Ex in the millstone. The blocks are all ore-dicted correctly, but I'm unsure how to change this myself with something like CT. Of course, the ideal thing would be to have it integrated.

**Comment by primetoxinz** [comment]
what is the oredict entry for the Nether Ex netherrack? just `netherrack`?

**Comment by arfink** [comment]
Yup.

**Comment by primetoxinz** [comment]
Alright, added. Btw, small things like this are easier through our [Discord](https://discordapp.com/invite/b2NxFcU) if you want to join that.
