### ISSUE TITLE
[1.11.2] CraftTweaker Support

### ISSUE THREAD

**Issue by LycanBlackpaw** [BeetoGuy/BetterWithMods#517]
So I'm having issues adding a Stoked Crucible recipe for my modpack (ore > ingot). It's giving me an error stating that it's expecting a closed parenthesis, or ), but it's not missing as far as I can tell.

Here's a link to the pastebin for the script file. https://pastebin.com/sSgb4fYz

The specific error is "ERROR: Error parsing scripts.zs:32 -- ) expected"

Any ideas?

**Comment by primetoxinz** [comment]
all of your itemstacks are missing the surrounding < and > 
it should be like this for example
`<minecraft:iron_ingot>`
