### ISSUE TITLE
Furnaces should be able to burn fuel without something to cook/smelt

### ISSUE THREAD

**Issue by vivagabe** [BeetoGuy/BetterWithMods#518]
Gloom can't be countered unless you have food or ore too cook.  Is it possible to allow fuel to burn in furnaces without something to cook?

**Comment by BeetoGuy** [comment]
Not without replacing the furnace block and tile entity. Usually, what I do is mine a piece of coal and get a stick to keep a torch in my hidey-holes.

**Comment by vivagabe** [comment]
I was in the awkward starting situation where i had a bunch of wood but nothing to cook and no coal, lol.  Thanks for the fast reply.
