### ISSUE TITLE
Dirtslab light glitch

### ISSUE THREAD

**Issue by shootHug** [BeetoGuy/BetterWithMods#522]
![2017-08-11_21 12 22](https://user-images.githubusercontent.com/30671708/29228637-deae1c8c-7eda-11e7-9223-8307c9d0ab99.png)
with the newest version from 1.11.2,  i get some ugly light glitches with the Dirt and Grass slabs. 
It seems that the class file don't use "useNeighborBrightness = true".
In older versions it works just fine but the same with 1.12.

**Comment by meelock** [comment]
Please do not post duplicate reports, the authors of this mod will fix this in their own time. Anyway, thanks for adding info.
