### ISSUE TITLE
Server crash when changing dimensions

### ISSUE THREAD

**Issue by darkphan** [BeetoGuy/BetterWithMods#526]
BTM Version: 1.12-2.0.4
Forge: 14.21.1.2443

When changing dimensions (to a Cavern one in this crash log) the server crashes with the following crash log: https://pastebin.com/1shMQWft

Rolling back to 1.12-2.0.3 resolves the issues.

**Comment by BeetoGuy** [comment]
Should be fixed in dev, just need to push it to CurseForge.

**Comment by BeetoGuy** [comment]
Pushed to CurseForge, should be approved in a few minutes.
