### ISSUE TITLE
Redstone Signal is too slow....

### ISSUE THREAD

**Issue by DaedalusGame** [BeetoGuy/BetterWithMods#534]
Gearboxes overpower too quickly, before the windchime or other detectors can turn it off.
Gearboxes propagate overpower, somehow. This means that more than the first gearbox can be affected by breakage.

**Comment by primetoxinz** [comment]
I thought I had this fixed but after much struggle somehow the gearbox always reads the windmill too soon.

**Comment by DaedalusGame** [comment]
maybe put an overpower counter on the gearbox
