### ISSUE TITLE
Fat broken.

### ISSUE THREAD

**Issue by JoshD8500** [BeetoGuy/BetterWithMods#540]
Apple Pie fills fat instead of hunger using 1.12 version

**Comment by DaedalusGame** [comment]
Fat in general appears to be broken, you cannot acquire fat from overeating most foods anymore.

**Comment by JoshD8500** [comment]
Hunger bar was almost empty it filled a bit of hunger but gave lots of fat pumpkin pie also does this most other foods does not do this will do more testing

**Comment by vivagabe** [comment]
Was HCHunger removed in the latest build?  I cant seem to find the config option.

**Comment by primetoxinz** [comment]
You need applecore installed.

**Comment by vivagabe** [comment]
I have AppleCore installed and still didn't see it.  I'll double check when I get home.  This is for 1.12.1 btw

**Comment by vivagabe** [comment]
Hmm, I have latest AppleCore and latest BwM but still no HCHunger config.  I even deleted my old config and generated a new one,  I have AppleCore compat set to true.

**Comment by primetoxinz** [comment]
Fixed in dev
