### ISSUE TITLE
HCOres Config

### ISSUE THREAD

**Issue by RainbowSaber** [BeetoGuy/BetterWithMods#546]
>         # Number of Materials returned from Smelting an Ore
>         I:"Ore Production Count"=n

This part of the config has no effect on the game (latest,1.12)

Suggestion:
>         # Number of Materials returned from Smelting an Ore **in a Kiln**
>         I:"Ore Production Count"=n

Add an additional config for Kiln recipes. This would help smooth out the techtree and increase compatiblity between HCOres and "normal" Mods, since it allows you to eventually "move past" the reduced ore gen in an interesting and flavorful way.

**Comment by DaedalusGame** [comment]
there exists an additional config for kiln recipes but it's in a different spot

**Comment by RainbowSaber** [comment]
> tweaks {
>     kilnsmelting {
>         # Number of Materials returned from Smelting an Ore in the Kiln
>         I:"Ore Production Count"=1
>     }
> }

Forgot about that one. Maybe move it to HCOres ?

**Comment by primetoxinz** [comment]
That config will stay with the kiln because it allows increasing the production rate of the kiln regardless of whether HCOres is enabled. So it can make the kiln give n ingots if HCOres is disabled.

**Comment by RainbowSaber** [comment]
I can see that, I dont think putting it with HCOres would be too confusing, considering you can tweak HCOres to basically have no effect/positive effect anyways.
Adopting the same syntax for Kiln  (one config to set type (Ingot/Nugget) and one config to set amount) sounds like an improvement, no matter where it is though.

**Comment by primetoxinz** [comment]
It's not whether it's confusing, it's the fact that I literally cannot move it to HCOre due to how the code works. I also don't intend for there to be that many configs.

**Comment by RainbowSaber** [comment]
The suggestion was not the point of this issue:

> >     # Number of Materials returned from Smelting an Ore
> >     I:"Ore Production Count"=n
> 
> This part of the config has no effect on the game (latest,1.12)

**Comment by RainbowSaber** [comment]
Sorry about the nagging in that case, didnt see any indication of a commit in the closing statement.

Keep up the great work
