### ISSUE TITLE
dirt and grass slabs and stairs suggestions

### ISSUE THREAD

**Issue by Hypsellis** [BeetoGuy/BetterWithMods#547]
I noticed the coarse dirt, podzol, and grass path slabs miss. I would suggest to add stair for each one too since slab exist. The slab displays in Minecraft creative tab, and not in the BetterWithMods one.

**Comment by primetoxinz** [comment]
I don't really understand what you mean by the first sentence.
Dirt slabs have a very specific purpose from the original mod, I don't see a reason for Dirt stairs.

**Comment by Hypsellis** [comment]
Oh so you won't add dirt stairs ?

**Comment by primetoxinz** [comment]
Probably not, no.

**Comment by Hypsellis** [comment]
What about coarse dirt, podzol, and grass path slabs ?

**Comment by primetoxinz** [comment]
grass path slabs exist in 1.12, the other two maybe eventually.

**Comment by Hypsellis** [comment]
Hm ok
