### ISSUE TITLE
Mechanical Booster Rails function oddly

### ISSUE THREAD

**Issue by DaedalusGame** [BeetoGuy/BetterWithMods#555]
[This is what a circle looks like](https://cdn.discordapp.com/attachments/337734764461162498/353245360988356609/unknown.png)

As can be seen, two sides are inverted in direction. Perhaps it could match the cauldron tilt direction for consistency?

**Comment by primetoxinz** [comment]
Mechanical Boosters were never even ported over to the new system, at least not by me
