### ISSUE TITLE
[1.10.2] Missing recipes for stone based Sidings

### ISSUE THREAD

**Issue by LordDan1989** [BeetoGuy/BetterWithMods#558]
There are no Saw recipes to create stone sidings. It's a small oversight. This includes all the stone recipes. Stone, Stone Brick, Brick, Ender, White Cobble etc etc. Only the wooden sidings are accessible.

For anyone using CraftTweaker

```
import mods.betterwithmods.Saw;

Saw.add([<betterwithmods:stone_siding:0>, <betterwithmods:stone_siding:0>], <minecraft:stone:0>);
Saw.add([<betterwithmods:stone_siding:1>, <betterwithmods:stone_siding:1>], <minecraft:stonebrick:0>);
Saw.add([<betterwithmods:stone_siding:2>, <betterwithmods:stone_siding:2>], <betterwithmods:aesthetic:6>); // White Stone
Saw.add([<betterwithmods:stone_siding:3>, <betterwithmods:stone_siding:3>], <minecraft:nether_brick>);
Saw.add([<betterwithmods:stone_siding:4>, <betterwithmods:stone_siding:4>], <minecraft:brick_block>);
Saw.add([<betterwithmods:stone_siding:5>, <betterwithmods:stone_siding:5>], <minecraft:end_stone>);
```

**Comment by primetoxinz** [comment]
The basic saw is not supposed to be able to cut stone anything. That will be one of the functions of the steel saw eventually.

**Comment by LordDan1989** [comment]
I see, these do not appear in JEI it seems.

**Comment by primetoxinz** [comment]
Well, considering that 1.10.2 is unsupported version you can either make a PR to fix this or just do it with crafttweaker
