### ISSUE TITLE
Mob drops

### ISSUE THREAD

**Issue by vivagabe** [BeetoGuy/BetterWithMods#562]
Skeletons drop bows too often.  Zombie pigmen shouldn't all be equipped with gold swords.  Also, it may just be my bad luck but I rarely see any mobs with tools or armor.

**Comment by DaedalusGame** [comment]
Do you stick around one area much? Seems regional difficulty will increase the percentage of mobs spawning with armor, up to 15%, and Hard difficulty has a 5% of spawning mobs with weapons, while Normal only has a 1% chance.
About Skeletons: Is that a thing? Currently, all mobs will drop everything they hold... should it not apply to bows that way? IIRC, bows are only string and sticks anyway when rendered, and clog your mobfarm until then...
About Zombie Pigmen, maybe a tweak could be introduced to configure the chance of them holding swords...

[Oh hey, useful link](http://sargunster.com/btw/index.php?title=Changes_to_Hostile_Mobs)

**Comment by primetoxinz** [comment]
I believe Zombie Pigmen always spawn with a Sword *because* of the code to make them always drop it. If a Pigmen isAbleToPickUp or whatever, which is usually like a 25% chance and 100% with the mob drop tweak, they always spawn with a sword. I don't know how we'd fix that one.

**Comment by vivagabe** [comment]
I do usually stick around one spot but recently started venturing out cause of lack of food.  Maybe i bump difficulty to Hard.  I guess skellys dropping bow all the time isnt a huge deal. i just dont remember skellys dropping them as often in BtW.  Thats too bad about zombie pigmen.  In Btw, it was always kind of fun looking for that one pigman with the sword then trying to figure out how you were going to get him without dying the swarm of other pigmen around him lol.  Regardless, your mods have greatly improved 1.12 and i thank both of you for your work.

**Comment by BeetoGuy** [comment]
The old system, back when the items dropped when the entity was killed, determined if an item in a zombie pigman/skeleton's hand could actually drop. I don't know when in the entity construction the item list is available, though.

**Comment by primetoxinz** [comment]
After reading the link Bord posted, we probably should only change Zombies

**Comment by primetoxinz** [comment]
I made this only effect zombies now.
