### ISSUE TITLE
Crash with SimpleCorn in Planter

### ISSUE THREAD

**Issue by nmarshall23** [BeetoGuy/BetterWithMods#567]
My game crashes when I try to grow corn from the [SimpleCorn mod](https://minecraft.curseforge.com/projects/simple-corn), in a Planter.

https://pastebin.com/PN4FGw9B

Loading that world crashes my game. I expect that I have to remove that Planter. 

I'm using Better With Mods 1.2.41-1.11.2

**Comment by primetoxinz** [comment]
Post this to SimpleCorn, tell them I said `world.getBlockState(pos.down()).getBlock().isFertile(world, pos)` should be `world.getBlockState(pos.down()).getBlock().isFertile(world, pos.down())`

**Comment by nmarshall23** [comment]
Thanks I've posted it to his issue tracker.
