### ISSUE TITLE
HC Hunger not working

### ISSUE THREAD

**Issue by vivagabe** [BeetoGuy/BetterWithMods#573]
I created a fresh instance with Better with Mods, Better with Addons, and AppleCore (all the latest versions, all 1.12.1) and it appears that the configs did note generate a HC Hunger option. After playing a few minutes it was obvious that it wasnt working as intended (hunger bar didnt move).   Has anyone else had this issue?

**Comment by primetoxinz** [comment]
Fix incoming here: http://ci.blamejared.com/job/BetterWithMods/118/
