### ISSUE TITLE
Iron, diamond, steel axes shouldnt take durability damage splitting logs

### ISSUE THREAD

**Issue by vivagabe** [BeetoGuy/BetterWithMods#574]
Is it possible to implement this? Also, is github where I should be suggesting these BtW features?

**Comment by Timeslice42** [comment]
Are you sure this is right? I thought they merely didn't take damage when breaking leaves.

**Comment by vivagabe** [comment]
http://sargunster.com/btw/index.php?title=Change_log#Version_4.A2_Timing_Rodent

**Comment by Timeslice42** [comment]
Yeah, I totally didn't know there'd been a new version since Humped Camel. I like all of the changes (including the change to grass growth) except for stumps. Politics can go die in a fire.
