### ISSUE TITLE
[Question] HCStump / Traverse compat

### ISSUE THREAD

**Issue by GeekyNinja** [BeetoGuy/BetterWithMods#575]
G'day, have a question. Not an issue, per se, but wanted to get some feedback.

I'm running Traverse (v1.3.1) alongside Better With Mods (v2.0.10), and have "HCStumping" enabled.

Currently, Traverse trees do not obey this rule, and was wondering if BWM needed to make this happen? I raised with the Traverse dev but they said to come speak to you. I also wondered whether this was somehow linked to issue #553?

Thanks so much :-)

**Comment by primetoxinz** [comment]
HCStumps in BWM is honestly a hack that won't ever work well with other mods. The stump feature in [Better With Addons](https://minecraft.curseforge.com/projects/better-with-addons) is far better for compatibility.

**Comment by GeekyNinja** [comment]
Thanks for the feedback! I'll give that a go. Any hints for the best chance of things to work in regards to config options? Should I turn the BWM HCStumps off and leave BWA Stumps on? Both on?

**Comment by DaedalusGame** [comment]
Both on means that vanilla trees will have BWM stumps and BWA stumps will apply for everything else. Note that BWA stumps are mechanically different: Every upright log on soil is considered a stump and takes longer to break. I'll likely expand the properties of BWA stumps to be more similar to BWM stumps later.

**Comment by primetoxinz** [comment]
In fact I wouldn't mind replacing HCStumps with BWA edition as it is just simpler and more expansive. Could remove HCStump generation but keep the block for now and add the block-less version.

**Comment by vivagabe** [comment]
Would it be possible to make it so that the stump remover could work on BwA stumps?  I love having uses for red mushroom, creeper oyster, and rotten flesh.

**Comment by GeekyNinja** [comment]
Fantastic feedback. Thanks to you both, primetoxinz & DaedalusGame.
