### ISSUE TITLE
[TODO] Refactor classes with many items like ItemMaterial, ItemMechanical, BlockAesthetic

### ISSUE THREAD

**Issue by Koward** [BeetoGuy/BetterWithMods#58]
We should refactor big classes that holds variants that are not variants but instead many different items or blocks.
Look at BWCrafting.java. It's very hard to read. To understand a recipe with ItemMaterial or ItemMechanical you have to check the classes and index a name array with the meta of the stack. This is madness.

Variants should not be used this way, these are different items. They should have there own registry entry, even if they share the same class, not this ugly and hard to maintain array of names.

It's not hard to do, but there's a problem : they would then have their own registryName, and I fear the old items would disappear from worlds.

**Comment by primetoxinz** [comment]
I understand the want to split ItemMaterial into multiple items, but it's an unnecessary hassle and a waste of item ids, even though there are way more than you could ever need. 
To help with the madness I did have 
https://github.com/BeetoGuy/BetterWithMods/blob/master/src/main/java/betterwithmods/items/ItemMaterial.java#L22-L28
to call by their variant name and find the meta.
Old items would 100% disappear, there are ways to handle it but it just doesn't matter imo

**Comment by BeetoGuy** [comment]
Yeah, that was my thinking, regarding IDs. Especially back during 1.7.10 when I was cramming in as many mods as I could to try and break Minecraft, and IDs started becoming a very real issue. While the internal method to get the stack metadata works, maybe the API should have something to let people find those stacks externally?

**Comment by Koward** [comment]
These static methods could be used in BWCrafting, that would make things easier to read, that's great.

**Comment by primetoxinz** [comment]
Closing to clean up issues
