### ISSUE TITLE
Buckets seem to be broken

### ISSUE THREAD

**Issue by Anarchquixote** [BeetoGuy/BetterWithMods#588]
The bucket recipe seems to be broken. It will not build with either the vanilla recipe or the BTW recipe

**Comment by primetoxinz** [comment]
works just fine, make sure you don't have other mods removing the recipe.
![image](https://user-images.githubusercontent.com/4721642/31318338-94543f4c-ac1e-11e7-84ea-1ad849f555fa.png)
