### ISSUE TITLE
Pam's Harvestcraft food values in HCHunger 

### ISSUE THREAD

**Issue by kiwifrogg** [BeetoGuy/BetterWithMods#596]
Harvestcraft food values are much lower than usual while the BWM foods are quite high.  For example with HCHunger on, beef wellington give 3 hunches(normally 9) while kebabs from BWM gives 4.  most the pams meals give 2 hunches(normally 6) while pork dinner and tasty sandwich gives 3 for loads less effort.  The problem is if you add spice of life with diminished returns the pams food almost becomes useless, and you spend the entire game cooking and eating .

**Comment by DaedalusGame** [comment]
Let this be a lesson in "you can't put every single food overhaul into the same mod install at once"

**Comment by primetoxinz** [comment]
I have no interest in supporting Pam's or SoL mainly for the reasons @DaedalusGame mentioned and its more work than worth. If you still want it feel free to make an addon, it's rather easy.
