### ISSUE TITLE
Redstone wire pops off when lift platform settles

### ISSUE THREAD

**Issue by DaedalusGame** [BeetoGuy/BetterWithMods#69]
[Nasal voice] according to the wiki the platform should move rails and redstone wire. 
Moving it is fine, but when the platform settles, the dust pops off sometimes. (There's also a rendering glitch with it but it's not that important)

69, dude.

**Comment by MRebhan** [comment]
Yep, I encountered this in my testing but I thought I fixed it. I might take a look at it once more ;)

**Comment by MRebhan** [comment]
Fixed (probably): https://github.com/BeetoGuy/BetterWithMods/pull/73
