### ISSUE TITLE
Hunger doesn't tick down with Hardcore Hunger disabled?

### ISSUE THREAD

**Issue by BeetoGuy** [BeetoGuy/BetterWithMods#71]
I've been seeing quite a few posts about this. At first, I thought it had something to do with AppleCore, but it doesn't look like that's the case as of a more recent report.

**Comment by Koward** [comment]
I confirm this bug. I have not found how it happens yet, but I have something in mind : the total value in HC hunger is higher than vanilla (20 becomes 60). If someone was to disable Hardcore Hunger after creating its world, maybe the previous (could be 60) will stay, so the hunger will take a while before coming back to noticeable (<20) levels.
I have yet to check if it's possible, but that's a lead.

**Comment by Koward** [comment]
Probably fixed by commit [7f9d6be](https://github.com/BeetoGuy/BetterWithMods/commit/7f9d6bead2fcb068de3264cbb78e72d19fbb619a) but that needs to be checked (can't run myself the mod ATM).

**Comment by BeetoGuy** [comment]
Yeah, I think it was resolved, now that I look back at testing the server syncing.
