### ISSUE TITLE
Stoked Fire - Crash

### ISSUE THREAD

**Issue by Tetrajak** [BeetoGuy/BetterWithMods#74]
I'm getting crashes on both my server and single player whenever my friends or I attempt to stoke a hibachi. The stoked fire appears to form, and the game crashes a couple of seconds after that. I've been really enjoying the mod up until this point!

Error log: http://pastebin.com/KLvsVe3x

**Comment by BeetoGuy** [comment]
Does it happen without OptiFine loaded? Really seems like that mod's been doing some weird things with block states.

**Comment by Tetrajak** [comment]
Yes, the same error happens without OptiFine as well.

**Comment by BeetoGuy** [comment]
Alright, I'm getting an additional check going that might fix it, though I can't be certain since I don't seem to be able to replicate on my end.

**Comment by Tetrajak** [comment]
Thanks for working on this. I'm still getting the same error when it's only BWM: http://pastebin.com/G99KvUJD

**Comment by Tetrajak** [comment]
Hey, just grabbed your update that you pushed to curseforge, and this bug is fixed! Thank you for the quick update!

**Comment by BeetoGuy** [comment]
That's a relief, thanks for telling me it was definitely fixed.
