### ISSUE TITLE
[Forgotten feature]Filtered Hopper emitting a RS signal when full

### ISSUE THREAD

**Issue by Erik3003** [BeetoGuy/BetterWithMods#75]
"If all the slots in a hopper inventory contain items, the hopper will produce redstone power."
 source: http://www.sargunster.com/btw/index.php?title=Hopper
This change should be fairly easy to implement and would add some needed control, since the comparator doesn't work on the filtered hopper.

**Comment by primetoxinz** [comment]
Added comparator support, which gives more flexibility than only full
