### ISSUE TITLE
0.12 Server Startup Crash

### ISSUE THREAD

**Issue by zcorcoran** [BeetoGuy/BetterWithMods#77]
Server running 0.12 crashes during the transition from preinitialization to initialization. It looks to be a client-only function being called:

http://pastebin.com/vvh61rfT

[22:44:19] [Server thread/ERROR] [FML]: Caught exception from betterwithmods
java.lang.NoClassDefFoundError: net/minecraft/client/renderer/block/statemap/IStateMapper

**Comment by Tetrajak** [comment]
I am able to reproduce this on my server as well; http://pastebin.com/Vy52Sebu

**Comment by BeetoGuy** [comment]
Looks like it's related to Immersive Engineering's registry. I'll see if I can fix and push an update real quick.

**Comment by BeetoGuy** [comment]
Alright, looks like I finally tracked the problem down. Some rendering methods getting moved out of the proxy class was causing it, adding SideOnly to them seems to have fixed it.

**Comment by BeetoGuy** [comment]
Yeah, looks like it's all good now. I'll upload the fix to CurseForge.
