### ISSUE TITLE
Can't Right-Click Interact with Blocks when holding item (0.12-hotfix2 and 1)

### ISSUE THREAD

**Issue by zcorcoran** [BeetoGuy/BetterWithMods#80]
I can't interact with anything on right click with anything other than an empty hand. It seems like the log debarking is encountering an issue, which leads to the entire right click interaction failing.

Here's the log of me vainly trying to open chests and stuff:
http://pastebin.com/n63m2uHW

So far I've found that this applies to doors, chests, storage drawers, and BWM machines, so it seems like pretty much all right-click interactions are affected.

Interacting with things empty handed works as expected.

**Comment by BeetoGuy** [comment]
Can't seem to replicate on my end. Seems strange that the item doesn't give a harvest level in those logs.

**Comment by zcorcoran** [comment]
It doesn't seem to happen in singleplayer, just multiplayer. I'll try updating the Forge version on my server, it's kind of old.

The actual console output might also be more helpful (the log was missing the list of listeners that precedes the error): http://pastebin.com/HNtCk18x

**Comment by BeetoGuy** [comment]
Yeah, it doesn't look like it's on our end.

**Comment by zcorcoran** [comment]
Yeah, updating Forge on the server to 12.18.1.2095 fixed it, so we're good.
