### ISSUE TITLE
Console Spam and World Lag

### ISSUE THREAD

**Issue by jsaggers** [BeetoGuy/BetterWithMods#83]
Using the latest version of BetterWithMods 0.12 hotfix2.
World lags after a while especially when getting near a village.
The console spam is out of control (check included text file)
[bett-with-mods-console-errors.txt](https://github.com/BeetoGuy/BetterWithMods/files/509961/bett-with-mods-console-errors.txt)
That is just a small portion of it.
Just thought I would let you know.

**Comment by BeetoGuy** [comment]
Yeah, I think I see where the problem is. For the moment, it can probably be alleviated by disabling Hardcore Villagers in the config.

**Comment by Koward** [comment]
You could use EntityVillager.getIsWillingToMate(false) to get the field, I don't see the use for reflection here.

**Comment by primetoxinz** [comment]
@Koward because getIsWillingToMate goes through other code, like the need for the villager to have food in it's inventory

**Comment by BeetoGuy** [comment]
Alternatively, isWillingToMate can be changed to public in the access transformer.

**Comment by primetoxinz** [comment]
Reflection is honestly better than AT, but either way works

**Comment by BeetoGuy** [comment]
Alright, I'll just change the reflection up to fix it.

**Comment by Koward** [comment]
@primetoxinz I do not think so. When using getIsWillingMate(false), the condition if (!this.isWillingToMate && updateFirst && this.hasEnoughFoodToBreed()) stops at updateFirst and the rest of it is not executed.
Therefore the only thing that matters is return this.isWillingToMate;
