### ISSUE TITLE
[1.10.2] Server start up crash

### ISSUE THREAD

**Issue by ruyanve** [BeetoGuy/BetterWithMods#84]
Using Better With Mods-0.12.1-1.10.2  on Forge 2095, I'm getting the following crash on server start uo:
http://beta.pastee.com/ejks5

**Comment by BeetoGuy** [comment]
Looks like it's something wrong with Hardcore Hunger, probably something to do with the config change event.

**Comment by ruyanve** [comment]
I disabled that specific config option, will test on a vanilla forge install and regen the config.

**Comment by BeetoGuy** [comment]
Yeah, I think I narrowed down the particular event that was causing it. I'll release a hotfix when I take care of a few other crashes.

**Comment by ruyanve** [comment]
Sweet! I'll hold off on updating then for now and bring the beast back up. 
Cheers!
