### ISSUE TITLE
[Suggestion] Comparator Support

### ISSUE THREAD

**Issue by accessdenied0** [BeetoGuy/BetterWithMods#85]
Hello @BeetoGuy, 

First I want to thank you for this port of this very interesting mod (BTW). I always wanted to play with this mod and the options to disable some of the Hardcore-features do I like very much.

Secondly: It might be not the highest priority on your list, but I would like to see Redstone-Comparator support for some of your blocks (mainly with Inventory e.g. Millstone), to be able to automate the input and maybe to disable them.

I hope you like that suggestion,

access_denied

**Comment by DaedalusGame** [comment]
what does this mean
you can disable any mechanical block by applying redstone to the closest gearbox
Millstones already have an open inventory, i believe so you can just pipe items in

Did you maybe mean Comparator support?

**Comment by accessdenied0** [comment]
I mean [Comparator ](http://minecraft.gamepedia.com/Redstone_Comparator) Support. For example:
Are processable Items in the Mill and how full it is from 0-15 and so on.
