### ISSUE TITLE
CraftTweaker support for filtered hopper?

### ISSUE THREAD

**Issue by MechWarrior99** [BeetoGuy/BetterWithMods#88]
So, I just learned that you can get flint and sand from tossing gravel on a filtered hopper that has a wicker filter. I was wondering if we could get CraftTweaker support for the filtered hopper? I think it would be really cool if we could.

If not that is understandable of course. :)

**Comment by BeetoGuy** [comment]
It might take a while to get a system that will work that way, but I know it was planned at one point. I'll keep this open and flagged as "enhancement" to remind myself to look into it.

**Comment by primetoxinz** [comment]
Finished
