### ISSUE TITLE
Burn times of BWM items/blocks are wrong

### ISSUE THREAD

**Issue by Erik3003** [BeetoGuy/BetterWithMods#90]
After playing around with JEI fir some time, I noticed, that every burnable item in BWm except bark and nethercoal has an burntime of 300 (1,5 items). This is ridiculous, considering you can saw a log into 6 planks and two bark, making a burn capacity of 6 * 1.5i + 2 * 0.5i  = 10i(i stands for smelted item), already being better than charcoal (considering you can double charcoal by using a kiln this isn't a big problem), BUT you can also cut the planks into sidings, then into mouldings and then into corners, rising the burn capacity to 6 * 2 * 2 * 2 * 1.5i + 2 * 0.5i = 73i, because corners also have a burn time of 300 (1.5i), meaning you can smelt 73 items with JUST ONE LOG.

**Comment by BeetoGuy** [comment]
Yeah, I've been meaning to address that.

**Comment by Erik3003** [comment]
Still isn't fixed...
The problem is the Material.WOOD, which is hardcoded into the vanilla furnace to give a burn time of 300.
(see net.minecraft.tileentity.TileEntityFurnace, getItemBurnTime())
You might also add appropriate burn times for wicker, grates, slats, tables and benches.

**Comment by BeetoGuy** [comment]
This seems like a problem that doesn't just extend to my mod, now that I look at it. Wooden slabs from other mods would also have a burn time of 300. I can probably do a workaround by changing the block's material to something else, but that just feels like a band-aid solution.
