### ISSUE TITLE
[Suggestion] Support Biomes O' Plenty Woods

### ISSUE THREAD

**Issue by Shadows-of-Fire** [BeetoGuy/BetterWithMods#93]
I don't know how much trouble it would be to implement, but I would enjoy it if both vanilla and BoP logs could all get the hardcore lumberjack treatment instead of just the vanilla logs.  I realize that it would require a compat and bark items for each log, but it would be nice to have.

**Comment by WolfieWaffle** [comment]
I think ideally it could dynamically support any wood, I know that Agricraft has done that with it's wooden blocks so you could look at their source code.

**Comment by primetoxinz** [comment]
info saved [here](https://github.com/BeetoGuy/BetterWithMods/projects/2)
