### ISSUE TITLE
[Bug] Duplication Glitch in Mill Stones

### ISSUE THREAD

**Issue by Tetrajak** [BeetoGuy/BetterWithMods#94]
I've got a couple of powered Mill Stones, and they're not consuming items, but they're still spitting out the appropriate results.

Version used: 0.12.3

**Comment by BeetoGuy** [comment]
I can't seem to replicate it on my end.

**Comment by Tetrajak** [comment]
It's been happening to us on our server consistently.

**Comment by DaedalusGame** [comment]
Replicated it on the curse release. Haven't tested head revision.

**Comment by BeetoGuy** [comment]
Strange, I wonder why it's happening in the Curse release, but not the file I uploaded.

**Comment by BeetoGuy** [comment]
I'm wondering if it's more a Forge issue. I can't replicate it with a Curse-hosted copy, either.

**Comment by Tetrajak** [comment]
Which version of Forge would you recommend for use with the latest version of BWM?

**Comment by BeetoGuy** [comment]
It's built on 2076, which seems recent enough. If you're using a later version, I might have to take a look at it.

**Comment by Tetrajak** [comment]
Ah, I've been using 2073 on my client and server. I've tried it out on both with the latest recommended version (2099), and all seems well!

**Comment by BeetoGuy** [comment]
Good to hear. I might have to add a Forge version check, this seems to become a recurring issue.
