### ISSUE TITLE
Wolfs not producing dung.

### ISSUE THREAD

**Issue by phrostt** [BeetoGuy/BetterWithMods#97]
I assume a lot of the mechanics are same as in BTW. I made a dark room for wolves and gave them plenty of room, they do not eat any food thrown to them and never produce dung. Would appreciate some help with this, I really want to advance without cheating.

**Comment by DaedalusGame** [comment]
Looking at the code, it appears that currently any adult animal will shit every once in a while, the BTW specific way of wolves in dark rooms appears to not be a thing yet

**Comment by phrostt** [comment]
I have an animal farm and im yet to see shit from any of them :(

**Comment by BeetoGuy** [comment]
The config might be disabled, if that's the case. An alternative way of getting dung is by killing passive mobs with the saw.

**Comment by phrostt** [comment]
You need the saw to get wood bark and you need wood bark to get the tanned leather, unless im missing something here.

**Comment by DaedalusGame** [comment]
Use a knife or axe on a log to strip it.

**Comment by phrostt** [comment]
Thank you.
