### ISSUE TITLE
[0.12.3 - 1.10 hotfix3] Saw crashes with certain items

### ISSUE THREAD

**Issue by nightlone** [BeetoGuy/BetterWithMods#98]
The saw will crash the game when trying to place these items on top of it:
1) Pumpkin
2) Jack O' Lantern 
The log may be of use for you as well:

[2016-10-16-5.txt](https://github.com/BeetoGuy/BetterWithMods/files/532385/2016-10-16-5.txt)

**Comment by BeetoGuy** [comment]
Looks like it's related to the pumpkin/jack o' lantern's placement check. I think I've got it resolved.

**Comment by nightlone** [comment]
Awesome mod btw :) though I may have found a cross mod incompatibility, gonna check on it some more
